---
title: "2012 Honda Civic Tips"
author: "J. R. Minter"
date: "Started 2020-05-07, Last modified: 2021-09-04"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

[Back to Index](../README.html)

My Honda Civic has 43,000 miles as of 2021-09-04

# Security System Alarm

The security system alarm activates when the doors, trunk, or hood are
opened without the key, or remote transmitter.

When the security system alarm activates, the horn sounds intermittently
and all of the exterior lights flash. (it is **really annoying**).

# To deactivate the security system alarm:

- Unlock the vehicle using the key, or remote transmitter. The system,
along with the horn and flashing lights, is deactivated.

# Immobilizer System

- Leaving the ignition key in the vehicle can result in theft or
accidental movement of the vehicle.

- Always take the ignition key with you whenever you leave the vehicle
unattended.

- Do not alter the system or add other devices to it. Doing so may damage
the system and make your vehicle inoperable.

# Security System Alarm

The security alarm continues for a maximum of two minutes until the
security system deactivates.

[Back to Index](../README.html)