---
title: "Tips on Using Slidify"
author: "J. R. Minter"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: united
    highlight: pygments
---
```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# make this an external chunk that can be included in any file

library(knitr)
options(width = 72)
opts_chunk$set(message = F, error = F, warning = F, comment = NA, fig.align = 'center', dpi = 100, tidy = F, cache.path = '.cache/', fig.path = 'figure/')

options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
knit_hooks$set(plot = knitr:::hook_plot_html)
```


[Back to Index](../README.html)

``Slidify`` is a package by Ramnath Vaidyanathan that may be used
to create HTML5 slides from R.


**Note 2015-05-04:** There is apparently a problem with slidify working with `stringr-1.0.0`. The interim solution is to revert to revert to `stringr-0.6.2`.

# Installation
One installs Slidify from github in R with the commands

```
require(devtools)
install_github('slidify', 'ramnathv')
install_github('slidifyLibraries', 'ramnathv')
```
# Getting started
RV provides some helpful tips to get started on his
[github](https://github.com/ramnathv/slidify) page.

Here are the first steps (from R)

```
setwd("~/work/play")
library(slidify)
author("jrmSlides")
```

This creates a basic framework in directory ``jrmSlides`` with
an ``index.Rmd`` template and an ``assets`` directory. When you
edit the ``index.Rmd`` template and ``Knit HTML`` in RStudio, this
creates the ``index.md`` and ``index.html`` files and a ``libraries``
directory.

If you want a splash image on a starter slide and a logo on the
title slide, add

```
logo        : latex.png
biglogo     : mandril.png 
```
just above ``framework`` in the YAMML top matter and put the images
in the ``assets/img`` directory.

We probably want to change
```
widgets     : []  # {mathjax, quiz, bootstrap}
```
to
```
widgets     : [mathjax, bootstrap]  # {mathjax, quiz, bootstrap}
```

Then run ``Knit HTML`` in RStudio
to incorporate the changes.


# Alchemy
## io2012
``io2012`` is a convenient framework for slides. I find the default
text too small and like to add some color to the title slide. We
need to edit files in the ``libraries/frameworks/io2012`` directory.

### css/slidify.css
change the ``article`` styles

```
article p, article li, article li.build{
  font-family: 'Helvetica', 'Crimson Text', 'Garamond',  'Palatino', sans-serif;
  text-align: justify;
  font-size:36px;
  line-height: 1.5em;
  color: #474747;
}
```
### layouts/deck.html
 Change the ``hgroup`` in the title slide to
 
 ```
       <hgroup class="auto-fadein">
        <h1 style="color:#CC2904">{{ title }}</h1>
        <h2 style="color:#474747">{{ subtitle }}</h2>
        <p style="color:#474747">{{ author }}<br/>{{ job }}</p>
      </hgroup>
 ```
 Note that we are using a darker gray for the text.
 
 ### Making a reproducible, custom theme.
 Once one gets a set of changes that we would like
 to recycle, one can always make a new copy of
 ``io2012`` in the ``[R-HOME]/library/slidifyLibraries/libraries/frameworks/`` directory and incorporate the changes there.


[Back to Index](../README.html)
