---
title: "Octave Tips"
author: "J. R. Minter"
date: 'Started: 2019-03-21, Last modified: 2019-04-17'
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
    highlight: tango
---

[Back to Index](../README.html)

# Introduction

Gnu Octave is an Open Source program similar to Matlab.
Binaries are available [here](https://www.gnu.org/software/octave/).

There is a version that runs from the command line and a GUI version.

As of 2019-03-21, the current release is `Octave 5.1.0.0` which was
released on 2019-03-01.

One **_major advantage_** of the Windows installer is that it comes
bundled with many (all key anyway...) packages from Octave Forge.
This saves a lot of headaches while compiling packages, especially
on MacOS. I have a Parallels Win10 x64 VM for this reason...

## Flatpak install

On Debian and Ubuntu, we install using flatpak as outlined
[here](http://ubuntuhandbook.org/index.php/2019/03/gnu-octave-5-1-0-released-with-hidpi-support-howto-install/).

1. `sudo apt-get install flatpak`

2. `sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

3. `sudo flatpak install flathub org.octave.Octave`

4. Launch from the Gnome launcher. Pin to Favorites.

5. Uninstall as desired:

    ```
    flatpak install flathub org.octave.Octave
    sudo apt-get remove flatpak
    
    ```


# Octave resources

1. [octave Online](https://octave-online.net/)

2. The [NexMirror](https://github.com/NexMirror/Octave) Octave source
repository on github.

3. Richard Schneeman's Octave code for the 2011 stanford machine learning
[ machine learning](https://github.com/schneems/Octave) class.

4. The [flathub](https://github.com/flathub/org.octave.Octave) Octave git
repository

5. Sublime Text [Octave](https://github.com/apjanke/OctaveSupport) support.

    **_Usage_**:
    
    Once installed, there will be an “Octave” choice under the
    `View > Syntax` menu. Open an Octave `.m` file and select it.
    You may also want to do:
    
        `View > Syntax > "Open all with current extension as..." > Octave.
    
    **_Snippets_**:
    
    To use the code snippets, type one of their names and hit the `Tab`
    key. Available snippets:

    - `octclass` – A classdef class definition, in GNU Octave style
    
    - `octfun` - A function definition, in GNU Octave style. This is a
    fixed-up version of the one found in Sublime Text’s Matlab package.

    - `unwind` – An unwind_protect block
    
    - `unwtry` – A combination unwind_protect + try/catch block
    

6. The [homebrew](https://github.com/octave-app/homebrew-octave-app)
code for the `Octave.app`

7. The [Octave.app](https://github.com/octave-app/octave-app-bundler) bundler.

8. Some [numerical](https://github.com/IPGP/num-matlab) functions

9. [tertiary Courses](https://github.com/tertiarycourses/OctaveTraining)
Octave training examples.

10. A collection of [scripts](https://github.com/RoaldFre/octaveScripts)

11. Useful [functions](https://github.com/ptflinner/OctaveFunctions/blob/master/functions.m)

12. [nice examples](https://github.com/johnfkraus/octave)

13. [Linear Algebra examples](https://github.com/Lo1s/Laff)


# Getting the path right

Getting the path right was fun

I ended up doing this

1. I set my Octave function folder as

    ```
    C:/Users/jrminter/Octave (note upper case...)
    ```

2. I ran

    ```
    rmpath("C:/Users/jrminter/octave")  (my old path renamed to `Octave`)
    addpath("C:/Users/jrminter/Octave")
    savepath() (this saved the path to C:/Users/jrminter.octaverc)
    ```

On the Mac, we install via Homebrew. This installs `Octave 4.4.1`.

Developer MacOSX App downloads are available
[**here**](http://octave-app.org/Developer-Downloads.html).

There is extensive documentation
[online](https://octave.org/doc/interpreter/index.html#SEC_Contents).

## Development and Debugging on Octave for macOS

There is also discussion regarding the development of the macOS app
[**here**](https://github.com/octave-app/octave-app/issues/25).

One suggestion for a **spinning ball** on Octave on MacOS - try:

    ```
    rm -rf ~/.config/octave 
    ```
    
    and restart...


# Using Octave in Rmarkdown

## Code chunks must be self-contained

We need to set the path to the Octave executable to run Octave chunks
in Rmarkdown. **_N.B._ Octave code chunks must be _self-contained_**
**unlike** R code chunks.

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
octaveExe <- Sys.getenv("OCTAVE_EXECUTABLE")
octaveExe
```

On `crunch`, I set the environment variable `OCTAVE_EXECUTABLE` to:

```
C:/Apps/Octave-5.1.0.0/mingw64/bin/octave-cli-5.1.0.exe
```

On `jrmFastMac`, I set `OCTAVE_EXECUTABLE` to:

```
/usr/local/bin/octave
```

in Renviron in the `jrm_dotfiles` git repository. This
is symbolically-linked to `.Renviron`

Here is an example code chunk. Since I don't want this to execute
here, note that the configuration has been moved to inside the
block of triple back-ticks...

```
{octave, engine.path=octavePath}
   A=[1,2,3;4,5,6]
   [minval, row] = min(min(A,[],2));
   [minval, col] = min(min(A,[],1));
   [minval, row, col]

```

# Key Elements

## Listing installed packages

List the installed packages with:

```{octave list_installed_pkgs, engine.path=octaveExe}
pkg list

```

### Windows

On Win they were in:    

```
C:\Apps\Octave-5.1.0.0\mingw64\share\octave\packages
```

### Debian

On Debian Sid, they are in:

```
Package Name  | Version | Installation directory
--------------+---------+-----------------------
   dataframe  |   1.2.0 | /usr/share/octave/packages/dataframe-1.2.0
     general  |   2.1.0 | /home/jrminter/octave/general-2.1.0
       image  |  2.10.0 | /home/jrminter/octave/image-2.10.0
          io  |  2.4.12 | /home/jrminter/octave/io-2.4.12
  statistics  |   1.4.0 | /home/jrminter/octave/statistics-1.4.0
    symbolic  |   2.7.1 | /home/jrminter/octave/symbolic-2.7.1    
```





## Setting up for working with operators

1. element by element operators are the operator with a preceding `.`.
For example:

    ```{octave elem_by_elem, engine.path=octaveExe}
    A = [1,2,3,4];
    B = [2,4,6,8];

    A .* B
    A .+ B
    A .^ B
    ```

2. We can set row and column vectors and matrices

    ```{octave row_col_vec_mat, engine.path=octaveExe}
    A = [1 2 3 4]
    B = [2;4;6;8]
    C = [1 2 3 4;5 6 7 8;9 10 11 12]
    ```



# An Octave Tutorial Series on YouTube

[DrapsTV](https://www.youtube.com/watch?v=X0xLTKRWPgo&list=PL1A2CSdiySGJ6oZe6XB-TTCFuHc5Fs1PO)
from 2014. Decent...

## Setup for the command line version

1. Set a custom prompt.

    ```
    PS1("\# > ")
    ```

    gives a simple command line, although the standard prompt
    is reasonable:
    
    ```
    octave:1> 
    ```
    
2. Clear the screen

    ```
    octave:1> clc 
    ``` 

## Special Functions

1. `ones(n,m)` - Generates a matrix `n x m` of 1's

2. `zeros(n,m)` - Generates a matrix `n x m` of 0's

3. `eye(n) or eye(n,m)` Generates an identity matrix

4. `rand(n,m)` Generates a matrix `n x m` of randomly distributed elements

    ```{octave ones_mat, engine.path=octaveExe}
    ones(3,5)
    
    rand(3,5)
    
    eye(4)
    ```
## The colon operator


    ```{octave colon_op, engine.path=octaveExe}
    S1 = 1:5
    ```
    
    ```{octave colon_op_step, engine.path=octaveExe}
    S2 = 2:2:10
    ```

## Indexing

    ```{octave indexing, engine.path=octaveExe}
    S = [1 2; 3 4]
    
    S(1,1)
    S(1,[1 2])
    S(1,1:2)
    S(1,:)
    ```

## Other functions

    ```{octave other_funcs, engine.path=octaveExe}
    x = sprintf("Pi to 8 decimals: %0.8f", pi)
    
    vec = [pi, 2*pi]
    ceil(vec)
    floor(vec)
    round(vec)
    max(vec)
    min(vec)
    ```
    
    We can get help with `help(rand)`
    
    
See the [intereter](https://www.gnu.org/software/octave/doc/interpreter/)
docs...

## Loading and using data

[link to data](https://www.mediafire.com/folder/ffvd5sfasy2bz/Tutorial_3_-_Loading_%26_Saving)

Octave uses a working directory just like a terminal or command line.
It supports most commands from both Windows and *nix.

- `cd` - Change directory

- `ls`, `dir` - List current directory

- `pwd` - Print current working directory

Octave has built in `load()` and `save()` functions that make it easy to
load and save many types of data files.

`load filename` or `load("filename")` loads the data into a vector or
matrix.

Octave can also save data easily

`save <filename> <variable>`

Octave supports temporary files. These are deleted when Octave closes.

The syntax is

```
f = tmpfile
save f <variable>
load f
```

```{octave load_dat, engine.path=octaveExe}
m = load("./dat/single.dat");
length(m)

v = rand(5,1)

save ./dat/mydata.dat v
    
f = tmpfile
save f v
v = [0]
load f
    
a = [1; 2; 3];
b = [4; 5; 6];

[a; b]

c = [a b]

size(c)

length(c)

length(a)
    
```

Note that we can merge (concatenate) data

```{octave concat, engine.path=octaveExe}

A = [1;2;3];
B = [4;5;6];
C = [A B]
D = [A;B]
```

## Size and Length functions

- size(m) - returns a matrix of dimensions

- length(m) - returns the longest dimension


```{octave sz_len, engine.path=octaveExe}

A = [1;2;3];
B = [4;5;6];
C = [A B]
D = [A;B]

size(C)
length(C)

size(D)
length(D)
```

Octave and load and save:

- Matlab files
- csv files
- tabulated /  whitespace files

Bear in mind...

- If you **don't specify a variable**, octave will save 
**_all_ the variables in the session**.

- If you want to save plain text, add the option `-ascii`.

- Specify what you want with:

   ```
   save <filename> var1 var2
   ```
- use `addpath("path/to/my/folder")` to add a load/save path.

## Plotting in Octave

Octave supports many different types of plots.

### Simple X-Y Plots

```
y = 0:20;
y = y .^2;
plot(y)
```

The `hold on` in console

`close` will close the screen.

### Scatter Plots

```
y = 0:20;
y = y .^2;
x = 0:20;
scatter(x,y)
```

### Histograms

```
a = randn(1000, 1);
hist(a)
hold(on)
```

default is 10 bins

specify the mumber

```
a = randn(10000, 1);
hist(a, 50)
hold(on)

```

### Contour plots

```
x = [1 2 3 2 1];
y = x;
z = x' * y;
z
axis([1 5 1 5]);
contour(z);
```

### Polar plot

```
x = 0:0.1:2*pi;
size(x)
y = linspace(0.1, 0.1, 63);
polar(x,y)
```

### Pie Charts

```
a = 1:6;
pie(a);
```

```
a = 1:6;
e = [1 0 1 0 1 0];
pie(a,e);
```

### 3D Plots

```
x = -10:10
y = -10:10
[x,y] = meshgrid(x,y)
z = x .^2 + y .^2
mesh(x,y,z)
meshc(x,y,z)
meshz(x,y,z)
surf(x,y,z)

//saving//
print -dpng ‘mymesh.png’
```

## Control Statements

The two control statements in Octave are `if` statements and `repetitions`
(`for` loops and `while` loops).

### Boolean (Comparison) Operators

- `==` Is equal to

- `!=` Is **not** equal to

- `~=` Is **not** equal to

- `>` Greater than

- `<` Less than

- `>=` Greater than or equal to

- `<=` Less than or equal to

### `if` statement and `for` and `while`  loops


```{octave simple_if, engine.path=octaveExe}
% simple if
x = 6;
if x >= 5,
    disp("x is larger than 5!");
end;
```

```{octave if_elseif_else, engine.path=octaveExe}
% if-elseif-else
x = 6;
if x > 10,
    disp("x is bigger than 10!");
elseif x > 0,
    disp("x is greater than 0 but less than 10!");
else
    disp("x is negative!");
end;
```

```{octave for_loop, engine.path=octaveExe}
% for loop
for i=1:10,
    disp(sprintf("%ith index",i));
end;
```

```{octave while_loop, engine.path=octaveExe}
% while loop
i = 1;
while i < 10,
    disp(i);
    i=i+1;
end;
```

```{octave break_statement, engine.path=octaveExe}
% break statements
n = 1;
v = 0;
while true,
    v = v + n;
    if n > 4,
  break;
    end;
    n = n + 1;
end;
v
```

## Defining functions

### Editing from the command line

```
edit mini.m
```

Then type the function...

### Examples

```{octave minimum_func, engine.path=octaveExe}
function ret = minimum(x)
  ret = x(1);
  for i = 2:length(x),
    if x(i) < ret,
      ret = x(i);
    end;
  end;
endfunction

y = [1 2 -5 7 8];
minimum(y)

```

```{octave minmax_func, engine.path=octaveExe}
function [low,high] = minmax(x)
  low = x(1);
  high = x(1);
  for i = 2:length(x),
    if x(i) < low,
      low = x(i);
    elseif x(i) > high,
      high = x(i);
    end;
  end;
endfunction
  
y = [1 2 -5 7 8];
minmax(y)
```

Add error checking

```{octave minmax_err_func, engine.path=octaveExe, error=TRUE}
%
% Note: knitr chunk option error=TRUE to permit the error message to print out
%
function [low,high] = minmax(x)
  if nargin != 1,
    usage("minmax(vector)");
  end;
  if isvector(x),
    low = x(1);
    high = x(1);
    for i = 2:length(x),
      if x(i) < low,
        low = x(i);
      elseif x(i) > high,
        high = x(i);
      end;
    end;
  else
    error("minmax expects a vector!");
  end;
endfunction

y = [1 2 -5 7 8];
minmax(y)

% try a matrix...
y = [1 2; 3 4]
minmax(y)
```

## Plots

These crash in Rmarkdown chunks...

### Scatter plots

```
y = 0:10;
y = y .^2;
x = 0:10;
scatter(x,y);
```

### Histogram

```
a = randn(1000,1);
hist(a)
```

Note the difference with the number of bis set to 50

```
a = randn(1000,1);
hist(a,50)
```

### Contour plot

```
x = [1 2 3 2 1];
y = x;
z = x' * y;
axis([1 5 1 5]);
contour(z);
```

### Polar plot

```
x = 0:0.1:2*pi
size(x)
y = linspace(0.1, 0.1, 63)
polar(x,y)
```

### Pie chart

```
a = 1:6;
pie(a);
```

Note the difference

```
a = 1:6;
e = [1 0 1 0 1 0];
pie(a,e);
```

### 3d plot

```
x = -10:10
y = -10:10
[x,y] = meshgrid(x,y)
z = x .^2 + y .^2
mesh(x,y,z)
meshc(x,y,z)
meshz(x,y,z)
surf(x,y,z)
%
% saving
%
print -dpng ‘mymesh.png’
```



# Getting the path right

1. Run `addpath ("~/Octave")` to add an Octave folder for functions

2. Save the path with `savepath ()`. This will write to `~/.octaverc`.


# Install packages from Octave Forge

```
pkg install -forge image
```

# Publish

Octave has a nice `publish` feature. To publish the `pub_example.m`
file, one would enter from the command line (in the correct directory...)

> publish("pub_example.m");

This creates a nice HTML file with a notebook-like format.

# PDF output from jupyter notebook w/ Octave kernel

This does not work automatically. I found a workaround
[here](https://nbconvert.readthedocs.io/en/latest).

0. Install what we need from python

    See the
    [installation section](https://nbconvert.readthedocs.io/en/latest/install.html).

    ```
    conda install nbconvert
    conda install pandoc
    ```

1. use as a command line tool

    See the
    [useage section](https://nbconvert.readthedocs.io/en/latest/usage.html).

    ```
    jupyter nbconvert --to latex notebook.ipynb
    ```

2. Use LaTeX to render the notebook. `TeXworks` worked fine...

   In general, I am pleased with the rendering...
   
   There are items to add to the .tex file
   
       Under `\title{}` (perhaps change):
       \title{Octave \textit{Vade Mecum}}
       \author{Mike James (Modified by J. R. Minter)}
       \date{2019-03-25}

# Using Octave with Rmarkdown




# Min and Max value for a matrix

This is n annoyance... Adapted from
[here](https://gist.github.com/Atlas7/6e03676da65bf467cb22d1ca42f20695).

1. Octave matrix index start with `1` not `0`.

2. To find the minimum value of the matrix and its index, one can use
   this function of the matrix `A`:
  
   ```
   A=[1,2,3;4,5,6]
   [minval, row] = min(min(A,[],2));
   [minval, col] = min(min(A,[],1));
   [minval, row, col]
   ```
   
   and for the maximum value:
   
   ```
   A=[1,2,3;4,5,6]
   [maxval, row] = max(max(A,[],2));
   [maxval, col] = max(max(A,[],1));
   [maxval, row, col]
   ```

   I coded these into functions: `max_val_pos` and `min_val_pos`. 
   
   **Note:** These are maintained under version control (`git`) in the
   `global` respository in the `octave/functions` folder.

# Functions

I struggled until I discovered one can have **only one function per .m file**...

1. Run `addpath("~/Octave")` and put functions there...
2. savepath () to save to above
3. Functions must be in **individual** files with extension `.m`
4. Test the path with `path()`


# FFTs

There is a video tutorial by Ashwith Rego (2012-11-28) on
[YouTube](https://www.youtube.com/watch?v=XofmaKJ8RnA).

There is a decent tutorial
[here](https://matlabgeeks.com/tips-tutorials/how-to-do-a-2-d-fourier-transform-in-matlab/).

# Using Octave in Jupyter Notebook.

This is **awesome**!

See: [Calysto's](https://github.com/Calysto/octave_kernel) Readme.rst file
for installation instructions.

- To install via conda:

   ```
   conda config --add channels conda-forge
   conda install octave_kernel
   conda install texinfo # For the inline documentation (shift-tab) to appear.
   ```

- Configure for MacOS

   1. `.octaverc` contents
   
   ```
   addpath ('/Users/jrminter/octave', '-begin');
   setenv("GNUTERM","qt");
   ```
   
   2. Add to `.bash_profile`
   
   ```
   OCTAVE_EXECUTABLE="/Applications/Octave-5.1.0.app/Contents/Resources/usr/Cellar/octave-octave-app@5.1.0/5.1.0/bin/octave-5.1.0"
   export OCTAVE_EXECUTABLE
   ```
   




[Back to Index](../README.html)