run("Close All");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step01.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step02.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step03.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step04.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step05.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step06.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step07.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step08.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step09.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step10.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step11.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step12.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step13.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step14.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step15.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step16.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step17.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step18.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step19.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step20.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step20.tif");
open("/Users/jrminter/dat/images/key-test/efi-test/50X-1/Step21.tif");
run("Images to Stack", "name=Stack title=[] use");
selectWindow("Stack");
run("Extended Depth of Field (Easy mode)...");
selectWindow("Stack");

selectWindow("Output");
saveAs("Tiff", "/Users/jrminter/dat/images/key-test/efi-test/50X-1/EDF.tif");
