---
title: "John Minter's Image-J Tips"
author: "J. R. Minter"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: united
    highlight: pygments
---

[Back to Index](../README.html)

## Annotating images
From [wiki.imagej.net](http://wiki.imagej.net/Annotating_Images#Issues_with_adding_text)

Images can be annotated using the annotation tool. Double-click to get a configuration image. Adding text to a stack is a slightly different process. You can draw a text box by following the same steps, but on a stack, keyboard shortcut ``Ctrl+B`` will overlay the text on the current slice, while shortcut ``Ctrl+D`` will draw the text on every slice of the stack.

The ``Cookbook > Annotating images > Add Scale bar`` choice from the menu opens a configurable dialog. One needs to set the scale from ``Analyze > Set Scale`` first.

## Sources of plugins

[Stowers Research Institute](http://research.stowers.org/imagejplugins/)

## Reproducible Jython Scripting

For a couple of years I have been trying to follow the ``DRY`` process (Don't Repeat Yourself) for more reproducible Jython scripting with DTSA. Recently I have been migrating my ImageJ scripts to Jython to use with Fiji. I just learned how import user functions...

1. Create a folder ``Lib`` in FIJI_ROOT/jars/
2. Create your user module. My first one is ``jmFijiGen.py`` and place it in your new ``Lib`` folder. One of the first functions is ``ensureDir``.
3. Use the following to use ``utf-8``.

```
from org.python.core import codecs
codecs.setDefaultEncoding('utf-8')
```
4. To use ``ensureDir`` in your Jython scripts, include

```
import jmFijiGen as jmg
jmg.ensureDir(imgDir)
```


## Alchemy...

### Inverting an image

I am always hunting for the invert command. it is **not** in the ``Process > Binary`` menu but rather in the ``Edit > Invert`` menu. The shortcut is ``Ctrl-Shift-I``

### Using a mu in a Jython script

The usual Windows key sequence for a $\mu$ is **not** a utf-8 character. Using this gives errors in Jython scripts. Here is how to define a $\mu$
as a utf-8 character:

```
a = [0xCE, 0xBC]
mu = "".join([chr(c) for c in a]).decode('UTF-8')
units  = mu+"m"
```
### Getting dir() to work with Jython in Fiji

One needs to start Fiji with a command switch. On MacOSX, this works:

```
/Applications/Fiji.app/Contents/MacOS/ImageJ-macosx -Dpython.cachedir.skip=false --
```

On Win7, this works from the ``fiji.cmd`` in ``C:\Apps\local``:

```
"C:\Apps\Fiji.app.win64\ImageJ-win64.exe" -Dpython.cachedir.skip=false --
```

And this works starting it with Java8 from the ``fiji8.cmd`` in ``C:\Apps\local``:

```
"C:\Apps\Fiji.app.win64\ImageJ-win64.exe" -Dpython.cachedir.skip=false --java-home "C:\Program Files\Java\jdk1.8.0_20"
```

Note that these command arguments may also be put in the shortcuts that start Fiji. I did this on ``ROCPW6C6XDN1``


### How do I launch ImageJ with a different version of Java?

[FAQ](http://fiji.sc/Frequently_Asked_Questions#How_do_I_launch_ImageJ_with_a_different_version_of_Java.3F)

Use the --java-home command line option. Examples:

On OS X:
```
/Applications/Fiji.app/Contents/MacOS/ImageJ-macosx --java-home \
  '/Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home'
```

## Edge-preserving averaging (smoothing) algorithms

### Thresholded Blur

[ImageJ Wiki](http://imagejdocu.tudor.lu/doku.php?id=plugin:filter:thresholded_blur:start)

## Plug-ins that don't return an image reference

Wayne Rasband noted (2013-05-22) that some reader plugins,
including Bio-Formats, open and display the image without
returning a reference. He offered the following
work-around in jython scripts:

```
imp = IJ.openImage(path)
imp = WindowManager.getCurrentImage()

```

## Using overlays on image channels

Wayne Rasband provided (2013-05-24) this useful snippet

```
imp.setMode(CompositeImage.GRAYSCALE);
overlay = new Overlay();
// add rectangle that will be displayed on channel 1 of all 10 frames
rect1 = new Roi(100, 100, 100, 100);
rect1.setPosition(1, 1, 0);
overlay.add(rect1);

```

[Back to Index](../README.html)
