---
title: "Git Tips"
author: "J. R. Minter"
date: "Started: 2013-07-16, Last modified: 2019-03-07"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

[Back to Index](../README.html)

These are John Minter's tips for a workflow using git. They were
compiled from several web sources.

# Quick tips

## Rendering Rmarkdown on Github

Yihui Xie made a convincing argument for not rendering .Rmd files on github
as plain markdown. He explains the reasoning
[here](http://yihui.name/en/2018/10/rmd-github/). 

He recommends installing the
[Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha)
add in. He also recommends adding the code below to the global stylesheet
to wrap Rmd code

```
.type-rmarkdown .blob-code-inner {
  white-space: pre-wrap;
}
```

Current version

1. Click on "css" button on upper right
2. Select `Styles` from left menu.
3. Select `Edit Global Stylesheet`
4. Paste the code from above.
5. Press `Save`
6. Close the window.
7. Reload your github page with .Rmd file to check



## Branches

1. Create a new branch on local repository

```
git checkout -b table-names
```

Edit files and commit your changes. You can checkout the master again
with 

```
git checkout master
```

later you can

```
git checkout table-names
```

2. Push/pull to the origin (github)

```
git push origin table-names
```

or

```
git pull origin table-names
```

## Using git credentials

1. From [stackoverflow](https://stackoverflow.com/questions/1595848/configuring-git-over-ssh-to-login-once).

    For the `tip` project:

    ```
    git config -l
    git config remote.origin.url git@github.com:jrminter/tips.git
    ```

2. Jenny Bryan's credential helper tips from
[happygitwithr.com](https://happygitwithr.com/credential-caching.html).

    **Windows:**

    Plan A: 
    
    ```
    git config --global credential.helper manager
    ```
    
    Plan B (deprecated):
    
    ```
    git config --global credential.helper wincred
    ```
    
    **Mac:**

    Find out if the credential helper is already installed. In the shell, enter:
    
    ```
    git credential-osxkeychain
    ```
    
    and look for this output:
    
    ```
    usage: git credential-osxkeychain <get|store|erase>
    ```
    
    If you don’t get this output, it means you need a more recent version
    of Git, either via command line developer tools or Homebrew.
    
    Once you’ve confirmed you have the credential helper, enter:
    
    ```
    git config --global credential.helper osxkeychain
    ```
    
    **Linux:**

    In the shell, enter:
    
    ```
    git config --global credential.helper 'cache --timeout=10000000'
    ```
    
    to store your password for ten million seconds or around 16 weeks, enough
    for a semester...




## Useful videos

See youtube [Git Foundation Playlist](https://www.youtube.com/playlist?list=PLg7s6cbtAD15G8lNyoaYDuKZSKyJrgwB-)

# Recent changes

Note some really helpful aliases [here](https://hackernoon.com/lesser-known-git-commands-151a1918a60).

Now use

```
git add --all :/
```

## Get the git history for a file

```
git log -- git/git-tips.Rmd
```


## Connect a local repository to github

from [Karl Broman](http://kbroman.org/github_tutorial/pages/init.html)

1. Prepare the local repository as usual. It helps to have the folder be the desired repository name on github.
2. Go to [github](https://github.com/).
3. Log into your account as usual
4. Click the [new](https://github.com/new) button in the top-right. You’ll have an option there to initialize the repository with a README file, but it is better not to add it.
5. Click the ``Create repository`` button.
6. Go to the local repository and type at the command prompt (`$`):

```
git remote add origin https://github.com/username/new_repo_name
git push -u origin master
```

To add from all directories.


# Initial configuration

Here are some useful initial variables to set up for git

```
git config --global user.name "John Minter"

git config --global user.email "jrminter@gmail.com"
git config --global user.email "john.r.minter@kodak.com"

# saves multiplatform headaches caused by line endings...
# Configure Git on OS X to properly handle line endings
git config --global core.autocrlf input 

git config --global color.ui true
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.lol "log --oneline --graph --all --decorate"
```

## See what git ignores

```
git ls-files --others --ignored --exclude-standard
```

## Note this procedure after changing line endings in a repository

1. Save your current files in Git, so that none of your work is lost.

```
git add . -u
git commit -m "Saving files before refreshing line endings"
```
2. Remove every file from Git's index.

```
git rm --cached -r .
```

3. Rewrite the Git index to pick up all the new line endings.

```
git reset --hard
```

4. Add all your changed files back, and prepare them for a commit. This is your chance to inspect which files, if any, were unchanged.

```
git add .
```
It is perfectly safe to see a lot of messages here that read warning: CRLF will be replaced by LF in file."

5. Commit the changes to your repository.

```
git commit -m "Normalize all the line endings"
```

# Some helps on commit messages

[Chris Beams](http://chris.beams.io/posts/git-commit/#seven-rules)

[Brigade Engineering](https://medium.com/brigade-engineering/the-secrets-to-great-commit-messages-106fc0a92a25)

# see what changed

My new favorite command...

```
git whatchanged
```

# Syncing a fork

From [GitHub Help](https://help.github.com/articles/syncing-a-fork/)

1. `git fetch upstream`
2. `git checkout master`
3. `git merge upstream/master`
4. `git push`
5. `git pull`

# Branches

Work should be done on a branch to keep `master` clean. Think of
`master` as a production environment. 

## Merge a branch with master

```
git checkout master
get merge my-branch
```

May need to resolve merge history

```
<<<<<< Head
some code
=======
diff code
>>>>>>> my-branch
```
fix and
```
git add the-file
```
repeat for other files, then
```
git commit -a -m'fixed conflicts'
```

If you don't have time to fix conflict

```
git merge --abort
```

will clean up

A cleaner merge:

```
git merge --squash target-branch
```
merges all changes and generates a single new staged commit for
you to commit with a single message.

## Delete a branch

1. A fully-merged branch

```
git checkout master
git branch -d my-merged branch
```

2. A non-fully merged branch

```
git checkout master
git branch -D my-merged branch
```

## Check out and track a remote branch

From [stackoverflow](http://stackoverflow.com/questions/379081/track-all-remote-git-branches-as-local-branches/6300386#6300386) answer to initial question

```
git checkout --track origin/branchname
```

## get rid of obsolete, merged branches

```
git branch --merged | xargs git branch -d
```

## To remove a remote branch (if you know what you are doing!)

```
git push origin :the_remote_branch
```

## see commits with abbreviated sha

Hadley Wickham noted:

> With git, each change (commit) is given a unique identifier, called a sha. The sha is a key into a database that provides the author, date, and a description.

Here is how we can see them...

```
git log --oneline --decorate --tags
```

## local cherry picking
```
git checkout <OTHER_BRANCH> -- path/to/file
```

## Syncing a fork

Here is github's official document on [Syncing a fork][1]:

### The Setup

> Before you can sync, you need to add a remote that points to the upstream repository. You may have done this when you originally forked.

> *Tip: Syncing your fork only updates your local copy of the repository; it does not update your repository on GitHub.*

>     $ git remote -v
    # List the current remotes
    origin  https://github.com/user/repository.git (fetch)
    origin  https://github.com/user/repository.git (push)
    
>     $ git remote add upstream https://github.com/otheruser/repository.git
    # Set a new remote
    
>     $ git remote -v
    # Verify new remote
    origin    https://github.com/user/repository.git (fetch)
    origin    https://github.com/user/repository.git (push)
    upstream  https://github.com/otheruser/repository.git (fetch)
    upstream  https://github.com/otheruser/repository.git (push)

### Syncing

> There are two steps required to sync your repository with the upstream: first you must fetch from the remote, then you must merge the desired branch into your local branch.

## Fetching

> Fetching from the remote repository will bring in its branches and their respective commits. These are stored in your local repository under special branches.

>     $ git fetch upstream
    # Grab the upstream remote's branches
    remote: Counting objects: 75, done.
    remote: Compressing objects: 100% (53/53), done.
    remote: Total 62 (delta 27), reused 44 (delta 9)
    Unpacking objects: 100% (62/62), done.
    From https://github.com/otheruser/repository
     * [new branch]      master     -> upstream/master

> We now have the upstream's master branch stored in a local branch, upstream/master

>     $ git branch -va
    # List all local and remote-tracking branches
    * master                  a422352 My local commit
      remotes/origin/HEAD     -> origin/master
      remotes/origin/master   a422352 My local commit
      remotes/upstream/master 5fdff0f Some upstream commit

## Merging

> Now that we have fetched the upstream repository, we want to merge its changes into our local branch. This will bring that branch into sync with the upstream, without losing our local changes.

>     $ git checkout master
    # Check out our local master branch
    Switched to branch 'master'
    
>     $ git merge upstream/master
    # Merge upstream's master into our own
    Updating a422352..5fdff0f
    Fast-forward
     README                    |    9 -------
     README.md                 |    7 ++++++
     2 files changed, 7 insertions(+), 9 deletions(-)
     delete mode 100644 README
     create mode 100644 README.md

> If your local branch didn't have any unique commits, git will instead perform a "fast-forward":

>     $ git merge upstream/master
    Updating 34e91da..16c56ad
    Fast-forward
     README.md                 |    5 +++--
     1 file changed, 3 insertions(+), 2 deletions(-)

> *Tip: If you want to update your repository on GitHub, follow the instructions [here][2]*


  [1]: https://help.github.com/articles/syncing-a-fork
  [2]: https://help.github.com/articles/pushing-to-a-remote#pushing-a-branch


## Getting a pending Fork

From [stackoverflow](http://stackoverflow.com/questions/6022302/pull-requests-from-other-forks-into-my-fork/28729484#28729484) answer 3.

### **Update: Via Webpage**

> Nowadays (since?), you can do this via the github webpage.

> I assume, you should have already a fork (`MyFork`) of the common repo (`BaseRepo`) which has the pending pull request from a fork (`OtherFork`) you are interested in.

> 1. Navigate to the fork (`OtherFork`) which has initiated the pull request which you like to get into your fork (`MyFork`)
2. Go to the pull requests page of `OtherFork`
3. Click new pull request
4. The pending pull request(s) should be offered. Select on the left side as the base fork your fork (MyFork) (**IMPORTANT**)
5. Now the option of `View pull request` should change to `Create pull request`. Click this.

> Now you should have a pending pull request in your fork (`MyFork`), which you can simply accept.

## more nice tip resources

[git tips from the trenches](https://ochronus.com/git-tips-from-the-trenches/)

## git config file

From [Getting Started](http://git-scm.com/book/en/Getting-Started-First-Time-Git-Setup)

On Windows systems, Git looks for the ``.gitconfig`` file in the ``$HOME`` directory (``%USERPROFILE%`` in the Windows environment), which is usually  ``C:\Documents and Settings\$USER`` or ``C:\Users\$USER`` for most people, depending on version (``$USER`` is ``%USERNAME%`` in the Windows environment). It also still looks for ``/etc/gitconfig``, although it’s relative to the MSys root, which is wherever you decide to install Git on your Windows system when you run the installer.


# removing unwanted cached files

From[Source.kohlerville.com](http://source.kohlerville.com/2009/02/untrack-files-in-git/)

Today I learned how to untrack files that have already been added
to a git repository. The following command will stop tracking but
keep the file there intact. This is good for directories that have
auto generated files every so often so everytime you do a git commit,
you don’t have to commit a new copy of these files.

```
git rm --cached filename

```

For example,


```
git rm --cached man/*.Rd

```

# Git extensions for VS
[source forge](http://sourceforge.net/projects/gitextensions/)

## Oops control - recovering a deleted file.

Put this first because when I'm in a panic after an accidental
deletion, I'm in no mood to search.

From [John Bohn](http://jjbohn.info/blog/2013/10/03/find-deleted-files-in-git/)

So, if I have a file that I deleted a month or so ago called ``foo.rb`` 
but for some reason I need to bring it back into my local repo.
I can easily bring it back by running the following:

```
git checkout `git rev-list -n 1 HEAD -- foo.rb`^ foo.rb
```

So, that's obviously a bit of a long-winded shortcut. Let's break it down.

It's really two commands in one. Let’s start with inside the ticks.

```
git rev-list -n 1 HEAD -- foo.rb
```
The ``-n`` 1 says "give me one revision". ``HEAD`` represents the tip of
the current branch. The bare double dashes (or ``--`` ) represents my current
branch. When all put together we are saying, print the latest commit hash
starting from the commit I am currently on, in the branch that I am currently
on, that modified ``foo.rb``. The caret (``^``) is a shortcut that represents
the previous commit to whatever it appends.

Once you grok that, the next part is pretty easy. Once interperted by the
shell, the command is just a normal checkout from an alternate commit.

## getting github not to ask for a password on windows
[stackexchange](http://stackoverflow.com/questions/3625148/how-do-i-store-a-password-for-my-key-so-i-can-commit-and-pull-from-repository-wh)
pointed me to a solution on
[github](https://help.github.com/articles/working-with-ssh-key-passphrases#platform-windows)
that **finally** worked for pulls. On win7, I still got
userid requests. This article on
[stackexchange](http://stackoverflow.com/questions/8588768/git-push-username-password-how-to-avoid)
pointed to a solution that worked for pushes:
edit the url to
```
git remote set-url origin https://user:pw@github.com/jrminter/repo.git
```
another post suggested using ``git@github.com:org/repo.git``.
This did not work for me.



# A better log
From
[coderwall](https://coderwall.com/p/euwpig)

So, are you tired of the old and boring git log
screen? Just type in:

```
git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
```

I guess that's a bit too long, eh? Let's just make an alias. Copy and paste the line below on your terminal:

```
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
```

And every time you need to see your log, just type in

```
git lg
```

Or, if you want to see the lines that changed

```
git lg -p
```


# Twelve common "verbs" for 99% of the workflow

Scott Chacon notes that 99% of one's daily work can be done
using twelve common commands

## Init

```
git init
```
This initializes the repository and creates default branch "master"

## Clone

```
git clone url
```

This clones a given URL

## Add

```
git add some-file # adds an individual file to to my staging area
git add .         # adds all...
```

## Status

```
git status # what is staged/unstaged
```

## Commit

```
git commit -a -m'Useful message'
```

This commits whatever you are working on and moves HEAD ptr
forward. Commits Should be "logical units"

## Branch

Branches are pointers into the graph -- a reference.
Easy to write... writes 42 bytes to a file
HEAD is a symbolic branch - a pointer to the current
branch you're working on and represents the
last known status of your working directory.

```
git branch          # lists branches
git branch foo      # creates branch "foo" to last commit. Do this FREQUENTLY
git checkout foo    # switches to branch "foo" and has HEAD point there
git branch -d foo   # delete branch foo (-d is safe, -D removes pointer, will never be pushed)
git checkout branch # copies the branch into your working directory
git checkout -b iss53 master # create branch & co branch iss53 and sets the master (default) ptr there

```

## Merging

```
git checkout target
git merge    source
```

When you resolve conflicts, use git add, git commit, and 
git mergetool

## Push and Pull

All been local up to now.
Remotes: url to other nodes of this project
If you did git clone you will have an ORIGIN

Push to master

```
git commit
git fetch # (pull?)
git merge origin/master
git push  # (to server)
```

The problem of "Your branch is ahead of 'origin/master' by n commits."

```
$ git status
# On branch master
# Your branch is ahead of 'origin/master' by 1 commit.
#
nothing to commit (working directory clean)
$ git push origin master
Everything up-to-date
```

May have to be sure that master isn't checked out on origin...

### Push other branch

```
git checkout -b iss53 31b8; git commit; git commit
git push origin iss53 # has a branch on server that points where mine is
```

```
git fetch # (will get)
get co iss53
git commit
git push origin iss53
```

Scott Chacon likes get fetch/merge/push for most people as
opposed to pull/merge/push

```
git pull #  a wrapper script tries fetch/merge can blow up with multiple branches
git push # a wrapper script to push to server
```

## Logs

```
git log #  walk your commit history from HEAD down
```

### Log Subsets

```
git log branchA ^ branchB #  show commits reachable by branchA not reachable by branchB. see what has NOT been merged in. Quite useful...

git fetch
git log origin/master ^master	# shows what is on the server master branch not in my local branch equivalent to git incoming

git fetch
git log master ^origin/master # what is unique that I would be push

git log -p patch
git log -stat
```

## Tags

```
list tags
git tag
add a tag
git tag -a v1.2.500 -m 'version 1.2.500'
remove a tag
git tag -d v1.4.400 
rename a  tag 
git tag v1.4.400 v1.2.400
tag -d v1.4.400 

```


# Changing the origin for a repository

[Stack Overflow](http://stackoverflow.com/questions/2432764/how-to-change-a-remote-repository-uri-using-git)
had a useful tip to change the repository from the command
line:

```
git remote set-url origin git://new.url.here
```

One can just edit .git/config and change the URLs there. You're not
in any danger of losing history unless you do something very silly
(and if you're worried, just make a copy of your repo, since your
repo is your history.

Note that the appropriate section from a .git/config file for a
github repository looks like

```
[remote "origin"]
  url = https://github.com/jtleek/dataanalysis.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

Note that the appropriate section from a .git/config file for a
repository on a network share looks like

```
[remote "origin"]
  url = c:/usr/jrminter/doc/work/proj/QM13-06-01A-Sowinski
	fetch = +refs/heads/*:refs/remotes/origin/*
```

[Back to Index](../README.html)