---
title: "R-Markdown Tips"
author: "J. R. Minter"
date: "Started: 2016-12-08, Last modified: 2018-08-23"
output:
  knitr:::html_vignette:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
---

[Back to Index](../README.html)

# Overview

**R-markdown** is a powerful light-weight formatting language that enables the
author to generate attractive documents that are stored in plain text files
that are compatible with version control. This works very well in the
**RStudio** environment.

Some key resources are the
[RStudio Intro to rmarkdown](http://rmarkdown.rstudio.com/lesson-1.html), 
the RStudio Intro to Pandoc
[markdown](http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html),
and for $\LaTeX$ math, the
[AOPS](http://artofproblemsolving.com/wiki/index.php/LaTeX:Commands) site.

## Some template examples

- The [sorensonimpact](https://github.com/Sorenson-Impact/sorensonimpact)
package. This inspired my
[minterbrand](https://github.com/jrminter/minterbrand) package.

- A nice html template in the [epuRate](https://github.com/holtzy/epuRate) package by Holtz Yan.

## Using the `out.extra` argument to apply styles to a single chunk.

From [zevross.com](http://www.zevross.com/blog/2017/06/19/tips-and-tricks-for-working-with-images-and-figures-in-r-markdown-documents/#bonus-knitr-and-r-markdown-functionality)

The code below uses this argument:

```
out.extra='style="background-color: #9ecff7; padding:10px; display: inline-block;"'
```

```{r useOutExtra, out.width="50%", out.extra='style="background-color: #9ecff7; padding:10px; display: inline-block;"'}
plot(10:1, pch=21, bg="red")
```

# Use default css and custom css file in html_vignette()

There was an interesting discussion on how to include both the default css file and a custom css file in a `html_vignette` document in the **rmarkdown** [issues](https://github.com/rstudio/rmarkdown/issues/732) on `github`. J. J. Allaire offered some great options below.

A few options here:

1. Use `!expr` to execute R code to determine the path of the default CSS, e.g.

<tt>
```
css:
  - !expr system.file("rmarkdown/templates/html_vignette/resources/vignette.css", package = "rmarkdown")
  - styles.css

```
</tt>

Create an inline CSS chunk at the end of your document with your custom styles, e.g.

<tt>

```{css}
p {
color: gray;
}
```
</tt>

Use the include `-> in_header` option to include an HTML file that contains a style element with the styles you want.



# My typical YAML for an HTML document

**YAML** is an abbreviation for "Yet Another Markup Language". 
R-markdown uses YAML to encode information for later steps in the document
generation process. Each document begins with a YAML header. 
This is an example of a YAML header for an analysis. Note how the \% 
character is escaped. Also note the $\LaTeX$ expression.

```
---
title: "SEM/EDS analysis of qm-05000-SampleID"
author: "J. R. Minter"
date: "Started: 2016-12-07, Last Modified: 2018-07-04"
abstract: |
  The particles were deposited on a Si chip and lightly C coated. The 
  morphology appeared to be a mixture of small needles and small equiaxial
  nanoparticles. Clumps seemed to be particles embedded in a film.
  
  Analysis of EDS spectra revealed an atomic fraction of $\dfrac{Al}{Al+Zn}$
  of 3-4\%.
output:
  knitr:::html_vignette:
    css: ../theme/jm-mod-vignette.css
    number_sections: yes
    toc: yes
    bibliography: bibliography.bib
---

```

Note that one can generate the date and time at document generation time by
using an R chunk in the YAML header.

by putting the R expression:

    r format(Sys.time(), '%Y-%m-%d')
    
in the blank area below (I had to enter this way or it would compile...)

    date: "`    `"

to create the YAML entry...

# YAML for a PDF document.

PDF documents can have some **really complicated** YAML.
I spent a couple of hours getting this example to work well.
I don't want **future me** to have to repeat the process...

```
---
title: "My title"
author: "John Minter"
date: "Started: 2018-07-10, Last modified: 2018-07-11"
geometry: "left=0.5in,right=0.5in,top=0.5in,bottom=0.5in"
output:
  pdf_document:
    # fig_caption: yes
    number_sections: yes
    latex_engine: xelatex
    fig_width: 5
    fig_height: 5
bibliography: inc/viridis.bib
csl: inc/acs.csl
fontsize: 12pt
header-includes:
  - \usepackage{fontspec}
  - \usepackage{chngcntr}
  - \setmainfont[BoldItalicFont={Times New Roman Bold Italic}]{DejaVu Sans}
  - \counterwithin{figure}{section}
  - \counterwithin{table}{section}
---
```
followed by this chunk. **Note:** I moved the chunk name int the block
so it will not execute here...

```
{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
  comment = NA,
  fig.align = "center",
#  fig.height = 6,
#  fig.width = 7,
  message = FALSE,
  warning = FALSE,
  error = FALSE)
```

## Simple Word to markdown

From [rud.is](https://rud.is/b/2017/04/30/r%E2%81%B6-using-pandoc-from-r-a-neat-package-for-reading-subtitles/)

```
rmarkdown::pandoc_convert("simple.docx", "markdown", output="simple.md")

```

# Using python chunks and conda environments

1. We can pass a specific python conda environment by using
the knitr **engine.path** argument.

For example, to use the conda environment **r-tensorflow**,
we would use the following argument for **knitr**:

```
engine.path="C:/Apps/miniconda/envs/r-tensorflow/python"
```

2. Get rid of comment characters during printing

We would use the following argument for **knitr**:

```
comment=NA
```

3. Suppress annoying messages from **tensorflow**: Set the
following **environment variable**

```
TF_CPP_MIN_LOG_LEVEL=2
```

# Splitting an ordered list

Works with a single page/slide or across slides

```
## Slide

<ol>
<li> Sed ut perspiciatis unde omnis iste natus error...
<li> Nemo enim ipsam voluptatem quia voluptas sit...
</ol>

This is an interrupting block of text...

<ol start=3>
<li> Neque porro quisquam est, qui dolorem ipsum quia..
<li> Quis autem vel eum iure reprehenderit qui in ea voluptate...
</ol>

```

# Key HTML and Unicode characters


```
mu  &#x393; or &mu; Can use &Mu; for capital. 
    Unicode is \U00B5 (micro) and \U039c (upper) \U03BC (lower)
    
phi &Phi; or &phi; or \U03D5 (lower) \U03A6 (upper)

rho &Rho; or &rho; or \U03C1 (lower) \U03A1 (upper)

A-ring: &#8491;  or \U212B

degree &#176; or \U00B0

superscript 2  <sup>2</sup>  \U0032
subscript 2    <sub>2</sub>  \U2082
superscript 3  <sup>3</sup>  \U0033

```

# Custom themes

The easiest way to make a custom theme is to modify an existing one.
I modified the R vignette theme.

# Controlling image size

We can get fine control of image size like this:

1. Start by adding these packages to the first R chunk

```
library(png)
library(grid)
library(rEDS)
```

2. Include an image in a R chunk like this:

```
img <- readPNG("../path-to/foo.png")
grid.raster(img)
```

3. The header for the R-chunk might include. **Note**: Use **unique**
chunk names

```
r includeImg1, fig.width=7.5, fig.height=5.625, echo=FALSE, fig.align='center',
fig.cap='ImgName. 7 kV 1,000X'
```

4. I compute the fig.height from the desired width (7.5 in) and the image
   dimensions using R. For a 1024/768 image, one gets:
   
```
> 7.5*768/1024
[1] 5.625
```

# Citations

See [Citations](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

At end of document add

```
last paragraph...

# References
```

Then a citation like:

```
Blah blah [see @doe99, pp. 33-35; also @smith04, ch. 1].

Blah blah [@doe99, pp. 33-35, 38-39 and *passim*].

Blah blah [@smith04; @doe99].
```

A minus sign (-) before the @ will suppress mention of the author in the citation. This can be useful when the author is already mentioned in the text:

```
Smith says blah [-@smith04].
```

You can also write an in-text citation, as follows:

```
@smith04 says blah.

@smith04 [p. 33] says blah.
```



[Back to Index](../README.html)