---
title: "Low Carb Diet"
author: "Karl Denninger"
date: "Original: 2016-04-25, Modified to Rmarkdown: 2020-02-25"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---
[Back to Index](../README.html)

Archived from [here](https://market-ticker.org/akcs-www?post=231343).

The medical industry doesn't want you to read this.

Nor does the food industry.

But you should read it, and let it sink in.

There is a lot of BeeEss flying around about low-carb eating.  Here are some common myths and truths related to this lifestyle.

**Myth:** It's a "fad diet."  Eating low-carb is a lifestyle, not a diet and it is not a fad.  In fact humans, prior to the discovery of high-density agriculture, almost-exclusively ate in this fashion.  A "fad" is an unproved and new way of doing something without examination as to validity.  It is in fact the modern mania with vegetable oils, nearly none of which exist in nature, along with other highly processed foods such as cereals and sugar-laden things, driven by literal billions of advertising dollars, that is the fad.  Nobody spends a billion dollars advertising broccoli crowns on TeeVee!

**Myth:** Low-carb eating means not eating vegetables and fruits.  Nonsense.  For nearly everyone who decides to eat low-carb their consumption of vegetables greatly increases, especially when it comes to green vegetables.  There is no restriction whatsoever in the consumption of things such as spinach, broccoli, brussels sprouts, cucumbers and its soaked-in-vinegar friend the dill pickle, various forms of peppers and similar.  Small, nutrient-dense fruits and berries, along with nuts, are also compatible in amounts comparable to that which would be found "in season" naturally.

**Myth:** Low-carb eating means not getting enough fiber.  Oh really?  All those vegetables are an insufficient source of fiber?  Like hell; what's missing is the artificially-added back fiber that people love to crow about in things like bread, which wasn't there in the first place due to all the processing.  I suppose if you want to eat what amounts to cardboard (cellulose) that has been put back into a processed food so it can claim to be "high fiber" then yes, it means "not getting enough" but the last time I checked cardboard wasn't a naturally-occurring thing nor would you find it tasty -- unless it was slathered with sugar.  Guess what gets added to these "foods" to make all that added-back fiber palatable?  Yep.

**Myth:** Low-carb eating means not having enough energy since you don't have carbohydrates.  Fact: Your body, even if you're very slender with zero perceptible fat on you, has enough fat in storage to run ten marathons without eating, yet you can't even run one with a maximum load of stored carbohydrate.  Your stores of glycogen, which is what carbohydrate is metabolized into in the body, are limited to about 2,000 calories at most.  Even the leanest person has five to ten pounds of fat stored on them (and most have a lot more) with each pound being 3,500 calories.  You do the math.

**Myth:** You need carbohydrates.  Fact: There are no essential carbohydrates.  There are essential fatty acids and protein complexes, along with ascorbate (vitamin C) that your body cannot synthesize, but no such thing exists for carbohydrates.  The exact amount of carbohydrate your body requires is zero.

**Myth:** You can't perform athletically without carbohydrates.  Fact: Athletic performance, especially for endurance events such as running at double-digit mileages, is not only possible without carbohydrates it in many ways can be superior.  During heavy exertion the digestive system is effectively shut down because the body shunts its energy resources to the skeletal muscles to drive that performance.  Since carbohydrate stores are limited to about 2,000 calories and a mile of running requires somewhere between 100 - 120 calories to sustain plus your base energy requirement (another 150 calories/hour or so) during longer endurance events you're constantly "dancing with the devil" in attempting to consume carbohydrates and digest them while your digestive system is barely functional.  If you lose this dance you either vomit or have an immediate need to relieve yourself out the other end -- and both of those events come with dehydration, which is very dangerous when exerting yourself heavily.  By contrast when running on lipids (fats) even the leanest athlete has more than enough fat in their body to run several ultra marathons back-to-back and thus need consume nothing in the way of food, requiring only hydration and electrolytes that can be immediately absorbed by the intestines.  Further, studies have shown that those who are low-carb adapted burn much more fat during exercise than those who run into glycogen-deficit due to lack of carbs during a workout.  In other words if part of your fitness goals include losing or maintaining body mass then being keto-adapted, that is, eating low-carb, will make your exercise far more productive in terms of losing weight -- 2.3x as much, to be precise.

**Myth:** There's nothing to eat, it gets boring fast, and nutrient quality is poor.  Fact: See the below list; virtually everything available to eat before the introduction of cheap international transport and "factory" foods is compatible with low-carb eating.  Any form of animal flesh, eggs, cheeses, most vegetables and modest amounts of fruit and nuts are what make up a low-carb dietary intake.  In addition virtually all spices are zero-carbohydrate and can be used without concern as to quantity.  When you eat a lot of carbohydrate you're targeting caloric intake since high-carbohydrate foods have very low nutrient levels.  The poster child for this is of course sugar, which other than carbohydrate has essentially zero nutrients, but it doesn't end there.  Most high-carb starchy foods have very low vitamin and other nutrient loads compared against foods such as broccoli, kale and similar.  Broccoli, for example, has your entire Vitamin C and K requirements in one serving along with a very high nutrient and protein balance score yet nets only 31 calories per serving and 6 grams of carbs, 2 of which are indigestible (fiber.)  Rice, on the other hand, has a very low nutrient balance score, a decent protein balance, 205 calories/serving (6.6x as much!) and 45g of carbs yet only one gram of fiber (1/4 as much.)  It also fails to provide any material amount of your vitamin requirements; the only related item that measures reasonably-well is folate.  On the other hand when you eat low-carb your nutrient levels are naturally very high since those non-animal-source foods compatible with low-carb eating are sparse in calories.  In short, assuming you consume the same caloric intake, what you "crowd out" when eating high-carb is nutrition while what you "crowd out" when eating low-carb is junk.

**Myth:** Low-carb means eating a very high amount of protein.  Fact: Low-carb eating contains moderate protein levels.  Very high amounts of protein in fact are not "low-carb" since protein, when taken in beyond metabolic needs, is converted to glucose in the body.  That would be the opposite of what you're intending.  Don't trim the fat off your steak, consume it instead.

**Myth:** Your cholesterol balance will go to hell on a low-carb diet and you'll have a heart attack.  Fact: HDL typically goes up and LDL typically goes down, which is good, not bad.  However, there are several flies in the ointment of the common rubric regarding cholesterol, dietary fat and heart disease, not the least of which is that the correlation in several studies, including recent studies, has been backward. That is, increased carbohydrate and PUFA (polyunsaturated fatty acids -- read, vegetable oils) intake is associated with increased, not decreased, ischemic heart disease.  Want to have a heart attack?  Eat carbs and vegetable oils.  Seriously, I'm not kidding.

**Myth:** You won't stick with it even if you try it.  Fact: If you really do keto-adapt it is unlikely you'll ever return to eating high-carb foods en-masse.  Why?  Because you'll find them to be too sweet and no longer tasty.  Sugar and its analogues are quite-addictive, and like most addictive things their "dose response" goes down the more you use them.  That is, after a while a given amount of sugar doesn't taste "sweet" any more, so you add more to get the same "sweetness."  Stop consuming sugars for a few months and suddenly even a tiny amount tastes too sweet, and is no longer pleasant.  In addition once you become keto-adapted you are no longer a slave to food.  People are utterly shocked to find that I often wake up in the morning and have no desire to eat anything until somewhere around lunchtime!  They wake up famished every morning and immediately hit the pancakes, cereals and breads.  I did too, until I went keto-adapted and that all disappeared.  If you've ever been "hangry" it's because you're actually experiencing withdrawal from the addictive nature of fast carbohydrates.  If you enjoy being a slave then may the chains rest lightly on your back, but just remember that this form of slavery comes with greatly-increased risks of heart disease, obesity and diabetes.  Are you sure it's worth it?
Once again, for those who missed it the last time, here's the "don't eat" list:

Anything with added sugars on the label irrespective of amount.  If a word ending in "-ose" is on the label, it's a sugar.  Maltrose, dextrose, sucrose, fructose, etc.  All are sugars.  Go through your cupboard and throw all those packages and cans out, and don't buy any more of them.

Anything with man-made PUFAs in it.  There are two basic types of PUFAs -- Omega-3 and Omega-6.  Omega-3 is good for you in reasonable amounts and is almost-exclusively found in the flesh of animals, including most-especially fish.  Omega-6, on the other hand, is found naturally in most plant material.  The problem is that the amount found in plants you eat whole is tiny but when concentrated into man-extracted oils from vegetable sources you wind up consuming thousands of times more of it than you ever could by eating the actual plant.  Cottonseed oil, for example, is full of this stuff, yet you'd never sit down and eat a bowl of cotton seeds!  Likewise, you'd have to eat something like two bushels of corn in a single sitting to get the amount of PUFA found in one tablespoon of corn oil, but it is utterly trivial to consume that amount in baked goods.  This is true for all vegetable oils.  The only exception?  Small amounts of olive oil are reasonable used as a salad dressing.  But you should never, ever, cook with vegetable oils including sauteeing, frying, basting or similar because the fact that they're unsaturated means they oxidize rapidly and heat makes them oxidize more and faster.  The "switch" to vegetable-based oils in fryers has probably killed more Americans in the last 40 years than all other causes of death combined.  By the way, if you want the worst of the worst they come in the form of anything that has the word "hydrogenated" on the label.  Those are PUFAs that have been chemically stabilized so they are a solid and don't spoil while on the shelf in the store.   Let me be crystal-clear: The amount of PUFA you can safely ingest, and thus should ingest, is zero, with the exception of room-temperature olive oil used as a salad dressing or similar.  That section in your grocery store is IMHO "heart attack in a bottle."

"White", starchy vegetables and plants.  This means rice, potatoes and similar.  Rice and potatoes are peasant food.  If you'd otherwise die they're acceptable, I guess, but I'd hardly call them my first choice. Rice I've already covered but potatoes aren't far behind.  Their nutrient balance is severely skewed and, frankly, sucks.  With 63g of carbs and 278 calories in one large (300gm) potato, while they have a decent amount of fiber (7g) and a good protein balance the rest is lacking.  Of the vitamin complex only C and B6 are well-represented, and only half of your needs (compare against Broccoli.)  The real problem with starchy foods is that they're carb-dense but nutrient-poor on balance which means they're not only incompatible with low-carb eating they will probably crowd out the nutrient-dense vegetables you should eat.  Since these tend to digest quickly they also provoke a large insulin response.  Note that any of these fried in PUFAs, such as french fries, dramatically multiply the trouble.  These "foods" are served in restaurants (e.g. xxx "over rice" or xxx "with fries") because on a per-calorie basis they cost almost nothing.

Grains (especially wheat) and anything made with them.  Cereals and similar are even worse than starchy vegetables in that the fiber is nearly-all absent as processed and thus has to be added back.  Whole-wheat bread has a horrible protein quality score, is very high in carbs with 2 slices having 24g all on its own (20 of which "count" as there are 4 of fiber) and a modest nutrient balance.  Store-bought breads and cereals, however, almost all contain hydrogenated oils -- that is, the worst sort of PUFAs.  In terms of insulin response grains are almost-indistinguishable from table sugar and some are actually worse.  Yes, this means no pizzas, pastas and similar.  Again, the reason that hamburger comes on a bun at the restaurant or drive-thru is because on a per-calorie basis it costs pennies; to get the same calories with that burger wrapped in lettuce you'd need another patty that contains actual food.
So what do you eat?

Green vegetables such as spinach, kale, broccoli, brussels sprouts, cucumbers, etc.  All are high in nutrients, low in calories, very low in carbohydrate and glycemic load and most have a good amount of fiber as well, all of it being naturally-occurring (not "added back.")  Frozen is fine; fresh is ok if you prefer it but there's no nutritional difference that's material.

Modest amounts of fruits are fine, eaten whole, approximating what you could obtain in season.  Note that neither fruits or vegetables should be "juiced" or otherwise processed; doing so grossly speeds up the absorption of the sugars and destroys much of the fiber value!  Eat your strawberries, in other words, as strawberries, not as a component in a "smoothie."

Full-fat cheeses are perfectly ok; they have a near-perfect (75-80/20-25) balance of fat:protein.  Do not buy the "reduced fat", "2%" or similar cheeses.

Eggs likewise have a decent balance of proteins and fats, eaten whole, although they are a bit protein-heavy.  Eschew the "eggwhite" and "eggbeaters" nonsense; break actual eggs and prepare them as you wish (it's perfectly ok to cook them first if you want them hard-boiled!)  On mass eggs have about 6 grams of both fat and protein, but since fat is 9 cal/gm the energy balance (which is what you care about) is 1.5:1 in favor of fat.  This means about 40% protein, 60% fat when you do the math; the goal for a non-athlete is around 20-25% of intake from protein, so they can't be your primary source but they're good overall.

Full-fat meats and fish.  Pork, chicken, beef and similar are all fine but do not trim or remove the fat portions.  This means you eat your chicken skin-on, eschew the "skinless" chicken breast in favor of the complete version and eat it all.  For steak, consume the fat and do not trim it; same with pork.  For fish prefer fatty fish such as salmon and tuna.

Reserve your excess fat, especially from bacon and sausage cooked for breakfast, and use it for cooking purposes -- such as sauteeing or even microwaving vegetables.  If poured into a coffee mug it will keep for several months in the refrigerator without a problem.  If you're older than 40 your mother probably did this and she knew what she was doing.  For other cooking purposes (e.g. if you want to have an omelet and don't happen to have handy reserved bacon fat) use butter.   Coconut oil, incidentally, if you can find it without extra crap in it, is mostly saturated fat and is one of the very few exceptions to the "no vegetable oil" rule that can be used reasonably-liberally.  Be careful buying it however as much of it is stuffed full of hydrogenated crap which turns it into one of the worst instead of being in the "acceptable" column.  READ THE LABEL.

Use all the spices you wish.  Virtually all of them are zero-carb and zero-calorie.  The same is true for hot sauces and such, but check the labels to make sure they're not stuffed full of sugars or hydrogenated oils.  Most are not but there are exceptions.
If you eat this way it is very hard to exceed 50g/carb a day.  As an example a cup of brussels sprouts has eight grams of carbs, only five of which count (3 are fiber and don't digest.)  If you eat a cup of those, two cups of broccoli flowers during the day in various snacks (8g more), one cup of green sweet pepper chopped up as a component of a main course or side for dinner (4g net) you'll have eaten quite a decent amount of vegetables yet you only consumed 17g of carbs net all day; you'd also have consumed just 108 calories.  You could triple that and still be ok on the carbs and yet have consumed just about 1/6th of your caloric intake requirement!

It then becomes a matter of choosing protein sources without trying to limit fats and, in fact, buying the cheaper sources tends to work better because the stores charge more to trim or otherwise remove the fats!  Between eggs, cheeses and animal products while intentionally leaving the fat content present you'll wind up with a low-carb diet that is very rich in nutrients and almost-completely absent in insulin-spiking carbs that also happens to be free of PUFAs that are associated with heart disease.

Oh, and you won't be hungry either; your body knows how to regulate its food intake all on its own if you simply stop poisoning the signalling pathways (largely mediated by leptin) that tell you whether you're hungry or not.

Welcome to waking up and not really wanting anything to eat until the middle of the day; a nice side effect of living this way is that your pants will fall off.

[Back to Index](../README.html)