---
title: "Penepma Tips"
author: "J. R. Minter"
date: 'Started: 2019-05-03, Last modified: 2019-05-03'
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

[Back to Index](../README.html)

# Introduction

# Use of a random seed

John Donovan explained the use of the random seed in `penepma`
in this [post](https://probesoftware.com/smf/index.php?topic=202.msg8305#msg8305)
on the Probe Software Forum:

> This question came up off-line so I thought I would mention it here.
> 
> When running Penepma from the GUI in the Standard application, the random
> seed is *not* varied. This is for reproducibility of results.
>
> However when running Penepma from **Probe for EPMA** to simulate EDS spectra,
> the random seed *_is_* varied.
>
> To add a random seed in the Penepma input file simply add a line like this to
> your .in file:
>
> ```
> RSEED  1 2                  [Seeds of the random-number generator]
> ```
>
> The defaults are 1 and 2 so you should change them if you want to simulate
> random statistics, though the Penepma documentation does not explain exactly
> **how** they are utilized that I can find. Except for this bit of code:
>
> ```
> C *********************************************************************
> C FUNCTION RAND
> C *********************************************************************
> FUNCTION RAND(DUMMY)
> C
> C This is an adapted version of subroutine RANECU written by F. James C
> C (Comput. Phys. Commun. 60 (1990) 329-344), which has been modified to
> C give a single random number at each call.
> C
> C The 'seeds' ISEED1 and ISEED2 must be initialised in the main program
> C and transferred through the named common block /RSEED/.
> C
> 
> IMPLICIT DOUBLE PRECISION (A-H,O-Z), INTEGER*4 (I-N)
> PARAMETER (USCALE=1.0D0/2.147483563D9)
> COMMON/RSEED/ISEED1,ISEED2
> C
> I1=ISEED1/53668
> ISEED1=40014*(ISEED1-I1*53668)-I1*12211
> IF(ISEED1.LT.0) ISEED1=ISEED1+2147483563
> C
> I2=ISEED2/52774
> ISEED2=40692*(ISEED2-I2*52774)-I2*3791
> IF(ISEED2.LT.0) ISEED2=ISEED2+2147483399
> C
> IZ=ISEED1-ISEED2
> IF(IZ.LT.1) IZ=IZ+2147483562
> RAND=IZ*USCALE
> C
> RETURN
> END
> ```
>
> and the following text:
>
> > 1.2.1 Random-number generator
> > In general, random-sampling algorithms are based on the use of random numbers » uniformly distributed in the interval (0,1). These random numbers can be easily generated on the computer (see, e.g., Kalos and Whitlock, 1986; James, 1990). Among the \good" random-number generators currently available, the simplest ones are the so-called multiplicative congruential generators (Press and Teukolsky, 1992). A popular example of this kind of generator is the following,
> > 
> > Rn = 75Rn¡1 (mod 231 ¡ 1); »n = Rn=(231 ¡ 1); (1.30)
> > 
> > which produces a sequence of random numbers »n uniformly distributed in (0,1) from a given \seed" R0 (< 231 ¡ 1). Actually, the generated sequence is not truly random, because it is obtained from a deterministic algorithm (the term \pseudo-random" would be more appropriate), but it is very unlikely that the subtle correlations between the values in the sequence have an appreciable e®ect on the simulation results. The generator (1.30) is known to have good random properties (Press and Teukolsky, 1992). 
> > 
> > However, the sequence is periodic, with a period of the order of 109. With present-day computational facilities, this value is not large enough to prevent re-initiation in a single simulation run. An excellent critical review of random-number generators has been published by James (1990), where he recommends using algorithms that are more sophisticated than simple congruential ones. The generator implemented in the Fortran 77 function RAND (Table 1.1) is due to L'Ecuyer (1988); it produces 32-bit floating-point numbers uniformly distributed in the open interval between zero and one. Its period is of the order of 1018, which is virtually inexhaustible in practical simulations.




[Back to Index](../README.html)
