---
title: "Quotes"
author: "J. R. Minter"
date: "Started 2021-08-06, Last modified: 2021-08-07"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

[Back to Index](../README.html)


> You cannot legislate the poor into freedom by legislating the wealthy
> out of freedom. What one person receives without working for, another
> person must work for without receiving. The government cannot give to
> anybody anything that the government does not first take from somebody
> else. When half of the people get the idea that they do not have to
> work because the other half is going to take care of them. and when
> the other half of the people gets the idea that it does no good to
> work because somebody else is going to get what they work for, that
> my dear friend, is the end of any nation. You cannot multiply wealth
> by dividing it     
- Dr. Adrian Rogers, 1931.

> Hope is the power of being cheerful in circumstances which we know to be
> desperate. It is true that there is a state of hope which belongs to bright
> prospects and the morning; but that is not the virtue of hope.
> ...    
> Exactly at the instant when hope ceases to be reasonable it begins to be
> useful.    
- G.K. Chesterson



[Back to Index](../README.html)

