---
title: "FEI Sirion SEM"
author: "J. R. Minter"
date: "Started: 2016-08-01, Last modified: 2021-06-11"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

[Back to Index](../README.html)

# Alignment of the FEI Sirion

## Align the final lens aperture

Before you align the column, be sure that the final lens aperture is correctly
aligned. If the final lens aperture has to be aligned, choose the smallest for
the best results. It is recommended to use **20 kV** and **spot 3**,
**UHR Mode**, with the specimen at a working distance of **5 mm**, the eucentric
working distance in the S-FEG. 

(**JM Note:** check if ours lets us use 20 kV in UHR mode.)

When the aperture is well aligned, the image does not rotate at low
magnification or move at high magnification during focusing.
**The position ofthe final aperture should remain constant and should not be**
**changed further during the alignment procedures.**

We do not use an aperture strip but rather Pt apertures in a CM holder. We
currently have the large hole, a 100 and two 30 micron aperures installed.

1. Go to the UHR Mode at 5 mm WD. Select Zero Beam Shift from the Stage menu.

2. Make an image at a magnification of about 10,000X. Select TV Rate from the
Scan pulldown menu and Average 4 from the Filter pulldown menu.

3. Move the stage to find a good area of interest, and focus as best one can.

4. Center a feature with the **Get** function.

5. Click in the Final Lens Modulator check box in the Beam control area, a
cross appears in the center of the screen and the image rotates about a point
on the screen.

6. Adjust the position of the aperture so that the center of the rotation is
over the cross.

7. Increase the magnification to 20,000X and realign. If necessary, repeat at
40,000X. At higher magnification the image moves very slightly in a certain
direction. By tuning the aperture, you can minimize this movement.

8. When corrected, switch off the Final Lens Modulator. There should be no image
shift when the focus control is used.

### Gun Tilt and Shift Field Adjustments

To perform a complete column alignment, use the adjustment procedures starting
with 20kV at Step 1 in the UHR Mode and work down to 500V, saving the results
at each procedure. Each individual adjustment is a complete step-by-step
procedure. For 30kV the mode can be changed to the HR Mode, the sequence in the
procedure being the same.

Use the rectangular X-Y control with cross-hair to change the setting of the
corresponding parameter. Click the left mouse button in this area. You can step
back and forth through each procedure (using the + or - buttons) and go to
another control area for further optimization of the image.

When each procedure ends, the adjustments are stored in the computer. When the
column is correctly aligned, the image stays in focus, and it does not show
substantial image displacement when you change kV and spot-size.
Later when you select a kV that is not in the list, the software performs
an interpolation between the values stored in the table.

### Gun Tilt and Shift Functions

The Gun Tilt and Shift adjustment control area shows the following Information
and functions. The White items in the table are significant to the alignment and
the Gray items are for additional information to the user.


| Field Name | Function |
| ---------- | --------------------------------------- |
| GTX,Y | Displays actual value of Gun Tilt X and Gun Tilt Y stored during last alignment. |
| GSX,Y | Displays actual value of Gun Shift X and Gun Shift Y stored during last alignment. |
| High Tension | Displays actual value of the kV. |
| ProbeCurr | Displays spot-size. The procedure starts with spot-size 1 and steps up to spot-size 7. |
| X-Over | Switches to crossover mode. Shows a marker on screen and positions the crossover relative to it. Use crossover mode only when there is no image. Use Gun Tilt and Gun Shift controls to bring the crossover to the center of the on-screen marker.|
| Lens Mod | Switches on the final lens modulator that modulates the final lens at the given magnification with amplitude coupled to magnification. Switch the scan mode to TV rate before using this mode. If the system is correctly aligned, the rotation center is in the center of the screen. |
| Intermediate Lens Mode |Service use only |
| DC On | Service use only. Default ON |
| Contrast |  Controls contrast of the applied detector. Use it if the contrast changes when spot-size is changed during the alignment steps. |
| Gun Tilt / Shift | Controls Gun Tilt and Gun Shift adjustments in both X and Y. The actual Gun Tilt and Gun Shift setting is indicated by the position of the cross in the field. If more tilt/shift is required at the edge of the screen, release the mouse button and click again in the control. |
| 0 Tilt, Shift | These buttons set Gun Tilt and Gun Shift to zero. |

#  SEM-EDS stage-mounted Faraday Cup issues

## From the Probe Software Forum by `sem-geologist` on 2021-06-11

Dear Collective Knowledge,

I am not sure that this is right sub-forum for this topic, As I could not found "General SEM Issues".

So I want to analyze the e-beam-extreme sensitive minerals, and SEM equipped with its multiple, large diameter EDS with very close proximity to the sample comes as best combination in the sense of counts for given beam exposure. EPMA-WDS TDI is out of the equation, as there are to many major elements, and TDI works only on the first 5 (with 5 WDS). SEM-multi EDS system makes TDI unnecessary, as it gives more counts with very short exposure, than few minute WDS.

The SEM problem with current measurements
All EPMA's has Faraday cup built-in column. That is a tremendous advantage - it has the constant length of conductor from cup to pico-amperometer. On SEM with stage mounted cup, the current reading will differ depending from where on the stage the cup (or set of standards with built-in cup) is mounted as the current path from cup to pico-amperometer will be different. In my case it is giving up to 5% difference in measured current! (Ouch!). That can propagate such error for standard-based EDS analysis.

Another problem is standard-set built-in Faraday cups.
We have some SPI, MAC, etc reference material sets with Faraday-cup built in (placed in center or at side of mount).
We polish these standard mounts once a year and do new carbon re-coating.
I guess this caused our built-in Faraday cups to be contaminated. On AsB (angularly selective BSE) on SEM I can see some debris inside some of cups, but other cups looks clean. Another concern is that probably carbon had piled up from every coating after mount polishing, as it is impossible to polish-off carbon inside the cup. I guess those Faraday-cups are junked at this point. I see that on 20kV Faraday cup is giving higher current compared to beam hitting by the hole, albeit the difference is much less than what I see on EPMA when measuring absorbed and beam (in column FC) current. If I set SEM to 10kV I get lower current reading inside the stage-mounted Faraday cup  than outside (which is illogical). I think that shows that all my FC are contaminated, and I am doomed.

Has anyone a hint how to clean those FC?
Could there be another hidden problem in my SEM setup and how to troubleshoot that?
Would buying separate FC (stand alone, not mounted with standards) would solve my problem?

SEM: Zeiss Sigma (FE) 

PS.: I start to understand the idea, why Bruker does not use the FC reading, but calibrates intensities to specified and measured X-ray intensity of material dedicated for that - in that way this problem with variations in FC measurements can be overcome. I think Au piece would perfectly fit for that porpoise as it is the most inactive metal; copper would oxidize, and would influence the counts at low voltages. The trouble is if I want to use DTSA-II which needs the beam current; hmmm... maybe I could simply define the ratio between Au and fictional beam current, and recalculate such net intensities into fictious current equivalent. If I would do standards and unknown with same fictitiously acquired beam current the quantification should work, I guess...

# Nicholas Ritchie responds

There is something really weird going on if your probe current measurements vary by 5 % over the range of stage positions and your out-of-cup is higher than your in cup.  It suggests to me that maybe the stage isn't isolated correctly, the path to ground (BNC) is poor or the faraday cup isn't well designed.

Also most of the picoammeters built into SEMs are not as good as those in microprobes.   This is usually not an issue if you maintain the probe current to within 10% but can be an issue if you vary the probe current by an order-of-magnitude between measurements in a measurement set.  (But I don't know why you'd do this.)

My experience with Faraday cups of all creeds and colors has been good.  I find the reproducibility to be excellent. I've never seen a Faraday cup go bad except when the hole gets plugged with Ag paint or some such.   I've used my primary Faraday cup for a decade or more but I often use cups integrated into standard blocks.  So long as the beam raster is fully enclosed in the darkness of the cup, the measurements are comparable between Faraday cups.  Having said this, I usually use the same cup for all measurements if possible (belt-and-suspenders).

I do believe there is merit to using the X-ray signal directly to calibrate probe current as you describe and as Bruker and Oxford do.  This method also accounts for geometric differences so long as the calibration material and unknowns are at the same working distance.  Gold would be a good choice.

# More from the mystery...

General EDS Issues / Re: SEM-EDS stage-mounted Faraday Cup issues (by sem-geologist)

Thank You Nicholas,

However I fooled myself. I found out that I got myself into anecdotal situation, albeit I had lost whole day.
I had found out today that I was terribly trolled. Well there were many signs which I had ignored as I had not took that into possibility.
The thing is that that Zeiss SEM has oxymoron config: Variable Pressure capability (environmental) and Schottky field emission cathode. Because of VP with FEG it is equipped with two ion pumps (not single, when no VP) and naturally (that important info is missing in booklets and specifications) in such configuration that secondary ion pump becomes expendable part - VP mode shortens its lifetime to something max 2-3 years. So naturally it burned-out about ~5 years ago. I can't remember why it could not be replaced/repaired then (zeiss service thing), but later every time we had a reemerging discussion (people are so restless to try to do stupid things again and again) if to buy and replace it with a new - I was insisting to do not, as FEG + VP is a complete nonsense in my opinion, and we have environmental tungsten tip equipped Jeol SEM (no ion pumps) for that kind of wankerry. Secondary ion pump being "out of order" was a guarantee that that instrument time will be not wasted to kind of complete rubbish analysis. EDS gathered at variable pressure had spread so much of bad impression among many professors and they think of EDS as very extremely uncertain method. It is so hard to undo the damage - much harder to change the opinion of professor than to teach right thing the students.
... and so two weeks ago that pump was replaced, and I had no idea about that.

So I had ignored many clear signs screaming into my face that I am on VP mode.
1. at first I saw previous project opened with one of those rubbish studies, and though "Oh dear, even this lunatic started to use this SEM; Had someone (How possibly?) at last convinced him of benefits of coating those rubbish samples?" (Well there is long very weird story from times I was explicitly working on SEM and I could not convince him. Unfortunately there is whole army of these weirdos. When I had to chose my position if to stay to work on SEM or move to EPMA, one of the factors to chose EPMA position was just to distance myself away from these never-ending nonsense stuff). The moral is that some people never change, while machines do.
2. I got 0.37 nA when measured in FC, and a month ago I was getting 0.6 nA at the same WD and aperture. I could not believe that FEG had so terribly aged in such a short time. So had checked it independently on 4 FC - while it was getting similar readings at center it was weirdly getting higher reading near the edge of FC. Taking VP into account now it makes perfect sense. But that looked for me like FC contamination + tip aging at that moment.
3. While checking for polishing-debris inside the FC, I was trying to use in-lense detector, but could not get a good picture. Again I thought that something is bad going with in-lense detector.
4. I noticed that FC reading differs from position on the stage. FC are different and probably has different depths, so different beam distances and different absorption by gas had caused different current readings.
5. I had reduced HV so in-lense picture would get better. It was not at all, and I was getting less current inside FC than outside of FC. With VP in mind that observation now makes perfect sense.
And I guess the absorbed stage current also was influenced by VP as part of charge is taken by gas.

[Back to Index](../README.html)