---
title: "Research Tips"
author: "J. R. Minter"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  knitr:::html_vignette:
    css: ../theme/jm-mod-vignette.css
    number_sections: yes
    toc: yes
vignette: >
  %\VignetteIndexEntry{Research Tips}
  %\VignetteEngine{knitr::rmarkdown}
---

[Back to Index](../README.html)

These are tips on effective scientific research collected by John Minter from selected web sources.

# Software Carpentry

Greg Wilson is an excellent teacher.


There is a [youtube](https://www.youtube.com/playlist?list=PLhFTuW7KWApwoo2DHzpWLhA19zenWF1LF) playlist from 2012.

## Key suggestions:

1. Plan your work in approximately 45 to 60 minute segments where you have optimal focus.

2. Write and test logical units thet fit the 7 $\pm$ 2 items one can keep in short term memory and assemble the into functions/blocks. **Note:** The shell history or iPython history can save typing and help.

3. Test and debug as you go. This save time in the long run.

4. Commit short, logical blocks to version control using meaningful commit messages to aid in later search.

## Installing the software on Windows

Getting the software set up on Windows can be a challenge. I like the Msys2 system


Get the basic installer [here](https://msys2.github.io/). There are great packages on [github](https://github.com/Alexpux/MSYS2-packages). 

1. Install msys2
2. Update the pacman database: `pacman -Sy pacman`
3. Install base devel: `pacman -S base-devel`
4. Install sqlite: `pacman -S sqlite`
5. Install nano: `pacman -S nano`
6. Install svn: `pacman -S svn`


# Good advice from Neal Anderson

From [Practical Process Research and Development - A guide for Organic Chemists, Second Edition 2nd Edition, p. 19](http://www.amazon.com/dp/0123865379). Hat Tip [ChemJobber](http://chemjobber.blogspot.co.uk/2016/02/bonus-process-wednesday-life-tips-from.html).

> The attitudes for chemists in process R&D may differ from those of drug discovery chemists.

> 1. Teamwork is key. Optimize interactions between discovery chemists, engineers, analysts. microbiologists, operators, Environmental Health & Safety officer, pharmaceutical chemists. QA/QC personnel, attorneys for patent applications, out-sourcing (CROs, CMOs), your manufacturing counterparts, and regulatory personnel. **Don't trivialize the work of others, especially if you don't understand their job.** (emphasis mine)
2. Recognize that the need to minimize impurities drives process development.
3. Know the edge of failure for your operations. For rapid development, stay away from the edge. For cost-effective processes, you may want to operate close to the edge.
4. Reproducible, accurate analytical data are necessary for effective process development.
5. If an operation is extremely difficult, reconsider. Perhaps additional information will simplify the operation.
6. Heed the advice of ecologists: "We're all in this together." Humor helps defuse the gravity of most difficult situations.
7. During process introduction and scale-up boring situations can be good - that means there are no problems to address.



# William Shockley on what makes an effective researcher
[Brian McGill](http://dynamicecology.wordpress.com/2014/01/23/william-shockley-on-what-makes-a-person-write-a-lot-of-papers-and-the-superstar-researcher-system/) has a nice summary on Shockley's view of research. He used publication as a metric and noted the factors that were required:

1. ability to think of a good problem
2. ability to work on it
3. ability to recognize a worthwhile result
4. ability to make a decision as to when to stop and write up the results
5. ability to write adequately
6. ability to profit constructively from criticism
7. determination to submit the paper to a journal
8. persistence in making changes (if necessary as a result of journal action).

Shockley then posits, what if the odds of a person clearing hurdle ``i`` from the list of 8 above is $p_i$? Then the rate of publishing papers for this individual should be proportional to $p_{1}p_{2}p_{3}\dots p_{8}$. This gives the multiplication of random variables needed to explain the lognormal distribution of productivity (Shockley goes on to note that if one person is 50% above average in each of the 8 areas then they will be 2460% more productive than average at the total process).

Another conclusion is that if you are really bad at just one factor ($p_{i}$ close to zero for just one $i$), it sinks your overall productivity. This is innate in the multiplicative model. This is a solid rationale for working on one's weakest required skill before enhancing one's best requirement - or at least collaborating with those skills who complement yours.


[Back to Index](../README.html)