---
title: "MS Office Tips"
author: "J. R. Minter"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MS Office Tips}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

[Back to Index](../README.html)

These are John Minter's tips for MS Office.
They were compiled from several web sources.

## Skype for Business

How do I use Skype for Business? 
  
Click [here](https://www.youtube.com/watch?v=7_c4zVJ739M&feature=youtu.be) to watch a Skype for Business: Step-by-step guide for new users 
  
Some additional Training videos:   
  
Click [here](https://www.youtube.com/watch?v=qVq7A7nS_TQ&feature=youtu.be&list=PLH5ElbTc1hWQirKampULE7vlfTbhSqssq) for a video Introducing Skype for Business 
  
Click [here](https://www.youtube.com/watch?v=eCIGpbukmow&feature=youtu.be&list=PLH5ElbTc1hWQirKampULE7vlfTbhSqssq) to see how to add a contact in Skype for Business 
  
Click [here](https://youtu.be/oEBQgOgAtnk?list=PLH5ElbTc1hWQirKampULE7vlfTbhSqssq) for a video on Presence and IM in Skype for Business 
  
Click [here](https://youtu.be/i9ubU-ndMZE?list=PLH5ElbTc1hWQirKampULE7vlfTbhSqssq) to see how to Meet and share using Skype for Business 
  
Click [here](https://youtu.be/XNuIQks8kuk?list=PLH5ElbTc1hWQirKampULE7vlfTbhSqssq) to see how to schedule a Skype for Business meeting


## Outlook

I have had problems with links with spaces. The key is to surround the
link with what
[Microsoft](https://support.office.com/en-ie/article/Add-links-containing-spaces-to-an-e-mail-message-65e3086b-8f1c-4e4c-88ab-7489b3c823b1)
calls `chevrons`. See the example below

```
<\\ekc1\fs1\My Project\@Weekly Meeting\+2015 Characterization Meeting Agenda>
```

## PowerPoint

### Footers don't show up

From [Holly Green](http://blogs.mccombs.utexas.edu/the-most/2012/06/04/when-the-slide-number-doesnt-show-in-powerpoint/)

If you're working in PowerPoint, and you want the slide number to display on the slide, the process is generally simple:

1. Go to the Insert tab.
2. Click the Slide Number button.
3. On the Slide tab, check the Slide Number box.
4. Click Apply to All to make the slide number show on all slides, or Apply to make the slide number show on just the current slide.

### Template location

On Win7 ``C:\Users\jrminter\AppData\Roaming\Microsoft\Templates``





[Back to Index](../README.html)