---
title: "Use Apple Air Pods"
author: "Jason Cross"
date: "Started 2018-01-19, Last modified: 2020-05-27"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

[Back to Index](../README.html)

# How to use AirPods with Apple TV

Jason Cross provides tips using Apple's wireless headphones make it easy
to enjoy a little private TV time.

Apple’s AirPods are far from perfect, but they some of the best true
wireless earbuds on the market, particularly for those with a lot of
Apple gear. 

Everyone knows that AirPods work with iPhones, iPads, and Macs, but we
tend to overlook the fact that they also work wonderfully with Apple TV
(4th generation or 4K). With the audio beaming wirelessly across your
living room to your AirPods, you can enjoy late-night or early-morning
TV without disturbing everyone else in your house. Here’s how you make it happen.

# Pairing with Apple TV

If your Apple TV is running tvOS 11 or later, and it’s logged in to the
same iCloud account as the iPhone or iPad you’ve paired your AirPods
with, you’re already done!

AirPods automatically pair with other Apple devices using the same
iCloud account, and that includes Apple TV (as of tvOS 11). 

# Airpods pairing

With tvOS 11, your AirPods should automatically pair with Apple TV if it
shares an iCloud account with another device you paired your AirPods to.

If your Apple TV uses a different iCloud account, or for some reason
isn’t running tvOS 11 or later, you’ll have to pair your AirPods
manually. Here’s how you do that.

1. Put your AirPods in the case and open the lid.

2. On the Apple TV, open the Settings app.

3. Click on `Remotes and Devices`, then `Bluetooth`.

4. Select your AirPods from the list.

5. If you use a different iCloud account on your Apple TV, or it’s not
running tvOS 11, you’ll have to pair your AirPods the old-fashioned way.

# Connecting to your AirPods on Apple TV

Once your AirPods are paired with your Apple TV, you have to actually
connect to them to make the Apple TV audio come out of your AirPods.

The simplest way to do this is to hold down the Play/Pause button on
your Apple TV remote (or the Remote app) when you’re at the home screen
or in the TV app. A menu will pop up allowing you to select music and
which device to play it through. Select your AirPods here.

# Airpods connecting

When at the main Apple TV menu, press the Play/Pause button for a couple
of seconds to get this handy audio select menu.

Some users claim that pressing the Siri button on the remote and saying
“Connect to my AirPods” will immediately connect to them, but try as I
might, I’ve never gotten this to work. Instead, it brings me to the
Settings menu. There’s no harm in trying it yourself.

# Using AirPods with Apple TV

Some of the functions you’re used to on your iPhone will not work when
using AirPods with Apple TV. You can’t use them to talk to Siri, for
example—you have to continue using the Siri remote for that.

But some of the AirPod’s functions still work great. You can double-tap
one of them to pause and resume video. Taking an AirPod out of your ear
automatically pauses whatever audio or video is playing. And of course,
simply putting your AirPods back into their case and closing the lid
will disconnect them.

**Note:** When you purchase something after clicking links in our
articles, we may earn a small commission. Read our affiliate link policy
for more details.

[Back to Index](../README.html)