---
title: "Tips on Using DTSA-II"
author: "J. R. Minter"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  knitr:::html_vignette:
    css: ../theme/jm-blue-vignette.css
    number_sections: yes
    toc: yes
---

[Back to Index](../README.html)

# Key tricks

## Database

Install derby. Use ij

connect 'jdbc:derby:/Users/jrminter/DTSA/Database v2/'

## Frequently needed scripts

### In OSImageAnalysis git repository

**In dtsa2/productionScripts directory:**

- JmGen.py is the workhorse.
- DumpMaterials.py and the **restore script** stds.py. Edit this last one to add new materials.
- listDetCalibrations.py to see what calibrations we have
- testGetMassFraction.py to aid adding new standards

## A proposed standard

Mark suggested I might be able to order this from
[Ted Pella](https://www.tedpella.com/calibration_html/UHV-EL_Reference_Standards_for_EDS_WDS.htm)
in Dec.

```
From Ted Pella

A standard
6075    UHV-EL 6 Rectangular Retainer, 9 x 12mm,
        with 6 reference standards (select from list)  each    685.00  
or
6076    UHV-EL 9 Square Retainer, 13 x 12mm,
        with 9 reference standards (select from list)  each    995.0

1. Faraday Cup, for beam current measurement, is available for all of the
   retainers and will take one of the spaces.
2. 146. Zinc Oxide  ZnO HP  ?
3. 102. Silicon Si  C   5N*
4.   1. Aluminum    Al  F   3N* or 
     3. Aluminum Oxide Al2O3 C 4N*
5.  30. Copper  Cu  F   2N or 
    31. Cupric Oxide    CuO P   3N
6.  89. Palladium   Pd  P   3N
7.  16. Boron Phosphide BP  P   3N
8. 108. Silver  Ag  F   3N5
9. 179. Rutile  TiO2

```

## Defining a custom material

It is important to add a name when one define a name when defining a
custom material that will be used with the MC3 simulations. Here is an
example for PET. **Note that the mass fractions are useful for complex materials.**


```
pet = epq.Material(epq.Composition([epq.Element.C,epq.Element.H,epq.Element.O],
                                   [0.62502,0.04196,0.069042]),epq.ToSI.gPerCC(1.37))
pet.setName("PET")
```

or

```
k412 = epq.Material(epq.Composition([epq.Element.O,
                                     epq.Element.Mg,
                                     epq.Element.Al,
                                     epq.Element.Si,
                                     epq.Element.Ca,
                                     epq.Element.Fe],
                                    [ 0.4276,
                                      0.1166,
                                      0.0491,
                                      0.2120,
                                      0.1090,
                                      0.0774]
                                      ),
                                    epq.ToSI.gPerCC(2.600))
k412.setName("K412")

```


The final step is **really important** - sometime the simple approach produces unicode characters in output file name generated automatically and these crash. **Simple names are better!!!**

**Get the mass fractions from the molecular formula the easy way:** 
I added a function to jmGen.py (v. 0.0.7) that wraps the utility functions in DTSA-II. The prototype is:

```
getMassFractions(compound, elemList, iDigits)
```

that one uses like this for an AZO compound with 2\% Al substituted for Zn:

```
import gov.nist.microanalysis.EPQLibrary as epq
import dtsa2.jmGen as jmg

elements = [epq.Element.Al, epq.Element.Zn, epq.Element.O]
massFra = jmg.getMassFractions("Al2Zn98O100", elements, 5)
```

which returns a dictionary with the mass fractions:

```
{'Al': 0.00669, 'O': 0.19841, 'Zn': 0.7949}
```



## File naming tricks

For simulations, I often name files with a **compound-kV-nTraj** type syntax. Writing a helper function can mimimize repetition


```
def getSpecPath(baseName, baseDir, e0, nTraj):
    sName = "%s-%g-kV-%g-Traj" % (baseName, e0, nTraj)
    sPath = "%s/%s.msa" % (baseDir, sName)
    return sPath
```

I should also wrap a sequence like this:

```
spcFile = getSpecPath("Al", outDir, e0, nTraj)
al = wrap(readSpectrum(spcFile))
sp = spc.getProperties()
sp.setDetector(det)
al.display()
```

Here is my work-in-progress for a quantification script


```

ff = epq.FilterFit(det, epq.ToSI.keV(e0))
ff.addReference(element("Al"), al)
ff.addReference(element("Zn"), zno)
ff.addReference(element("O"), zno)
kr  = ff.getKRatios(azo)
kO  = kr.getKRatioU(epq.XRayTransition(epq.Element.O,epq.XRayTransition.KA1))
kZn = kr.getKRatioU(epq.XRayTransition(epq.Element.Zn,epq.XRayTransition.LA1))
kAl = kr.getKRatioU(epq.XRayTransition(epq.Element.Al,epq.XRayTransition.KA1))

fs = "%g\t%g\t%g\t%g\t%g\t%g" 

znoMat = epq.Material(epq.Composition([epq.Element.Zn,epq.Element.O],
                                      [0.80349,0.19651]),
                                      epq.ToSI.gPerCC(5.61))

stds = { epq.Element.Zn : znoMat, epq.Element.O : znoMat }

print (fs % (kO.doubleValue(), kO.uncertainty(),
             kZn.doubleValue(), kZn.uncertainty(),
             kAl.doubleValue(), kAl.uncertainty() ))


qr = quant(kr, 35.0, e0, stds, None, False, None, None)

print(qr)

print(dir(qr))

# print(qr.atomicPercentU(epq.Element.Al))
# print(qr.atomicPercentU(epq.Element.Zn))
# print(qr.atomicPercentU(epq.Element.O))

print(dir(qr.atomicPercentU(epq.Element.Al)))

# print(dir(epq.Element.Al))

def formatElement(qr, el):
    strLine  = "%s, " % el.toAbbrev()
    strLine += "%.6f, " % qr.atomicPercentU(el).doubleValue()
    strLine += "%.6f" % qr.atomicPercentU(el).uncertainty()
    return(strLine)

print("El, at.fra.mu, at.fra un")
out = formatElement(qr, epq.Element.Al)
print(out)
out = formatElement(qr, epq.Element.Zn)
print(out)
out = formatElement(qr, epq.Element.O)
print(out)


```


# System Admin

## Preferences

On Windows, preferences are stored in the registry. The base key is:

```
[HKEY_CURRENT_USER\Software\JavaSoft\Prefs\gov]
```
It is always useful to export this as a `.reg` file.

On MacOSX, preferences are stored in a `.plist` file...

```
~/Library/Preferences/gov.nist.microanalysis.plist
```


# Getting NISTMonte Monte Carlo packages to work with Iona and Jupiter

DTSA-II Iona seems to not export classes that were available
in Halley. I noticed that the `mcSimulate3.py` file had these
curious lines at the top:

```
import sys
sys.packageManager.makeJavaPackage("gov.nist.microanalysis.NISTMonte.Gen3", "CharacteristicXRayGeneration3, BremsstrahlungXRayGeneration3, FluorescenceXRayGeneration3, XRayTransport3", None)
```

Note: it does **not** like the lines to be split...

I did a Google search  and found
[this](http://sourceforge.net/p/jython/mailman/message/6725556/)
explanation: The following code works with Jython launched from the jar in the standard install:

```
import java.awt
f = java.awt.Frame()
f.title = "Hello AWT"
f.visible = True
```

but when run with `Jython.jar` from the standalone install
the code gives

```
>java -jar jython.jar
Jython 2.2b1 on java1.6.0 (JIT: null)
Type "copyright", "credits" or "license" for more information.
>>> import java.awt
Traceback (innermost last):
  File "", line 1, in ?
ImportError: no module named awt
>>> ^Z
```

WORKROUND

You need to nudge the system to do what caching would have done:-

```
import sys
sys.packageManager.makeJavaPackage("java.awt", "Window", None)
import java.awt
f = java.awt.Frame()
f.title = "Hello AWT"
f.visible = True
```

[Back to Index](../README.html)
