Mac OSX Tips
========================================================

[Back to Index](../README.html)

## Quick
### Lock Screen
Cntl-shift-eject keys

## Startup items
### my favorite color for desktop
RGB: 0,34,64

## global environment variables
If one has global environment variables to set at
launch time and be avaible to all applications (that
might note get them from ``.profile``) one can put
them in ``/etc/launchd.conf``. An example might be

```
setenv IMG_ROOT /Users/jrminter/dat/images
```

Note how this uses ``csh`` syntax...

## Personal environment variables
These are best set in ``.profile``

## Prework for Mavericks

### For a clean Install

From [Christina Warren](http://mashable.com/2013/10/23/clean-install-os-x-mavericks/)

### Homebrew

Current error building R packages

A hint from [StackOverflow](http://stackoverflow.com/questions/19533220/cannot-install-r-package-from-source-in-mac-osx-maverick) fixed the problem!!!

Edit ``Makeconf`` in  ``/Library/Frameworks/R.framework/Resources/etc``

set

```
CC=clang
CXX=clang++
```

Error described below:

It uses something like:

```
llvm-gcc-4.2 -arch x86_64 -std=gnu99 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c spectrum.c -o spectrum.o
```

Which produces this error

```
make: llvm-gcc-4.2: No such file or directory
```

This seemed to work for me until I updated homebrew...
From [John Bohn](http://jjbohn.info/blog/2013/10/02/fixing-homebrew-on-mac-osx-mavericks/)

I've had lots of problems with homebrew since upgrading to Mavericks.
The same problems also existed when trying to ``rbenv install`` and
really anything else that compiles. The root cause of the issue ended
up being a conflict Mountain Lion Command Line Tools and the ones
provided by Maverick.

There was an easy solution however. By running ``xcode-select``
(a tool provided to change the path to the current active developer
directory) it will fix the issue.

Specifically, run this from your terminal:

```
xcode-select --install
```

This will bring up a dialog to install the Command Line Tools
(which you will have to type in your password) and will fix the problem.

## Hardware tips
### Eject a stuck CD/DVD
1. Restart the computer. If necessary, use the reset/interrupt
button.
2. Immediately after the system startup tone, press and
hold the ``CMD-OPT-O-F`` key combination. The computer starts
up to a text-only screen, indicating that you are in
Open Firmware.
3. At the prompt, type ``eject cd`` and return.
4. At the prompt, type ``mac-boot`` and return.

[Back to Index](../README.html)