---
title: "VS2010 Tips"
author: "J. R. Minter"
date: "Started: 2013-12-27, Last modified: 2017-10-28"
output:
  knitr:::html_vignette:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
---

[Back to Index](../README.html)

# A quickie for VS2003.NET
Solution to not being able to open program database, From [here](http://social.msdn.microsoft.com/Forums/en-US/c18f09f2-871e-4810-a803-c889994415c3/visual-studio-fatal-error-c1033-cannot-open-program-database?forum=Vsexpressvc)

> Because of legacy code I required VS 2003 with at least SP1 on Windows7 to build C++.  I was able to resolve this problem by choosing compatibility mode Vista.  When I installed the program the default selection was XP service pack 3.

Some useful tips for Visual Studio 2010

# Using cmake

[StackOverflow](http://stackoverflow.com/questions/4219479/using-cmake-with-windows-7-visual-studio-2010-and-the-command-line)

# Reduce project size

Visual Studio creates ``Intellisense`` files that
add a lot of size to a project.

A very helpful solution from [StackOverflow](http://stackoverflow.com/questions/7706984/visual-studio-2010-c-project-remove-sdf-file)

> You can safely delete the .sdf file and ipch folder but you can also stop VS from putting those files in the project folder in the first place. (Useful if you have your source in a SVN or other synchronized folder, or if you store your project on a small volume like a USB stick or SSD and you don't want those large files stored in the same folder).

> Go to:

```
Tools -> Options -> Text Editor -> C/C++ -> Advanced
```

> In the ``Fallback Location``, set ``Always Use Fallback Location`` to ``True`` and ``Do Not Warn If Fallback Location Used`` to ``True``. In ``Fallback Location`` you can either put a path like ``C:\Temp`` or if you leave it blank then VS will use the temporary directory in your ``AppData`` folder.

HT Ozzah.

Note: another user noted:

> One can actually prevent VS making these files in the first place by setting ``Tools -> Options -> Text Editor -> C/C++ -> Advanced -> Disable Database`` option to ``True``.
  
I prefer the temp file approach...

[Back to Index](../README.html)