---
title: "Sublime Text 3 Tips"
author: "J. R. Minter"
date: "Started: 2015-02-13, Last modified: 2019-04-01"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

[Back to Index](../README.html)

These are John Minter's tips for using the editor ``Sublime Text 3``.

# Key info

A. Documentation 

   - [Official](http://www.sublimetext.com/docs/3/)
      Documentation
    
   - [Unofficial](https://sublime-text-unofficial-documentation.readthedocs.io/en/latest/)
      Documentation
      
   - [Installing via Homebrew](https://www.code2bits.com/how-to-install-sublime-text-on-macos-using-homebrew/)
      using the [homebrew cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sublime-text.rb)
      

# Better Markdown

From [Marius Schulz](https://blog.mariusschulz.com/2014/12/16/how-to-set-up-sublime-text-for-a-vastly-better-markdown-writing-experience)

1. Install the `Monokai Extended` package.
2. Install the `Markdown Extended` package to get the additional color scheme.


# Spell Checking

One can set the dictionary from the ``View`` menu. One can toggle spell checking either from the ``View`` menu or with ``F6``. For more information, see [here](https://www.sublimetext.com/docs/3/spell_checking.html).

# Setting file associations

From [StackOverflow](http://stackoverflow.com/questions/7574502/set-default-syntax-to-different-filetype-in-sublime-text-2)

In the current version of Sublime Text 2 and 3 you can set the syntax for all files of a certain file extension using an option in the menu bar. Open a file with the extension you want to set a default for and navigate through the following menus: 

```View -> Syntax -> Open all with current extension as... ->[your syntax choice].```

# The Package Control add-in

**Note** As of 2019-03-09, this no longer seems to work... It used
to be quite helpful.



# My current preferences

**Default**

```
{
    // Sets the colors used within the text area
    "color_scheme": "Monokai.sublime-color-scheme",

    // Note that the font_face and font_size are overridden in the platform
    // specific settings file. Set them in your User File Preferences.
    "font_face": "",
    "font_size": 10,

    "font_options": [],
    "theme_font_options": [],

    // Characters that are considered to separate words
    "word_separators": "./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?",

    // Set to false to prevent line numbers being drawn in the gutter
    "line_numbers": true,

    // Set to false to hide the gutter altogether
    "gutter": true,

    // Spacing between the gutter and the text
    "margin": 4,

    // Fold buttons are the triangles shown in the gutter to fold regions of text
    "fold_buttons": true,

    // Hides the fold buttons unless the mouse is over the gutter
    "fade_fold_buttons": true,

    // Columns in which to display vertical rulers
    "rulers": [],

    // Set to true to turn spell checking on by default
    "spell_check": false,

    // The number of spaces a tab is considered equal to
    "tab_size": 4,

    // Set to true to insert spaces when tab is pressed
    "translate_tabs_to_spaces": false,

    // If translate_tabs_to_spaces is true, use_tab_stops will make tab and
    // backspace insert/delete up to the next tabstop
    "use_tab_stops": true,

    // Set to false to disable detection of tabs vs. spaces on load
    "detect_indentation": true,

    // Calculates indentation automatically when pressing enter
    "auto_indent": true,

    // Makes auto indent a little smarter, e.g., by indenting the next line
    // after an if statement in C. Requires auto_indent to be enabled.
    "smart_indent": true,

    // Adds whitespace up to the first open bracket when indenting. Requires
    // auto_indent to be enabled.
    "indent_to_bracket": false,

    // Trims white space added by auto_indent when moving the caret off the
    // line.
    "trim_automatic_white_space": true,

    // Disables horizontal scrolling if enabled.
    // May be set to true, false, or "auto", where it will be disabled for
    // source code, and otherwise enabled.
    "word_wrap": "auto",

    // Set to a value other than 0 to force wrapping at that column rather than the
    // window width
    "wrap_width": 0,

    // Set to false to prevent word wrapped lines from being indented to the same
    // level
    "indent_subsequent_lines": true,

    // Draws text centered in the window rather than left aligned
    "draw_centered": false,

    // Controls auto pairing of quotes, brackets etc
    "auto_match_enabled": true,

    // Word list to use for spell checking
    "dictionary": "Packages/Language - English/en_US.dic",

    // Sets which scopes are checked for spelling errors
    "spelling_selector": "markup.raw, source string.quoted - punctuation - meta.preprocessor.include, source comment - source comment.block.preprocessor, -(source, constant, keyword, storage, support, variable, markup.underline.link, meta.tag)",

    // Set to true to draw a border around the visible rectangle on the minimap.
    // The color of the border will be determined by the "minimapBorder" key in
    // the color scheme
    "draw_minimap_border": false,

    // Always visualise the viewport on the minimap, as opposed to only
    // showing it on mouse over
    "always_show_minimap_viewport": false,

    // If enabled, will highlight any line with a caret
    "highlight_line": false,

    // Valid values are "smooth", "phase", "blink" and "solid".
    "caret_style": "smooth",

    // These settings control the size of the caret
    "caret_extra_top": 2,
    "caret_extra_bottom": 2,
    "caret_extra_width": 1,

    // Set to false to disable underlining the brackets surrounding the caret
    "match_brackets": true,

    // Set to false if you'd rather only highlight the brackets when the caret is
    // next to one
    "match_brackets_content": true,

    // Set to false to not highlight square brackets. This only takes effect if
    // match_brackets is true
    "match_brackets_square": true,

    // Set to false to not highlight curly brackets. This only takes effect if
    // match_brackets is true
    "match_brackets_braces": true,

    // Set to false to not highlight angle brackets. This only takes effect if
    // match_brackets is true
    "match_brackets_angle": false,

    // Enable visualization of the matching tag in HTML and XML
    "match_tags": true,

    // Highlights other occurrences of the currently selected text
    "match_selection": true,

    // Additional spacing at the top of each line, in pixels
    "line_padding_top": 0,

    // Additional spacing at the bottom of each line, in pixels
    "line_padding_bottom": 0,

    // Set to false to disable scrolling past the end of the buffer.
    "scroll_past_end": true,

    // This controls what happens when pressing up or down when on the first
    // or last line.
    "move_to_limit_on_up_down": false,

    // Set to "none" to turn off drawing white space, "selection" to draw only the
    // white space within the selection, and "all" to draw all white space
    "draw_white_space": "selection",

    // Set to false to turn off the indentation guides.
    "draw_indent_guides": true,

    // Controls how the indent guides are drawn, valid options are
    "indent_guide_options": ["draw_normal"],

    // Set to true to removing trailing white space on save
    "trim_trailing_white_space_on_save": false,

    // Set to true to ensure the last line of the file ends in a newline
    // character when saving
    "ensure_newline_at_eof_on_save": false,

    // Set to true to automatically save files when switching to a different file
    // or application
    "save_on_focus_lost": false,

    // Save via writing to an alternate file, and then renaming it over the
    // original file.
    "atomic_save": false,

    // The encoding to use when the encoding can't be determined automatically.
    // ASCII, UTF-8 and UTF-16 encodings will be automatically detected.
    "fallback_encoding": "Western (Windows 1252)",

    // Encoding used when saving new files, and files opened with an undefined
    "default_encoding": "UTF-8",

    // Files containing null bytes are opened as hexadecimal by default
    "enable_hexadecimal_encoding": true,

    // Determines what character(s) are used to terminate each line in new files.
    // Valid values are 'system' (whatever the OS uses), 'windows' (CRLF) and
    // 'unix' (LF only).
    "default_line_ending": "system",

    // When enabled, hovering over a word will show a popup listing all
    // possible locations for the definition symbol. Requires index_files.
    "show_definitions": true,

    // Shift+tab can be used to insert an explicit tab when tab_completion is
    // enabled.
    "tab_completion": true,

    // Enable auto complete to be triggered automatically when typing.
    "auto_complete": true,

    // The maximum file size where auto complete will be automatically triggered.
    "auto_complete_size_limit": 4194304,

    // The delay, in ms, before the auto complete window is shown after typing
    "auto_complete_delay": 50,

    // Controls what scopes auto complete will be triggered in
    "auto_complete_selector": "meta.tag - punctuation.definition.tag.begin, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc",

    // Additional situations to trigger auto complete
    "auto_complete_triggers": [ {"selector": "text.html", "characters": "<"} ],

    "auto_complete_commit_on_tab": false,

    "auto_complete_with_fields": false,

    "auto_complete_cycle": false,

    // Automatically close HTML and XML tags when </ is entered.
    "auto_close_tags": true,

    "shift_tab_unindent": false,

    "copy_with_empty_selection": true,

    "find_selected_text": true,

    "auto_find_in_selection": false,

    "drag_text": true,

    //
    // User Interface Settings
    //


    "theme": "Default.sublime-theme",

    // Set to 0 to disable smooth scrolling. Set to a value between 0 and 1 to
    // scroll slower, or set to larger than 1 to scroll faster
    "scroll_speed": 1.0,

    // Controls side bar animation when expanding or collapsing folders
    "tree_animation_enabled": true,

    // Controls animation throughout the application
    "animation_enabled": true,

    // Makes tabs with modified files more visible
    "highlight_modified_tabs": false,

    "show_tab_close_buttons": true,

    // Show folders in the side bar in bold
    "bold_folder_labels": false,

    // Draw divider lines between sections of the UI when using the Adaptive theme
    "adaptive_dividers": true,

    // Mac only. Valid values are true, false, and "auto". Auto will enable
    "gpu_window_buffer": "auto",

    // Valid values are "system", "enabled" and "disabled"
    "overlay_scroll_bars": "system",

    // Allows tabs to scroll left and right, instead of simply shrinking
    "enable_tab_scrolling": true,

    // Display file encoding in the status bar
    "show_encoding": false,

    // Display line endings in the status bar
    "show_line_endings": false,

    // Magnifies the entire user interface. Sublime Text must be restarted for
    // this to take effect.
    "ui_scale": 1.0,

    // Linux only. Sets the app DPI scale - a decimal number such as 1.0, 1.5,
    // 2.0, etc. A value of 0 auto-detects the DPI scale. Sublime Text must be
    // restarted for this to take effect.
    "dpi_scale": 0,

    //
    // Application Behavior Settings
    //

    // Exiting the application with hot_exit enabled will cause it to close
    // immediately without prompting. Unsaved modifications and open files will
    // be preserved and restored when next starting.
    //
    // Closing a window with an associated project will also close the window
    // without prompting, preserving unsaved changes in the workspace file
    // alongside the project.
    "hot_exit": true,

    // remember_full_screen will allow Sublime Text to start in full screen
    // mode if it was exited in full screen mode. When set to false, Sublime
    // Text will never start in full screen mode.
    "remember_full_screen": false,

    // Mac only. If the user's default shell should be invoked to obtain the
    // user's customized environment variables. May be a boolean, or a string
    // of the path the shell to invoke. Sublime Text must be restarted for this
    // to take effect.
    "shell_environment": true,

    // Always prompt before reloading a file, even if the file hasn't been
    // modified. The default behavior is to automatically reload a file if it
    // hasn't been edited. If a file has unsaved changes, a prompt will always
    // be shown.
    "always_prompt_for_file_reload": false,

    // Mac only: When files are opened from finder, or by dragging onto the
    // dock icon, this controls if a new window is created or not.
    "open_files_in_new_window": true,

    // Mac only: This controls if an empty window is created at startup or not.
    "create_window_at_startup": true,

    // Mac only: Show recent files on the Touch Bar.
    "show_navigation_bar": true,

    // Set to true to close windows as soon as the last file is closed, unless
    // there's a folder open within the window.
    // On Mac, this value is overridden in the platform specific settings, so
    // you'll need to place this line in your user settings to override it.
    "close_windows_when_empty": false,

    // Show the full path to files in the title bar.
    // On Mac, this value is overridden in the platform specific settings, so
    // you'll need to place this line in your user settings to override it.
    "show_full_path": true,

    // Shows the Build Results panel when building. If set to false, the Build
    // Results can be shown via the Tools/Build Results menu.
    "show_panel_on_build": true,

    // Shows build errors just under the line on which they occur.
    "show_errors_inline": true,

    // Preview file contents when clicking on a file in the side bar. Double
    // clicking or editing the preview will open the file and assign it a tab.
    "preview_on_click": true,

    // folder_exclude_patterns and file_exclude_patterns control which files
    // are listed in folders on the side bar. These can also be set on a per-
    // project basis.
    "folder_exclude_patterns": [".svn", ".git", ".hg", "CVS"],
    "file_exclude_patterns": ["*.pyc", "*.pyo", "*.exe", "*.dll", "*.obj","*.o", "*.a", "*.lib", "*.so", "*.dylib", "*.ncb", "*.sdf", "*.suo", "*.pdb", "*.idb", ".DS_Store", "*.class", "*.psd", "*.db", "*.sublime-workspace"],
    // These files will still show up in the side bar, but won't be included in
    // Goto Anything or Find in Files
    "binary_file_patterns": ["*.jpg", "*.jpeg", "*.png", "*.gif", "*.ttf", "*.tga", "*.dds", "*.ico", "*.eot", "*.pdf", "*.swf", "*.jar", "*.zip"],

    // File indexing parses all files in the side bar, and builds an index of
    // their symbols. This is required for Goto Definition to work.
    "index_files": true,

    // Set the number threads to use for indexing. A value of 0 will make
    // Sublime Text guess based on the number of cores. Use the index_files
    // setting to disable all workers.
    "index_workers": 0,

    // index_exclude_patterns indicate which files won't be indexed.
    "index_exclude_patterns": ["*.log"],

    // List any packages to ignore here. When removing entries from this list,
    // a restart may be required if the package contains plugins.
    "ignored_packages": ["Vintage"]
}


```



**User**

```
{
	"added_words":
	[
		"maxima",
		"binarize",
		"Northgate",
		"metallographic",
		"microscopist",
		"micrographs",
		"micrograph",
		"nanoparticles",
		"ultrathin",
		"chemometrics"
	],
	"color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",
	"dictionary": "Packages/Language - English/en_US.dic",
	"draw_white_space": "all",
	"font_face": "Lucida Console",
	"font_size": 12,
	"hot_exit": true,
	"ignored_packages":
	[
		"Vintage",
		"Markdown"
	],
	"ignored_words":
	[
		"Lispix",
		"hexane",
		"nanoparticles",
		"toolbar",
		"ultrathin"
	],
	"numix_folder_icons": true,
	"remember_open_files": true,
	"rulers":
	[
		72
	],
	"tab_size": 2,
	"tabs_large": true,
	"theme": "Numix Dark.sublime-theme",
	"translate_tabs_to_spaces": false
}
```
On Windows, this is in file `Preferences.sublime-settings` in:

```
C:\Users\jrminter\AppData\Roaming\Sublime Text 3\Packages\User
```

On Mac this is in:

```
"/Users/jrminter/Library/Application Support/Sublime Text 3/Packages/User"
```
## Packages

Package Control does not seem to work.
Available packages are cataloged on
[packagecontrol.io](https://packagecontrol.io/).

**Note**: unzip manual packages in the `User` folder shown above...



# Using Sublime Text 3 with git

## Windows

From [Stack Overflow](http://stackoverflow.com/questions/8951275/git-config-core-editor-how-to-make-sublime-text-the-default-editor-for-git-on)

> Sublime Text 3 (Build 3065)

> Sublime Text 3 (Build 3065) added the subl.exe command line helper. Use `subl.exe -h` for the options available to you. I have `"hot_exit": true` and `"remember_open_files": true` set in my Sublime Text user settings. I have found the following to git config to work well for me.

```
git config --global core.editor "'c:/program files/sublime text 3/subl.exe' -w"
```

> With this git config the a new tab is opened in my editor. I edit my commit message, save the tab and close it (`CTRL+w`). Git will wait until the tab is closed to continue its work.

## MacOSX

See the [Git Hub](https://help.github.com/articles/associating-text-editors-with-git/) page

Need to test the Windows approach. Need to see where subl is, perhaps symlink to `/usr/local/bin`

[Back to Index](../README.html)
