---
title: "Ubuntu Tips"
author: "J. R. Minter"
date: "Started: 2014-01-17, Last modified: 2019-04-08"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# make this an external chunk that can be included in any file
library(knitr)
options(width = 72)
opts_chunk$set(message = F, error = F, warning = F, comment = NA, fig.align = 'center', dpi = 100, tidy = F, cache.path = '.cache/', fig.path = 'figure/')

options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
knit_hooks$set(plot = knitr:::hook_plot_html)
```


[Back to Index](../README.html)

# Choose a kernel on boot
hold down ``left shift`` key on boot to get to grub menu


# How to upgrade kernels from the command line

From [Ask Ubuntu](http://askubuntu.com/questions/221/how-to-force-installation-of-kernel-updates-when-using-apt-get-upgrade)


After a little research, what you probably want to use is:

```
aptitude safe-upgrade
```
which does install new kernels. You should probably prefer
``aptitude`` in general to ``apt-get`` anyway, unless
you specifically need something in ``apt-get``.

# Remove a user

This will remove a user and their home directory from the command line:

```
sudo deluser --remove-home username
```


# Managing software - From Distrowatch

## Install/remove

```
Install new software from repository......... apt-get install pkg
Install new software from file .............. dpkg -i pkg  
Update existing software .................... apt-get install pkg
Remove unwanted software .................... apt-get remove pkg
```

## Updating the system

```
Update package list .......................... apt-get update
.............................................. aptitude update	
Update system ................................ apt-get upgrade
                .............................. aptitude safe-upgrade
```

## Searching for packages

```
Search by package name ........................ apt-cache search pkg
Search by pattern ............................. apt-cache search pattern
Search by file name ........................... apt-file search path
List pkg contents ............................. x86_64-linux-gnu.confackageName
List installed package ........................ dpkg -l
```

## Configuring access to software repositories

```
List repositories .............................. cat /etc/apt/sources.list
Add repository  ................................ (edit /etc/apt/sources.list)
Remove repository .............................. (edit /etc/apt/sources.list)
```

# Find and remove old kernels
from [liberiangeek.net](http://www.liberiangeek.net/2011/11/remove-old-kernels-in-ubuntu-11-10-oneiric-ocelot/)

### Find the current kernel. Don’t remove this one!!!
```
uname -r
```

### List all installed kernels
```
dpkg --list | grep linux-image
```

Finally, run the commands below to remove the kernel(s) you selected.
```
sudo apt-get purge linux-image-x.x.x.x-generic
```

### Update grub2 when done
```
sudo update-grub2
```

# Quick mount windows share
From [here](https://help.ubuntu.com/community/Samba/SambaClientGuide)

## restart when required
```
sudo service smbd restart
sudo service nmbd restart
```

## see what is going on with SAMBA
```
smbclient -L //marathon
smbclient -L //fortress
smbclient //fortress/data -U jrminter
```

## get it where the computer can find the server
```
sudo apt-get install winbind
sudo mousepad /etc/nsswitch.conf
```
change
```
hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4
```
to
```
hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4 wins
```
***Note*** putting wins earlier broke Google Chrome...

## Connecting using CIFS
CIFS is included in the smbfs package and is a replacement for smbfs.
[Reference](http://linux-cifs.samba.org/)

## Install smbfs
```
sudo apt-get install smbfs winbind
```

## Allow non-root users to mount SMB shares

You may either allow the group "users" to mount SMB shares, or add a group, samba, and add users you wish to allow to mount SMB shares to the samba group.

```
sudo adduser jrminter samba
sudo groupadd samba
```
then
```
sudo visudo
```
In the "group" section add your group you wish to allow to mount SMB shares
Add a line  in the "group" section :
```
# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL
%samba   ALL=(ALL) /bin/mount,/bin/umount,/sbin/mount.cifs,/sbin/umount.cifs
```

Change ``%samba`` to ``%users`` if you wish to allow members of the users group to mount SMB shares.

## create a mount point
```
sudo mkdir /media/fortress
sudo mkdir /media/fortress/data
```

```
sudo mount -t cifs //fortress/data /media/fortress/data -o username=samb_user,noexec
```

**Note:** ``samba_user`` = the user name on the samba server (may be different from your log-in name on the client). The "noexec" option prevents executable scripts running from the SMB share. You will be asked for BOTH your sudo and then your samba_user password.

## To umount
```
sudo umount /media/fortress/data
```

**Note:** Google Chrome preferences are in ~/.config/google-chrome

[Back to Index](../README.html)
