Oxford AZtec Tips
===========================================================

[Back to Index](../README.html)

### Preferred colors for maps

It helps to have consistent colors for maps. *N.B.* there are issues with R/G colorblindness here....
```
C-K    0 red
O-K  120 green
Cu-L 180 cyan
P-K       ??
Pd-L  60 yellow
Ag-L  30 brown

```



### Controlling the export of maps
1. For the map you want, right click and select ``Details``.
2. Note the ``Resolution (Width)`` (e.g. 1024 px) and the ``Image Width`` (e.g. 193 um). You may want to note the ``Magnification`` as well...
3. Again for the map you want, right click and select ``Export >> Settings``. Leave ``Keep Aspect Ratio``checked and turn off what you don't want. Set to the resolution you want (i.e. 1024) and then press ``Save As...``


### Setting your own logo

The Oxford logo is in a file ``logo.png`` in ``C:\Program Files\Oxford Instruments NanoAnalysis\AZtec\Reports``. It is ``150x71`` pixels. design a replacement with the same aspect ratio and rename the old one to ``logo-old.png``


[Back to Index](../README.html)
