---
title: "Bluetooth Tips"
author: "John Minter"
date: "2021-12-17  modified  2021-01-22"
output:
  word_document:
    toc: no
    toc_depth: '3'
  html_document:
    toc: no
    toc_depth: '3'
    df_print: paged
  pdf_document:
    number_sections: yes
    toc: no
    toc_depth: 3
editor_options:
  markdown:
    wrap: 72
---
\fontsize{18}{19.2}
\fontseries{r}
\selectfont

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
[Back to Index](../README.html)

# Connecting a Bluetooth Mouse on MacOS

1. Turn the mouse on, and make sure it's within range of your Mac.

2. Click the Apple icon in the top-left corner of the screen.

3. Select "System Preferences..."

4. Click the "Bluetooth" icon.

5. If it's not already on, select "Turn Bluetooth On."

6. Wait for your mouse to appear on the list.

# Pair a Bluetooth device on Windows 11

Before you start, make sure that your Windows 11 PC supports Bluetooth. For more info on how to check, see Fix Bluetooth problems in Windows. If you need help adding a device without Bluetooth capabilities, see Add a device to a Windows PC.

## Turn on Bluetooth

After you've checked that your Windows 11 PC supports Bluetooth, you'll need to turn it on. Here's how:

- In Settings    
Select Start > Settings > Bluetooth & devices, and then turn on Bluetooth.

- In quick settings    
To find the quick setting for Bluetooth, select the Network icon next to the time and date on the right side of your taskbar. Select Bluetooth to turn it on. If it's turned on without any Bluetooth devices connected, it might appear as Not connected.

If you don't see Bluetooth in quick settings, you might need to add it. For more info, see Change notifications and quick settings in Windows 11.

## To pair a Bluetooth device

1. Turn on your Bluetooth device and make it discoverable. The way you make it discoverable depends on the device. Check the device or visit the manufacturer's website to learn how.

2. On your PC, select `Start > Settings > Bluetooth & devices > Add device > Bluetooth`.

3. Choose the Bluetooth device, follow additional instructions if they appear, then select `Done`.

Your Bluetooth device and PC will usually automatically connect anytime the two devices are in range of each other with Bluetooth turned on.

## To pair a Bluetooth printer or scanner

1. Turn on your Bluetooth printer or scanner and make it discoverable. The way you make it discoverable depends on the device. Check the device or visit the manufacturer's website to learn how.

2. Select `Start > Settings > Bluetooth & devices > Printers & scanners > Add device`. Wait for it to find nearby printers, choose the one you want to use, then select Add device.

If you’re having problems installing your printer or scanner, see either Fix printer problems or Install and use a scanner in Windows.


# Using Blutooth on Bose speaker

## Connecting

1. On Phone, go into "Settings" (a grey gear)

2. 3rd from left is **Bluetooth**. Click on **Bluetooth**.

3. Look for "Bose Revolve Sound" on the list.

4. If it is **not connected**, press and hold the Bluetooth button on Bose. It 
should connect.

## Disconnecting

1. Go to **Settings**

2. Look for **Bluetooth**

3. Click on circular **i** (for information) for Bose

4. Click **disconnect**

# Anker Bluetooth Headphones

## Charging 

1. Fully dry off the USB port before charging

2. Use the provided USB-C charging cable and charger to prevent damage.

3. **Do Not** power on your headphones **while charging**.

## Bluetooth pairing

1. When powered off, press and holdthe power button for 5 sec LED stops.

2. Select "Soundcore Life Q30" on your Bluetooth list to connect.

3. Light notifications

   - Flashing red once every 60 sec : Low battery
   
   - Steady red: Being charged
   
   - light odd: Fully charged
   
   - flashing red: Bluetooth Pairing
   
4. Powering On/Off - Press and hold for 3 sec to power off

5. You can connect to two devices

   - First is with Bluetooth
   
   - Second press the button twice to pair with a second device.
   
   - Steady blue means Bluetooth connected.
   
   
6. Bluetooth for music

   - play/pause press the button
   
   - next track (+)  Press and hold 1 sec
   
   - Previous track  Press and hold 1 sec
   
   - Volume up/down Press
   
   - Answer / end call - press
   
   - Activate Siri press and hold 1 sec
   
7. Noise cancellation

   To reduce ambient noise, turn on the active noise cancellation mode    
   by pressing the **NC button** press the **NC button** again to turn off
   

8. AuX mode

   Play audio on an external device by plugging in a 3.5 mm AUX cable.
  
9. Reset

   You might need to reset your headphone if you have problems.
   Press and hold the power button and volume up button simultaneously
   for 5 sec until the LED indicator flashes blue and red alternately
   twice.


[Back to Index](../README.html)
