---
title: "iOS Tips"
author: "J. R. Minter"
date: "Started: 2014-09-07, Last modified: 2021-07-20"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

[Back to Index](../README.html)

# Changing Brightness on ios12

Open

```
Settings > Display and Brightness 
```

Then manually increase brightness **with the slider**.

# Music settings for iPhone12

Leave your music playlist on the `Library` tab.

# Stuck in Dark Mode

Our whole family worked to find this answer:

Happily, the [Apple Discussion](https://discussions.apple.com/thread/250656701)
provided a fix: **triple-click** the **side-button** to switch the `old`
dark mode **off**. Tim thought I might have set up **invert colors**.
I do not recall doing so. I will watch for it...

I think I will need to push the brightness to use the iPhone-12
in the mount in my 2012 Civic.  First world problems...

# How to invert colors

I want to make sure I need this prior to trying...

From [here](https://mcmw.abilitynet.org.uk/invert-colours-iphoneipadipod-touch-ios-12)


1. Open the 'Accessibility Settings': Settings > General > Accessibility.
2. Under the 'Vision' section, tap on 'Display Accommodations'.
3. Tap on 'Invert Colours'.
4. Tap on the toggle switch for the 'Invert Colours' mode you would like to use:


# Turn off emojis

I hate the emoji keyboard. I hit it easily with my fat fingers. I turned 
it off!

From [mashable.com](https://mashable.com/article/how-to-hide-memoji-imessage-keyboard/)

1. Open iMessage.
2. Click into a random conversation thread.
3. Swipe on the app icons until you see the bubble with three dots and then tap it.
4. Select "Edit"
5. Deselect "Memoji" from both the "FAVORITES" and the "MORE APPS" section.
6. Tap "Done"



# Turn off the Facebook auto-play video feature?

From [moneysavingexpert.com](http://www.moneysavingexpert.com/news/protect/2014/09/facebook-app-user-beware-big-bills-as-videos-automatically-play)

Go to your phone's settings

```
Settings > Facebook > Settings > Select 'Auto-play only on Wi-Fi', or 'Off'.
```

[Back to Index](../README.html)
