---
title: "Badger Film"
author: "J. R. Minter"
date: "Started 2020-08-05, Last modified: 2021-06-06"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```



[Back to Index](../README.html)

# Introduction

`BadgerFilm` is a program developed by Aurelien Moi and John Fournelle
to do thin film quantification from X-ray EDS and Electron Microprobe Spectra
from thin films on a substrate.

It is a successor to the `GMRFilm` package by Richard Waldo at General Motors
in the 1980s.

`BadgerFilm` is Open Source and is written in Visual Basic and hosted on
[github](https://github.com/Aurelien354/BadgerFilm). The developers note: 

> BadgeFilm requires a Windows OS (or emulator) and the
> .NET Framework 4.5.2 or higher version.

There is a `Quick Start` guide
[here](https://github.com/Aurelien354/BadgerFilm/blob/master/BadgerFilm%20v1.2%20quickstart.docx).

I have  local archives in the "Documentation" sub directory.

**2021-06-06**

Note Aurelien Moy posted this on the Probe Software Forum:

> John: Yes, you can import STRATAGem input files generated by Probe for EPMA. BadgerFilm can import multiple files at once and then average the loaded experimental k-ratios, giving a variance on the input data. This assumes that all the imported files are similar (describing the same sample with the same experimental conditions and measured X-ray lines).
Comparing the perditions of BadgerFilm and STRATAGem to experimental data can be interesting. I will try to gather some materials and start a new topic.

> Ansaheric: BadgerFilm can return the area density of the layers (in µg/cm²) but you will need either the density or the thickness, to convert this value to a thickness or a density, respectively. You cannot determine both the density and the thickness with this method.





[Back to Index](../README.html)
