---
title: "John Minter's Debian Tips"
author: "J. R. Minter"
date: "Started: 2019-02-28, Last modified: 2019-03-24"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

[Back to Index](../README.html)

# Introduction

## Key tips

**Finding items**:

1. Click **Activities** in the upper left corner.

2. A **Search** dialog opens at the top center of the screen.

3. Type what you want - like "_tips.html" for a link to my **Tips** html index...

 

## Key Debian Sites

- [**Debian**](https://www.debian.org/) is a free Linux operating system that
is related to Ubuntu. Most common hardware is supported.

- Get it
[**here**](https://www.debian.org/distrib/).

- Documentation is
[**here**](https://www.debian.org/doc/).

- Installation guides are
[**here**](https://www.debian.org/releases/stable/installmanual).

## Other Useful sites:

- Raphael Hertzog's
[Mastering Debian](https://raphaelhertzog.com/mastering-debian/).

- HowTooForge
[debian-minimal-server](https://www.howtoforge.com/tutorial/debian-minimal-server/).

- TogaWare
[Linux Survivor](https://www.togaware.com/linux/survivor/).

- securitynewspaper.com
[critical vulnerability](https://www.securitynewspaper.com/2019/01/24/critical-vulnerability-on-linux-apt-get-in-debian-ubuntu-and-mint-distros/).

# Mirrors

Mirror status: [here](https://mirror-master.debian.org/status/mirror-status.html)

I like Columbia best - much faster than RIT.
The two choices I have in
`/etc/apt/sources.list` are:

```
# deb http://mirror.rit.edu/debian/ stretch main
# deb-src http://mirror.rit.edu/debian/ stretch main

# Columbia does not seem to be updating 2019-03-02
deb http://mirror.cc.columbia.edu/debian/ stretch main
deb-src http://mirror.cc.columbia.edu/debian/ stretch main

# Binghamton updated as of 2019-03-02
deb http://debian.cs.binghamton.edu/debian/ stretch main
deb-src http://debian.cs.binghamton.edu/debian/ stretch main

```
# System Kung Fu

## Set the default web browser

```
xdg-settings set default-web-browser chromium.desktop
```

## Stop auto suspend

```
sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
```

To re-activate

```
sudo systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target
```


# Updates

## From the command line

See `man apt-get`.

```
apt-get update
apt-get upgrade
```

To override mirror warnings

```
sudo apt-get -o Acquire::Check-Valid-Until=false update
sudo apt-get -o Acquire::Check-Valid-Until=false upgrade
```

To update the distribution

```
apt-get dist-upgrade
```

# Admin tasks

## Removing old kernels

From
[tecmint.com](https://www.tecmint.com/remove-old-kernel-in-debian-and-ubuntu/).

1. Check the current kernel:

    ```
    jrminter@DebianSid:~$ uname -sr
    Linux 4.19.0-3-amd64
    ```

2. List all kernels:

    ```
    jrminter@DebianSid:~$ dpkg -l | grep linux-image | awk '{print$2}'
    linux-image-4.19.0-3-amd64
    linux-image-4.9.0-8-amd64
    linux-image-amd64
    ```
3. Delete the obsolete kernels & update grub:

    ```
    jrminter@DebianSid:~$ sudo apt remove --purge linux-image-4.9.0-8-amd64
    jrminter@DebianSid:~$ sudo apt remove --purge linux-image-amd64
    jrminter@DebianSid:~$ sudo update-grub2
    ```

4. Reboot the system:

    ```
    jrminter@DebianSid:~$ sudo reboot
    ```

## Creating GPG keys

See [https://keyring.debian.org](https://keyring.debian.org/creating-key.html)


## Add a user to sudo

### The easy way

Complements of [linuxpanda](https://linuxpanda.wordpress.com/2016/12/31/things-to-do-after-installing-debian-stretch/)

```
apt-get install sudo
usermod -a -G sudo <username>
```

Replace `<username>` with your username to which you want to grant sudo access.

Now logout & login to get sudo access to those users.


### The hard way...

From the command line:

1. Go to home directory by running command `cd $HOME`

2. Type `su -`. It will ask you for password. Type the
root user password. You will then be the root user.

3. Type `visudo`

4. Using the editor, add

   ```
   username (tab) ALL=(ALL) (tab) ALL
   ```

   to the sudoers file. Save (`write out`) and `exit`.

This was adapted from the answer by by Shrikant Khawale on 
[stackexchange](https://unix.stackexchange.com/questions/179954/username-is-not-in-the-sudoers-file-this-incident-will-be-reported).

# Adding miniconda

1. Download the latest [installer](https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh).

2. Make the shell script executable (`chmod +x *.sh`).

3. Install to `/home/jrminter/Apps/miniconda3`.

4. Answer `yes` to initialize in `.bashrc`.

5. Open a new terminal. Add the packages using `conda` from the
command line:
    
    ```
    conda install numpy scipy matplotlib seaborn jupyter spyder
    conda install sqlite pandas xlwt scikit-image
    conda config --add channels conda-forge
    conda install mahotas
    conda install sympy
    conda install cython
    pip install iversions
    
    ```

# Install Sublime Text 3

Install Sublime Text 3 via the official apt repository:

0. Add the required package

    ```
    sudo apt install apt-transport-https
    ```

1. Open terminal via Ctrl+Alt+T or by searching for `Terminal`
from desktop app launcher. When it opens, run the command to install
the key:

    ```
    wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -sublimetext-apt-key
    ```

2. Then add the apt repository via the command:

    ```
    echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
    ```

3. Finally check updates and install sublime-text via your system package manager:

    ```
    sudo apt-get update
    sudo apt-get install sublime-text
    ```
    
    Once installed, launch it from your desktop app launcher and enter your
    license.


# Cleanup

1. Remove unneeded config files

    From: [raphaelhertzog.com](https://raphaelhertzog.com/2011/01/31/debian-cleanup-tip-1-get-rid-of-useless-configuration-files/).

    ```
    sudo apt-get install aptitude
    sudo aptitude purge ?config-files
    
    ```

[Back to Index](../README.html)
