---
title: "SEM Tips"
author: "J. R. Minter"
date: "Started: 2015-10-07, Last modified: 2018-10-11"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---
[Back to Index](../README.html)

# Key materials from Ted Pella

Ted Pella is typically our first choice for EM supplies. These
are some of our favorites:

```{r, pellaTable, echo=FALSE, results='asis'}
library(pander)
fi <- './dat/Pella-products.csv'
df <- read.csv(fi, header = TRUE, as.is=TRUE)
row.names(df) <- NULL
set.alignment('left', row.names ='right')
pander(df, split.cells = 25, split.table = Inf)

```

Note: the solvent for Pella's colloidal is Dowanol PM. Here is Dow's
[Data sheet](./dat/Dowanol-PM.pdf).


# Cleaning SEM stubs

[Chris Holp](holpc@firstenergycorp.com) wrote:

> Working essentially as a one person SEM lab, long ago I came to the conclusion that unless the cleaning was very quick and easy, it was more practical to simply recycle the small stubs. I could not justify much time to clean them. I do think the larger items are a different consideration, however. My metallurgical mount holders, vices, multi-stub holders, etc., are pricey and well worth an effort to keep them looking good, both for myself and clients. For these, I remove paints and tape residues ultrasonically with an organic solvent. Once that is done, I've had decent success by ultrasonically cleaning them in a warm water solution with Alconox powder. This removes sputtered materials and other residuals nicely. The holders come out looking great again with no signs of etching or attack on the aluminum. I've never tried any of the other Alconox products for this, however. (I have no stake in Alconox.)

Note [Gert ten Brink](g.h.ten.brink@rug.nl)'s reply

> I do not even bother to clean them. They are consumables. Mind you, if you don't clean the old ones properly you make your SEM/vacuum dirty. If you buy them via the internet for a 100 pieces they cost 23.- euro's. The time spent cleaning them cost more.




# Handling problem specimens that charge

## Comments from Steve Chapman 2015-10-07 (protrain@emcourses.com)

These comments came from the microscopy listserver in response to a question about imaging a problematic leather specimen.

> Sounds as if you are trying, but if the charge is worse with dropping to 5 kV
that tells me you have lost the BSE contribution, this will be a big problem
whist using a TTL system. The converted BSE provide SE, but because they are
derived from BSE they do not carry so much charge information

> The approach to a problem specimen should be as follows:

> 1. Use the smallest possible piece of material, fixed to the stub with
a good quality conducting media.
> 2. Start at the lowest kV that you are able to work with, and a small
spot size; all aimed at not damaging or charging the specimen.  If you use a
TTL system go to the standard detector in the lower chamber, with about 7 mm
working distance.  You need a contribution of converted BSE (less charge)
which you are unlikely to have with TTL detection. If the signal is too low,
slightly increase the spot size.
> 3. If the specimen is not giving you a problem other than resolution,
increase the magnification using a fast scan if possible, to reduce the
intensity of beam on a particular area.
> 4. Having increased the magnification, as resolution is the problem,
increase the kV slightly (e.g. if you were using 1kV go to 1.5kV).
> 5. As long as there is no charge continue stepping up the kV until you
are happy with the result or the specimen charges.  If you charge the
specimen take it to air to discharge it, and go back to an earlier kV.
Slight charge may be reduced by reducing the spot size slightly.
> 6. If resolution is still the problem, try moving the specimen closer
to the final lens by a few mm, not too close as you will lose the very
valuable converted BSE.
> 7. Still a resolution problem, if you have a TTL system try 10 mm WD
then in steps down to 5 mm WD with this system, and see if you are able to
obtain a satisfactory result (with many TTL systems between 7 mm and 5 mm
works).
> 8. All of the time you are looking for a mix of kV, spot size, and WD
that provides the best mix of signal and therefore performance.

## Comments from Gary Brown (microscopy.gmb@gmail.com)

> I agree with what Steve had to say and have some additional comments.

> - A sample of a square centimeter or so is probably not too large.
> The conductive media should make a continuous electrical connection
> between the bare metal stub and the upper surface and continuing onto
> the upper surface of the sample.  I often use Leit C carbon adhesive
> from my friendly microscopy supply house because it combines
> electrical conductivity with excellent mechanical strength that
> materials like colloidal graphite (DAG) and silver paint don't have.
> Silver paint can also be problematic in EDS analysis.
> 
> -  The power that field emission SEM offers is incredibly bright
> source combined with a stable low voltage beam.  Secondary electron
> imaging (SEI) at low voltage provides the best topographical analysis
> of surface roughness.  Charge control in SEI is achieved by balancing
> the number of incident electrons entering the sample and electrons
> leaving as secondary and backscattered electrons.  I highly recommend
> the book "Scanning Electron Microscopy and X-ray Microanalysis", 3rd
> Edition by Goldstein et al., Springer, 2013.  The chapter on
> Procedures for Elimination of Charging in Nonconducting Specimens
> should be very helpful.
> 
> -  My 25 years of experience in low voltage, field emission SEM of
> polymers leads me to believe that some of the imaging problems
> experienced with leather may be similar to those observed in polymers.
> Both are insulators and consist of low atomic weight elements.  Like
> Steve, I suggest you start at around 1 kV accelerating voltage.  Use
> the spot size that the service engineers use to check your spatial
> resolution at 1 kV: this spot size is a good place to start because
> the manufacturer knows it gives an excellence balance of resolution
> and signal-to-noise.
> 
> -  For best results, I suggest you work with an uncoated sample.  You
> might start with a coated sample then move to the bare, uncoated
> sample.  Gold and gold-palladium coatings will obscure possibly
> important surface information.
> 
> -  Faster scan rates produce less charging than longer scan rates.
> If a single scan allows you to control charging but is somewhat noisy,
> average several scans recorded using shorter scan rates.  Do a few
> quick tests on fresh areas of the sample to see how long a scan rate
> you can use without producing charging.  Be aware that your default
> image acquisition scan rate may be much longer than the ideal scan
> rate for your sample. If this happens, record your images at the
> preferred rate.
> 
> -  Fortunately, sub-micrometer surface texture and porosity (as I
would expect to see in collagen-based leather surfaces) dissipate
charging thus making imaging easier.

# Voltage contrast

A tip from Valery Ray on the microcopy Lis5erver 2012-06-25

> There are two tricks that I have for stubborn passive voltage
> contrast samples. One is for overall floating structures where
> whole chain gets dark in a FIB - use black "Micron" 005 pen
> from Sakura brand to ground one end of the chain - these pens
> have fairly conductive trace with width about 200um and are
> great for drawing long grounding lines under microscope - final
> connection to chain is by FIB metal.
> 
> Another trick is for chains with "soft" disconnect - use
> "HUGE" beam currents, up to nA range, to get enough voltage
> drop to see location of the defect.
> 
> If you have a FIB with vented chamber (a-la FIB200 and all the
> later variants) then with small hardware hack and a bit of sample
> prep effort you can start doing active voltage contrast in about
> an hour.
> 
> Disconnect stage current cable from the sample holder (it is
> fairly useless for the originally-intended purpose anyway)
> and hard-ground sample holder to the stage. Use the disconnected
> cable and its feed-through to bring in voltage from regulated
> DC power supply (+/- 10V range) - your FIB is ready. For the
> sample preparation - attach short piece of a bonding wire to
> the piece of wire-wrap wire, attach wire-wrap wire to the sample
> by a drop of epoxy, bend bonding wire close to your
> chain in question, trim end of the bonding wire with ophthalmic
> scalpel, and fix it with drop of Ted Pelllas colloidal
> silver - all this takes about 30min. under inspection microscope.
> Almost done: load sample into your FIB, attache wire-wrap wire
> to the and of the freed stage-current
> cable, pump the chamber, make final connection of the chain to the
> silver dot at the end of the bonding wire, and apply voltage from the
> power supply :)
> 
> If for any reason none of the above works - any lab that has in-situ
> manipulator on the FIB should be able to do active VC for... EAG in
> Sunnyvale, or maybe even one of Universities next door?
> 
> Cheers :)
> Valery
> 
> Valery Ray \
> PBS&T, MEO Engineering Co., Inc. \
> 290 Broadway, Suite 298 \
> Methuen, MA 01844 USA \
> Phone: +1-978-296-5063 - leave a message with call-back number \
> US Mobile: +1-978-305-0479 \
> Skype: pbstmeo \
> E-mail: vray@partbeamsystech.com \

# Cryo-TEM

> From: Hands-Portman, Ian <I.J.Portman@warwick.ac.uk> \
> Date: Mon, Feb 4, 2013 at 3:43 AM \
> Subject: [3dem] Quality of Ethane \
> To: "3dem@ncmir.ucsd.edu" <3dem@ncmir.ucsd.edu> \
>  \
> We used high purity ethane for years, it does freeze quite quickly but
> it is easy enough to thaw with a touch from a screwdriver blade or a
> quick blast of fresh ethane. We never had contamination issues with it
> until the tank was almost empty but it was expensive to buy.
>
> When I heard about ethane/propane mixed I switched over to that -- for
> ease of use I buy it ready mixed - I'm not allowed to store then tanks
> in the lab so only want to have to move one around. It's considerably
> cheaper than plain ethane, it gels slightly but never sets - I
> wouldn't go back to using ethane.
> 
> Ian Hands-Portman \
> Imaging Suite Manager \
> School of Life Sciences \
> University of Warwick \
> Gibbet Hill Road \
> Coventry \
> CV47AL




[Back to Index](../README.html)