---
title: "R Package Tips"
author: "J. R. Minter"
date: "Started: 2015-05-08, Last modified: 2017-01-28"
output:
  knitr:::html_vignette:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
---

[Back to Index](../README.html)

# Overview

One of the best ways to make analyses reproducible is to not 
repeatedly write the same code. Instead, our goal is to assemble
re-usable functions into R packages under version control and
containing unit tests. This document contains my favorite tips
assembled from various sites on the web.

# Key References

[Jeff Leek's group practices](https://github.com/jtleek/rpackages)     
[Hadley Wikham's site](http://r-pkgs.had.co.nz/)     
[Hadley book on github](https://github.com/hadley/r-pkgs/)     
[CRAN keywords vignette](http://cran.r-project.org/web/packages/roxygen2/vignettes/rdkeywords.html)    
[CRAN roxygen process](http://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html)    

# Key tips

## Building a package with Rmarkdown vignettes

1. Run `devtools::build_vignettes()`
2. Restart R
3. Check by running:

```
library(pkgName)
browseVignettes("pkgName")
```


# Set up a new package `myPkg` that we plan to host on github

On my local computer:

```
setwd("~/git/")
library("devtools")
library("roxygen2")
library("knitr")
create("myPkg")
```

Then from the shell:

```
cd ~/git/myPkg
git init
```

Create a new repository on github. Then push my local copy to
github from the shell:

```
git remote add origin git@github.com:jrminter/myPkg.git
git add *
git commit -m 'initial commit'
git push -u origin master
```

# The cursed "no visible binding for global variable" error...

Using LazyLoaded data often gives this error. The key is to explicitly use the variable from the package namespace, eg:

```
ret <- func(myPkg::var, other)
```

# The importance of vignettes

> If you’re thinking without writing, you only think you’re thinking. -- Leslie Lamport

Vignettes are preferred to examples in documentation. These are much less painful to write using `rmarkdown` than `LaTeX`!

To create the first vignette, run:

```
devtools::use_vignette("my-vignette")
```

This will:

1. Create a `vignettes/` directory.
2. Add the necessary dependencies to DESCRIPTION.
3. Draft a vignette, `vignettes/my-vignette.Rmd`.



[Back to Index](../README.html)