---
title: "Data Science on Ubuntu Linux 64"
author: "John Minter"
date: "Started: 2019-02-16, Last modified: 2019-02-16,"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# make this an external chunk that can be included in any file
library(knitr)
library(ggplot2)
options(width = 72)
opts_chunk$set(message = F, error = F, warning = F, comment = NA,
               fig.align = 'center', dpi = 100, tidy = F,
               cache.path = '.cache/', fig.path = 'figure/')

options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
knit_hooks$set(plot = knitr:::hook_plot_html)
```

[Back to Index](../README.html)

# Introduction

These instructions are for `Ubuntu 18.04.2 LTS` (Bionic Beaver).

I run it in a Parallels VM on my MacBook Pro,


RStudio has a helpful package repository 
[here](https://cran.rstudio.com/bin/linux/ubuntu/bionic-cran35/).


and a timely article on how to build R from source
[here](https://support.rstudio.com/hc/en-us/articles/218004217-Building-R-from-source).


One would set up 

On Ubuntu (or Debian), one would install a CRAN mirror in the sources list
(`/etc/apt/sources.list`). This example is a source for the RStudio CRAN
mirror for Ubuntu 18.04 Bionic Beaver.

```
deb https://cran.rstudio.com/bin/linux/ubuntu/bionic-cran35/
```

note CRAN has a similar mirror at

```
https://cran.r-project.org/bin/linux/ubuntu/bionic-cran35/
```

Once the cran mirror has been set up you can use this command to
install package dependencies:

```
$ sudo apt-get build-dep r-base
```

Once you've satisfied the build dependencies, you should obtain and
unarchive the source tarball for the version of R you want to install.
Then from within the extracted source directory execute these commands
(this example assumes you are installing R 3.2.5 into /opt/R/3.2.5):

Note: The directory specified after ``--prefix=`` will determine where
R is installed to when executing the make install command.  The directory
does not need to exist already, it will be created.

```
$ ./configure --prefix=/opt/R/3.2.5 --enable-R-shlib
$ make
$ sudo make install
```

Note that the `–enable-R-shlib` option is required in order to make the
underlying R shared library available to RStudio.

You may also wish to link to the system BLAS libraries rather than use the
R internal versions. For this you’d use the following configure command:

```
$ ./configure --prefix=/opt/R/3.2.3 --enable-R-shlib --with-blas --with-lapack
```

The BLAS libraries are not part of the open source R binaries, but they speed
up calculations that are common in many analytic methods. If you are going
through the effort of building R from source you probably want to take advantage
of the performance benefits that are enabled by the BLAS libraries.

Optionally, you might want to point the R command to the latest R build.
In this case, R version 3.2.5.

```
$ sudo ln -s /opt/R/3.2.3/bin/R /bin/R 
```

Finally, after you have installed R, you might want to check that it was compiled
with all your desired capabilities (e.g. `png`, `cairo`, `tcltk`, etc.) with this
command:

```
> capabilities()
```









[Back to Index](../README.html)
