---
title: "Logos Tips"
author: "J. R. Minter"
date: "Started: 2017-01-21, Last modified: 2021-06-22"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---
[Back to Index](../README.html)

# Switching to different modes or sessions

1. Open Program Settings

- It starts with **General**

- Note the second selection box (At Startup Open To) - The default is
  `Most recent layout-any`. There is a **pull-down**. One can pull down
  that menu to any of your saved layouts and some others to help you
  set up what you want.

# Fix a strange problem with large fonts (2021-04-03)

Customer support asked:

1. Operating System?    
   I am running BigSur 11.2.4.    
   I am Running Windows 10 Pro 20H2     

2. Logos Version?    
   Today I updated to Logos 9.3.0.0052.
   
3. What happens if you make the scaling on the resource as well as on
   the program settings to default 100%?    
   as shown [here](https://support.logos.com/hc/en-us/articles/360015926432-Program-Settings)    
   I set "Content Scaling" and "Program Scaling" to 100%.    
   I then restarted.    
   That seemed to work. I thanked the Customer Support Agent.
   
   Also seemed to work on my 10 10 System.



# Read ESV

For ESV to have it read use `CMD R`. (It is in the pull-down menu for the
resource)

# Library helps

## Searches

### By type

```
type:bible AND lang:english
type:ency
type:comme
type:lex
type:lect
type:cal
```

### Multiple
```
title:romans, subject:romans, tag:romans
title:New Testament Survey
```

```
Romans NEAR (occasion, purpose)
Romans NEAR (theme, thematic, message)
```

[Back to Index](../README.html)