---
title: "Apple Watch Tips"
author: "J. R. Minter"
date: "Started 2021-12-04, Last modified: 2021-12-06"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---
[Back to Index](../README.html)

# Using the watch

1. Open stop watch

[Open Stop Watch](1-open-stopwatch.png)

2. start/stop/record lap times

[Start/stop/record-lap-times](2-start-stop-record-lap-times.png)

# Apple watch ring colors

The Activity app displays three rings. The **Red Move** ring shows how many active
calories you've burned. The **Green Exercise** ring shows how many minutes of
brisk activity you've done. The **Blue Stand** ring shows how many times in the
day you've stood and moved for at least one minute per hour.


# Get the most accurate measurements using your Apple Watch

From `https://support.apple.com/en-us/HT207941`

Your Apple Watch uses the personal information that you provide to help
calculate metrics for your daily activity. You can further improve its
accuracy by using these tips.

# Keep your personal information up to date

Your Apple Watch uses your personal information — such as your height, weight,
gender and age — to calculate how many calories you burn and other daily
activity metrics. 

To update your personal information, open the Apple Watch app on your iPhone.
Tap the `My Watch tab`, then tap `Health > Health Profile`.
Tap `Edit`, then tap the item that you want to change.

Health Profile on iPhone showing Date of Birth, Height and more.

# Make sure that you earn Move and Exercise credit

Every full minute of movement that equals or exceeds the intensity of a brisk
walk counts towards your daily Exercise and Move goals. With Apple Watch Series
3 or later, your cardio fitness levels are used to determine what is brisk for
you. For wheelchair users, this is measured in brisk pushes. Any activity below
this level only counts towards your daily Move goal.

To make sure that you earn Exercise credit during walks, allow the arm with your
Apple Watch to swing naturally. For example, while walking your pet, let the arm
with your watch swing freely while the other holds the leash.

If you need both hands while walking, for example to push a stroller, you can
still earn Exercise credit with the Workout app. Open the app on your Apple
Watch and tap Outdoor Walk. The Activity app relies on arm motion and an
accelerometer to track movement but the Workout app can use the accelerometer,
the heart rate sensor and GPS.


# Make sure that Wrist Detection is turned on

If Wrist Detection is turned off, you won’t get Stand notifications and your
Apple Watch can’t track your Stand progress. Background heart rate readings
(such as resting and walking rates) won’t be taken if Wrist Detection is turned
off. 

To check the setting, open the Apple Watch app on your iPhone. Tap the My Watch
tab, then tap Passcode. Make sure that Wrist Detection is turned on.

Resting and walking rates are only available on Apple Watch Series 1 or later.

Passcode settings on iPhone

# Check the fit

Wearing Apple Watch with the right fit — not too tight, not too loose and with
room for your skin to breathe — keeps you comfortable and lets the sensors do
their job.  

You may want to tighten your Apple Watch band for workouts, then loosen it when
you’ve finished. In addition, the sensors will only work if you’re wearing your
Apple Watch on the top of your wrist.

 

# Get the most accurate heart rate measurement

To get the most accurate heart rate measurement when you’re using Workout, make
sure that your Apple Watch fits snugly on top of your wrist. The heart rate sensor
should stay close to your skin. Find out about the accuracy and limitations of
the heart rate sensor.

If you have an Apple Watch Series 3 or later, set up Cardio Fitness Levels to
measure how hard your heart is working during an outdoor walk, run or hike in
the Workout app.

If you turn on Power Saving Mode during a walking or running workout, the heart
rate sensor will be turned off. To see if Power Saving Mode is turned on or off,
open Settings on your Apple Watch, then tap Workout. You can also find this
setting in the Apple Watch app on your iPhone. 

If you turn off Heart Rate in Privacy settings, you also won’t get a heart rate
measurement. To see if Heart Rate is turned on or off, open the Apple Watch app
on your iPhone, then tap Privacy.  


# Choose the best workout

When you use the Workout app, choose the option that best matches what you’re
doing. For example, if you’re running on a treadmill, choose Indoor Run. If
you’re doing a workout that isn’t listed, such as strength training, choose
Other.

Find out about each workout.

Indoor Run workout

# Calibrate your Apple Watch

Calibrate your Apple Watch to improve the accuracy of your distance, pace and
calorie measurements. Calibrating your watch can also help it learn your
fitness level and stride.

# Find out how to calibrate your Apple Watch. 

 

# What else can affect your heart rate reading?

Many factors can affect the performance of the Apple Watch heart rate sensor.
Skin perfusion (or how much blood flows through your skin) is one factor.
Skin perfusion varies significantly from person to person and can also be
impacted by the environment. If you’re exercising in the cold, for example,
the skin perfusion in your wrist may be too low for the heart rate sensor to
get a reading.

Permanent or temporary changes to your skin, such as some tattoos, can also
impact heart rate sensor performance. The ink, pattern and saturation of some
tattoos can block light from the sensor, making it difficult to get reliable
readings.

Motion is another factor that can affect the heart rate sensor. Rhythmic
movements, such as running or cycling, give better results compared with
irregular movements, such as tennis or boxing.

If you’re not able to get a consistent reading because of any of these factors,
you can connect your Apple Watch wirelessly to external heart rate monitors
such as Bluetooth chest straps. Find out how to pair Bluetooth accessories.

Heart rate is one of many factors that Apple Watch uses to measure your activity
and exercise. Depending on your workout, it selects the most appropriate inputs
for that activity. For example, when you’re running indoors, it also uses the
accelerometer. Find out more about how your Apple Watch uses GPS and the heart
rate sensor when you’re using the Workout app. 

Published Date: October 01, 2021    
JRM added  2021-12-05



[Back to Index](../README.html)

