---
title: "Python Tips"
author: "J. R. Minter"
date: "Started: 2013-07-16, Last modified: 2018-12-13"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

[Back to Index](../README.html)

# Get debug info on python installation

From [twitter](https://twitter.com/jiminy_crist/status/1072933721949552640)

```
python -m site

sys.path = [
    '/Users/jrminter',
    '/Users/jrminter/miniconda3/lib/python36.zip',
    '/Users/jrminter/miniconda3/lib/python3.6',
    '/Users/jrminter/miniconda3/lib/python3.6/lib-dynload',
    '/Users/jrminter/miniconda3/lib/python3.6/site-packages',
    '/Users/jrminter/miniconda3/lib/python3.6/site-packages/pymorph-0.96-py3.6.egg',
    '/Users/jrminter/miniconda3/lib/python3.6/site-packages/ezwrappers-0.0.910.dev0-py3.6.egg',
    '/Users/jrminter/miniconda3/lib/python3.6/site-packages/pyxray-1.3.3+1.ga0fc6ee-py3.6.egg',
    '/Users/jrminter/miniconda3/lib/python3.6/site-packages/pyPENELOPEtools-0+untagged.82.gf34e751-py3.6.egg',
    '/Users/jrminter/miniconda3/lib/python3.6/site-packages/uncertainties-3.0.2-py3.6.egg',
]
USER_BASE: '/Users/jrminter/.local' (exists)
USER_SITE: '/Users/jrminter/.local/lib/python3.6/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
Johns-MacBook-Pro:~ jrminter$ 

```



# Setup using miniconda

`2018-08-07`: Had an issue on my Win 7 box that made me uninstall my
`Miniconda-64` miniconda environment. I had migrated to this approach
on Win 7  when installing P. Pinard's `stratgem tools` where I need to
switch environments. Note that the Avast anti-virus really slows down installs.
Rebuilt the 64 bit environment. Wanted to record the the steps.

1. Get rid of the old `Miniconda-64` environment. Use the command line
(see below) This takes a while and gives some notifications that directories
are not empty. Delete those from the File Manager at the end of the (long)
process.

    ```
    rd /s /q C:\Apps\Miniconda-64
    ```

2. Install the `Miniconda3-latest-Windows-x86_64.exe` base install of
`miniconda`. I install into `C:\Apps\miniconda`. At the end of the process
**rename the directory** to `Miniconda-64`. At the end of the process we will
create a link named `miniconda` in the `C:\Apps` directory using the batch file
named `setPy64.cmd` which is in the `C:\Apps\local\path` directory.

3. After the installation finishes and the link has been created, try to start
python from the command path. You should see:

    ```
    C:\Users\jrminter>python
    Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) ... on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>>
    ```

4. Install the core python packages we will need. Add others to the list
as needed. Add others to the list (and note the date with a comment below)

    ```
    conda install numpy scipy matplotlib seaborn jupyter spyder
    conda install sqlite pandas xlwt scikit-image
    conda config --add channels conda-forge
    conda install mahotas
    conda install sympy
    conda install cython
    pip install iversions
    ```

5. To clean up (removing all the `.bz2` files), run

    ```
    conda clean --all
    ```




# Hints for key packages

## pandoc that will work with R-Studio

There seem to be some issues with pandoc 1.1.1 with RStudio on Windows. This version works

```
conda install pandoc=1.19.2.1
```

## matplotlib-scalebar

This is a helpful utility by Philippe Pinard. Install with

```
pip install matplotlib-scalebar
```

**Examples**:

Here is an example how to add a scale bar:

```
import matplotlib.pyplot as plt
import matplotlib.cbook as cbook
from matplotlib_scalebar.scalebar import ScaleBar

plt.figure()
image = plt.imread(cbook.get_sample_data('grace_hopper.png'))
plt.imshow(image)
scalebar = ScaleBar(0.2) # 1 pixel = 0.2 meter
plt.gca().add_artist(scalebar)
plt.show()
```
The scale bar also works with reciprocal units,:

```
from matplotlib_scalebar.scalebar import SI_LENGTH_RECIPROCAL
scalebar = ScaleBar(0.2, '1/cm', SI_LENGTH_RECIPROCAL) # 1 pixel = 0.2 1/cm
```

## pandas

Pandas provides a dataframe structure and is useful for
many applications. There are some "gotchas". Here are
some helpful links I want to keep...

- [10 Minutes to pandas](https://pandas.pydata.org/pandas-docs/stable/10min.html)
The official intro...

- [Wei-Ching Lin's](http://www.elasticmining.com/post/2015-12-24/gochas-using-pandas.html)
examples of unexpected behavior ("gotchas") encountered when using pandas.




## iversions

the **iversions** package is a small package that implements
listing of versions loaded by extending ipython magic commands.

1. clone from git repository from [here](https://github.com/iamaziz/iversions.git)
2, cd to the './git/iversions/iversions' directory
3. install with **pip install iversions**
4. use in ipython console or notebook with:

```
In [1]: %load_ext iversions

In [2]: import numpy as np
   ...: import pandas as pd
   ...: import tensorflow as tf
   ...: import os
   ...: import sys

In [3]: %iversions
numpy       1.13.1
pandas      0.20.3
tensorflow  1.3.0

Python 3.6.2 [Sun Aug 27, 2017 13:50:43]
```


# Key conda commands

**Note:** Sometimes the **conda update conda** command overwrites the miniconda
symbolic link I use to switch between 64 bit and 32 bit miniconda installs. The
solution is to delete the miniconda directory in C:/Apps and use the cmd files
to re-create the symbolic link...

I frequently need this list...

- List conda environments **conda info -e**
- Activate an environment (**source** on Win) **activate envName**
- Deactivate an environment (**source** on Win) **deactivate**
- Get other help **conda --help**
- Clean all source files: **conda clean --all** Can save > 1 Gb of space...
- To list channels:

```
conda config --get channels
```

- To **add** the **conda-forge** channel:

```
conda config --add channels conda-forge
```

Likewise

```
conda config --add channels conda-canary
```

- To **remove** the **conda-forge** channel:

```
conda config --remove channels conda-forge
```

likewise

```
conda config --remove channels conda-canary
```


# Current conda environments

```
> conda info -e
# conda environments:
#
py35qt4                  C:\Apps\Anaconda3\envs\py35qt4
py36                     C:\Apps\Anaconda3\envs\py36
py36-hs                  C:\Apps\Anaconda3\envs\py36-hs
py36-ski                 C:\Apps\Anaconda3\envs\py36-ski
root                  *  C:\Apps\Anaconda3
```

# A hyperspy 1.1.2 environment for Python 3.6

This uses **qt4**!


```
conda create -n py36-hs python=3.6
source activate py36-hs
conda config --add channels conda-forge
conda install hyperspy
conda config --remove channels conda-forge

# cd %HOME%/Documents/git/jmToolsPy3
# cd $HOME/Documents/git/jmToolsPy3

pip install .

```

# Two test environments for Python 3.6

```
conda create -n py36 python=3.6
activate py36
conda install numpy scipy matplotlib seaborn
conda install jupyter
conda install spyder
conda install mysql-connector-python pymysql sqlite
conda install pandas xlwt scikit-image bokeh nodejs datashader holoviews
conda install -c conda-forge mahotas=1.4.3
conda install sympy
conda install -c conda-forge spglib
conda install flake8 nose
conda install -c conda-forge py4j=0.10.4
conda install -c mcs07 chemspipy=1.0.5


# note if you install the bokeh tutorial, after you install bokeh
# you need to run this from the command line:
# > bokeh sampledata
# install modified pymorph-0.96-py3-src manually
# note: this works with my 'grains' exemplar
# also ended up installing holoviews from sorce via github

deactivate py36
```

I needed an environment with the development version of scikit-image.
I cloned the py36 environment, removed the production version of scikit-image,
and installed from a fresh pull from a direct clone of the scikit-image git
repo. Note that this also pulled down a couple of dependencies
(PyWavelets-0.5.1, dask-013.0, olefile-0.44, and toolz-0.8.2).

```
conda create --name  py36-ski --clone py36
activate py36-ski
conda remove --name py36-ski scikit-image
# needed this for latest build 2017-02-20
conda install -c anaconda cython=0.25.2
# On windows note that pip cache is in
# %USERPROFILE%\AppData\Local\pip
cd %HOME%/Documents/git/scikit-image
pip install .
```



# Youtube and other great tutorials

See also [Intermediate Python](http://book.pythontips.com/en/latest/)

- **Michael Droettboom** (Continuum Analytics) [Intro](https://www.youtube.com/watch?v=tWHiUk7PRyw)

- notebook from [GitHub](https://github.com/dmcdougall/strata-mpl-tutorial)

- from PyData 2015 NYC. He references the tutorial by [Nicolas Rougier](http://www.labri.fr/perso/nrougier/teaching/matplotlib/) who also has the source on [GitHub](https://github.com/rougier/matplotlib-tutorial). Some of this was inspired by [Ten Simple Rules for Better Figures](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833).

- Slides using reveal.js by [James Church](https://www.youtube.com/watch?v=EOpcxy0RA1A).

- [James Hetherington](http://rits.github-pages.ucl.ac.uk/doctoral-programming-intro/) of UCL has a really nice doctoral programming course in Python. He has prepared a [pdf](http://rits.github-pages.ucl.ac.uk/doctoral-programming-intro/notes.pdf) of the notes. And all the [Jupyter notebooks](http://rits.github-pages.ucl.ac.uk/doctoral-programming-intro/notebooks.zip) are available in a zip file. **One important hint: For Windows, append C:\\Program Files\\Git\\bin to the end of the path so it finds bash.exe**.

- [Frenando Perez](https://gist.githubusercontent.com/fperez/9716279/raw/69f78e7650a826b2806f83ac5275dea233aeefc9/ProgrammaticNotebook.ipynb) has a gist with a really great example of programatically creating a new Jupyter Notebook.

# Things that made me go "huh"...

## pyinstaller for python 3.5

From [stackoverflow](http://stackoverflow.com/questions/33168229/how-to-create-standalone-executable-file-from-python-3-5-scripts):

> You can use PyInstaller which support python 3.5. To install it with pip execute in terminal:

```
pip install pyinstaller

```


To build **makeOxfordAZtecIni.exe**: First make sure you have the environment
variable **EDS\_ROOT** set. You want everything in **EDS\_ROOT/Oxford/py** 


```
pyinstaller --onefile makeOxfordAZtecIni.py

```


## Latest Anaconda (4.2.0)

This will guarantee a **really clean** install. I discovered this by a lot of trial and error.

1. On Windows do a **complete uninstall**!

- Run the uninstaller
- Reboot
- From your user dir delete folders: **.anaconda, .ipython, .matplotlib, .spyder-xx**
- Delete the **.condarc** file from **C:\\Users\\username**
- Remove **C:\\Users\\userid\\AppData\\Local\\ContinuumIO**
- Run regedit and delete the keys **HKEY\_LOCAL\_MACHINE\\SOFTWARE\\Python** and **HKEY\_CURRENT\_USER\\Software\\Python**
- Run **ccleaner** and clean the registry
- Log off and back on
- Make sure nothing from Continuum shows up in the start menus

2. Install the x64 installer (**Anaconda3-4.2.0-Windows-x86_64.exe**)

3. Move `C:\Apps\Anaconda3;C:\Apps\Anaconda3\Scripts;C:\Apps\Anaconda3\Library\bin;` to right after R in `%PATH%`

4. Install **mysql-connector**, **ezwrappers** and pip install **pyinstaller**

```
conda install mysql-connector-python
pip install pyinstaller
cd ~/Documents/git/ezwrappers
python setup.py install
conda install -c conda-forge mahotas
```

5. create an environment for **hyperspy**

```
conda create -n py35qt4 python=3.5 qt=4
source activate py35qt4
conda config --add channels conda-forge
conda install mysql-connector-python
conda install mahotas
conda install hyperspy
cd ~/Documents/git/jmToolsPy3
python setup.py install
# we don't want to leave this active...
conda config --remove channels conda-forge
source deactivate
```

6. When updating environments with conda, make sure you have the correct **.condarc** file:

For the **default** (root) environment:

```
channels:
  - defaults
```

For the **py35qt4** (hyperspy) environment:

```
channels:
  - conda-forge
  - defaults
```

7. I had an install fail to install the menus on my Kodak laptop. I have the shortcuts stored in my installer collection. It later turned out that not everything installed. I fixed it by doing `conda install anaconda` from the command line. The shortcuts are all to be located in this folder:

**for all user installs:**

```
%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs\Anaconda3 (32-bit)  [or (64-bit)]
```

**for individual user:**

```
%APPDATA%\Microsoft\Windows\Start Menu\Programs\Anaconda3 (32-bit)  [or (64-bit)]
```


## possibly installing theano on Anaconda Py35

```
conda install -c jaikumarm theano=0.8.2
```

**Note:** This worked on MacOSX but **not** Win7 x64...

## installing mayavi 4.4.0 on py35

```
conda install -c menpo vtk=7.0.0
pip install mayavi

```


## matplotlib: tight_layout

From [tacaswell](https://github.com/scikit-image/scikit-image/issues/1775)

> `tight_layout` is not the default behavior in mpl because it is not 100% reliable (there are some artists it does not know about), does not work with all ways of making axes, and requires 2 passes through the rendering to get all of the sizes right. You can pass `tight_layout=True` as a kwarg to both `plt.figure()` and `plt.subplots()`

Note that `soupault` commented:

> I always use `plt.tight_layout()` right before `savefig()` or `plt.show()` in order to get fancy spacing. Although I don't really utilize any extraordinary capabilities of matplotlib (the most "complex" are: `twinx`, `twiny`, `long ticklabels`), that is for the reasons you described above.
As far as we use only basic plotting routines in skimage gallery, this change should be sufficient.

## install a `.whl` file

Using pip

```
pip install wheel_file.whl
```

or, directly from python

```
python -m wheel install wheel_file.whl
```

convert an `.egg` file to `.whl`

```
wheel convert ./wheel_file.egg
```

Note that `.whl` files are just specially formatted `.zip` archives. Change the extension to `.zip` and we can extract/explore...

## Visual Studio Versions

| Python | Ver  |    Microsoft                           |
|:-------|:-----|:---------------------------------------|
| 2.7    |  9.0 | VCForPython27.msi (VS 2008)            |
| 3.5    | 14.0 | VisualCppBuildTools_Full.exe (VS 2015) |

## Getting a good Anaconda set-up on Win7 x64

**NB:** If we want to pull packages from Anaconda Cloud we need to run

```
anaconda login
```

We will install the latest Anaconda Python 3.5 environment as a primary environment and use **conda** to create a Python 2.7 environment. This will provide a way to get whatever version of python you want and have them all play nicely together. We want to start with a clean slate...

1. Uninstall all system Pythons. Anaconda will replace them and let you set up environments with *conda*.
2. Run **ccleaner** and clean out the leftover cruft from the registry.
3. Install Anaconda3 2.5.0 in **C:\\Apps\\Anaconda3**
4. Move *C:\Apps\Anaconda3;C:\Apps\Anaconda3\Scripts;C:\Apps\Anaconda3\Library\bin;` to right after R in `%PATH%`
5. Run `conda update conda`
6. Run `conda update anaconda`   (does nothing at the moment, but can later...)
7. Run `conda update --all`
8. Run `conda install mysql-connector-python wheel dask`
9. Install `VisualCppBuildTools_Full.exe` to get a minimal, but sufficient VS-2015 C++ compiler. This is **much** lighter weight than `Visual Studio 2015 Community Edition`. This step is essential to build many packages (such as `skimage`) from their source (to get newer features).
10. Copy `vcbuildtoolsJM.bat` into `C:\Program Files (x86)\Microsoft Visual C++ Build Tools`. Create a launcher with `C:\Windows\System32\cmd.exe /k ""C:\Program Files (x86)\Microsoft Visual C++ Build Tools\vcbuildtoolsJM.bat"" amd64` and edit so it starts in a convenient directory (e.g. `C:\Users\my-userid\Documents\work\py3`).
11. Run `cd %GIT_HOME%\scikit-image`. Run `clean.sh`. Then run `python setup.py install` to install v.12-dev0 of scikit-image. All the tutorials use this. Not sure why they have not released it...
12. Fix path in `startMIDB3.bat`.
13. Run `cd %GIT_HOME%\OSImageAnalysis\py2\yml`.
14. Run `conda env create -f py27.yml`. This creates a `Python 2.7` environment.
15. For some reason, `juypter` is not properly installed from the `.yml` file, so run `conda install jupyter`. This installs jupyter and all the dependencies.
16. Copy `vcvarsallJM.bat` into `C:\Users\my-user-id\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0` and set up on the desktop a launcher with `C:\Windows\System32\cmd.exe /k ""C:\Users\l837410\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\vcvarsallJM.bat" amd64"`. Edit the batch file so that it starts in a convenient directory (e.g. `C:\Users\my-userid\Documents\work\py2`). **Note:** For some reason `%comspec%` doesn't work on `ROCPW7ZC5C423`.... This `.bat` file sets the environment variables, changes to the desired directory,  and activates py27.
17. Run `cd %GIT_HOME%\hyperspy`, then `git reset --hard; git checkout master`
18. Install hyperspy from command line:  `python setup install`.

## Downloads

```
from urllib.request import urlretrieve

url = 'http://cook.msm.cam.ac.uk//~hyperspy//EDS_tutorial//'
files = ['Ni_superalloy_1pix.msa', 'Ni_superalloy_010.rpl',
         'Ni_superalloy_010.raw']
for file in files:
    urlretrieve(url + file, file)
```

## Strings

- `r'$+\pi/2$'` - a `raw string`, where backslashes are not escaped. In this case this would be useful for an axis label in `matplotlib`.

- `u'  '` a unicode string.
- `ur'xxx' - a unicode raw string.



## Launching

On MacOSX, a recent update broke the launcher for spyder,
glueviz,and qtconsole. In reality, it is easier to use the Finder
to navigate to the desired directory, use the `cd to.app` to open
a terminal in that directory and start with one of

```
ipython qtconsole
ipython notebook
spyder
```

Note that starting `launcher` from the terminal makes the
graphical start work. Go figure...

## Updating

```
conda update conda
conda update anaconda
```

To update all packages

```
conda update --all
```

## Environments

The definitive guide is [here](http://conda.pydata.org/docs/using/envs.html)

### To list all environments

```
conda info --envs
```
or

```
conda env list
```
### To activate/deactivate an environment

On Windows

```
activate name

deactivate
```

On MacOSX/Linux

```
source activate name

source deactivate
```

### To list a detailed package list for an environment

```
conda list -e
```

### To create an environment

From the command line...

```
conda create --name myEnv python=3 scipy otherpackage
```

or from a yaml file

```
conda env create -f environment.yml
```

Export this file with from the active environment

```
conda env export > myName.yml
```

Remove an environment

```
conda remove --name theName --all
```

# iPython Notebook

Some hints from version 3.

- `--pylab` flag has been disabled as a flag; one should use
`%pylab` or `%matplotlib` in the notebook to enable matplotlib. 

- `--notebook-dir=<Unicode> (NotebookApp.notebook_dir)` the 
default is `u''`. This is the directory to use for notebooks
and kernels.  If one starts from the Anaconda Launcher, it seems
to start in one's home directory. One can navigate to the
desired folder.

## ipython4 and jupyter

Jupyter must be installed separately. See [jupyter github](https://github.com/jupyter/notebook)

An easy way to update after **the big split** from [blog.jupyter.org](http://blog.jupyter.org/2015/08/12/first-release-of-jupyter/)

```
pip install --upgrade ipython[all]  
```

or BF&I

```
# ensure setuptools/pip are up-to-date
pip install --upgrade setuptools pip
cd ~/git
git clone https://github.com/jupyter/notebook.git
cd notebook
pip install --pre -e .
jupyter notebook
```
## Polished jupyter notebooks


### Matplotlib tricks

From [here](https://www.reddit.com/r/IPython/comments/36p360/try_matplotlib_notebook_for_interactive_plots/)

> The old `%matplotlib inline` activates the inline backend, which renders figures in the notebook as static pngs.

If one wants to convert the notebook to PDF, this is the desired option

> The new `%matplotlib notebook` activates the nbagg backend, added in matplotlib 1.4, which will include a javascript interface for interaction with inline figures in the notebook. This only works in IPython >= 3.x;

This is a great option for notebooks that will remain in html format

### Optionally visible code

From [Chris Said](http://chris-said.io/2016/02/13/how-to-make-polished-jupyter-presentations-with-optional-code-visibility/) 2016-02-13.

To make the code optionally visible, available at the click of a button, include a raw cell at the beginning of your notebook containing the JavaScript and HTML below. This code sample is inspired by a [Stack Overflow](http://stackoverflow.com/questions/27934885/how-to-hide-code-from-cells-in-ipython-notebook-visualized-with-nbviewer) post, but makes a few improvements such as using a raw cell so that the button position stays fixed, changing the button text depending on state, and displaying gradual transitions so the user understands what is happening.

```
<script>
  function code_toggle() {
    if (code_shown){
      $('div.input').hide('500');
      $('#toggleButton').val('Show Code')
    } else {
      $('div.input').show('500');
      $('#toggleButton').val('Hide Code')
    }
    code_shown = !code_shown
  }

  $( document ).ready(function(){
    code_shown=false;
    $('div.input').hide()
  });
</script>
<form action="javascript:code_toggle()"><input type="submit" id="toggleButton" value="Show Code"></form>
```

It’s pretty straightforward to remove the extra elements like the header, footer, and prompt numbers. That being said, you may want to still include some attribution to the Jupyter project and to your free hosting service. To do all of this, just include a raw cell at the end of your notebook with some more JavaScript.

```
<script>
  $(document).ready(function(){
    $('div.prompt').hide();
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('.breadcrumb').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#999; background:#fff;">
Created with Jupyter, delivered by Fastly, rendered by Rackspace.
</footer>
```

One shortcoming with what we have so far is that users may still see some code or other unwanted elements while the page is loading. This can be especially problematic if you have a long presentation with many plots. To avoid this problem, add a raw cell at the very top of your notebook containing a preloader. This example preloader includes an animation that signals to users that the page is still loading. It heavily inspired by [this preloader](http://codepen.io/mimoYmima/pen/fisgL) created by [@mimoYmima](https://twitter.com/@mimoYmima).

```
<script>
  jQuery(document).ready(function($) {

  $(window).load(function(){
    $('#preloader').fadeOut('slow',function(){$(this).remove();});
  });

  });
</script>

<style type="text/css">
  div#preloader { position: fixed;
      left: 0;
      top: 0;
      z-index: 999;
      width: 100%;
      height: 100%;
      overflow: visible;
      background: #fff url('http://preloaders.net/preloaders/720/Moving%20line.gif') no-repeat center center;
  }

</style>

<div id="preloader"></div>
```

To work with these notebooks, you can clone my [GitHub repository](https://github.com/csaid/polished_notebooks). While the notebooks render correctly on nbviewer ([unpolished](http://nbviewer.jupyter.org/github/csaid/polished_notebooks/blob/master/notebook_original.ipynb), [polished](http://nbviewer.jupyter.org/github/csaid/polished_notebooks/blob/master/notebook_polished.ipynb)), they do not render correctly on the GitHub viewer.


## Problems with ipynb conversions to PDF

It did not like this kind of markdown:

```
data type, `'uint8'` (unsigned, 8-bit integer)
```
produced this $\LaTeX$

```
data type, \texttt{\textquotesingle{}uint8\textquotesingle{}} (unsigned, 8-bit integer)
```

gave the error:

```
LaTeX Error: Command \textquotesingle unavailable in encoding OT1.
```

but this was OK

```
 data type, `uint8` (unsigned, 8-bit integer)
```

I diagnosed this by converting to $\LaTeX$ with this command

```
ipython nbconvert --to latex 01_color_and_exposure.ipynb
```

and processing the $\LaTeX$

One directly converts to pdf with

```
ipython nbconvert --to pdf 01_color_and_exposure.ipynb
```

Note that Fernando Perez shows a useful Makefile for replacement 
[here](https://github.com/ipython/sloan-2013-reports/blob/master/Makefile).

Here is one I wrote that let me edit the $\LaTeX$ file in between

```
# in
# /Users/jrminter/src/py2/tstMakePdfFromIpynb
BASE=demonstrateEigenValues

all: $(BASE).pdf

$(BASE).tex: $(BASE).ipynb
	ipython nbconvert --to latex $(BASE).ipynb
	./replace.py $(BASE).tex


$(BASE).pdf: $(BASE).tex
	pdflatex $(BASE)
	pdflatex $(BASE)

clean:
	rm -rf $(BASE)_files
	rm -rf *.a*
	rm -rf *.b*
	rm -rf *.l*
	rm -rf *.t*
	rm -ff *.out

cleanall: clean
	rm -f $(PDF)

```

This is the `replace.py` file (from F. Perez)

```
#!/usr/bin/env python
"""Simple script to replace a list of regex patterns in the input file.

WARNING: this modifies the input file in place!!! It does leave file~ as a
backup.

Usage::

    replace.py <input filename>
"""

#-----------------------------------------------------------------------------
# Configure here - define replacement list
#-----------------------------------------------------------------------------

patterns = [(r'\\documentclass{article}',
             r'\\documentclass[11pt]{article}\n  \\usepackage{palatino}'),
             (r'\\title{demonstrateEigenValues}',
              r'\\title{Demonstrate EigenValues}\n \\author{John Minter}\n  \\date{\\today}')
            ]

# You shouldn't need to configure any further code.

#-----------------------------------------------------------------------------
# Imports
#-----------------------------------------------------------------------------

import os
import re
import sys

#-----------------------------------------------------------------------------
# Main code
#-----------------------------------------------------------------------------

# Compile regexes first. That way, if there's an error in any of them, we fail
# early before touching any files.
replacements = [ (re.compile(pat, re.MULTILINE), rep)
                 for (pat, rep) in patterns ]

# Rename input file, read it in, run over the regexes and write output file
fname = sys.argv[1]
backup = fname+'~'

os.rename(fname, backup)

with open(backup) as fin:
    out = fin.read()

for rx, rep in replacements:
    out = rx.sub(rep, out)

with open(fname, 'w') as f:
    f.write(out)
```


# Spyder problem on Py 3.4

Had problems with crashes. Turned out to be Babel 2.0. Ended up installing both Babel and Spyder from source. 

## Checking outdated packages

```
pip install wheel
pip install some-package.whl

```

For python 2

```
pip2 list --outdated

pip2 install h5py --upgrade
pip2 install traitsui --upgrade
```

## Microsoft Visual C++ Compiler for Python 2.7

### Installing and Uninstalling

The compiler package will default to installing just for the current user and does not require administrative privileges. To install for all users of a machine, execute `msiexec /i <path to MSI> ALLUSERS=1` from an elevated Command Prompt.

To remove or repair the compiler package, locate the entry in Programs and Features and select Remove or Repair.

### Using with Python distribution tools
Python package developers should download and use this compiler to produce binary wheels for their Python packages to upload to PyPI. Installing the wheel package, updating to setuptools 6.0 or later, and adding setup.py bdist_wheel upload to your build process will produce the correct files (remember to do this for both 32-bit and 64-bit versions).

If a Python package you are installing does not have a wheel, you can install this compiler package on your own machine. Once the compiler is installed and you have updated to setuptools 6.0 or later, you can use pip install to build and install the Python package. If you are managing multiple machines and need to install the Python package on all of them, you should install the wheel package and use pip wheel to produce a wheel that can be installed on machines without requiring this package.

## installing from git repos

For python 3
```
$ cd repo
$ pip3 install -e ./
```

For python 2
```
$ cd repo
$ pip install -e ./
```

## Uninstalling Python 3.4.1 on Win7 x64

Following the hints below:

1. I uninstalled all other installed py34 pgms. Uninstalled 3.4.1. Failed.
2. Did a regedit search for **Python 3.4.1  **and deleted all keys
3. Did a **Python  **search and deleted all keys
4. Ran CCCleaner and cleaned all
5. Deleted everything in Python34 except empty Scripts folder
6. Restarted
7. Ran CCCleaner and cleaned all
8. Installed 3.4.2

Not the first person to run into this problem. Found [this](http://www.gossamer-threads.com/lists/python/python/1157273)

On 8/29/2014 11:26 PM, Llelan D. wrote: 

> Actually, I do know more than a little about the Windows MSI service and 
> application, and had already perused the logs to no avail. All of the 
> listed registry keys were deleted without changing the problem. The 
> missing file is of no importance since I already know the installation 
> directory is deleted. It's just that the installer should normally 
> supply that information. 
> 
> The error messages are Windows System errors that are being caused by 
> requirements of the MSI installer file and not the msiexec.exe 
> application. The problem is with how the installer is written and not 
> the MSI system. 
> 
> There's always a simple answer to things like this. It's just that the 
> simple answers are harder to find in poorly written code. 
> 
> I randomly poked around the registry a lot more, deleting anything I 
> could find referring to Python34 and then the string "Python 3.4.1". I 
> finally got desperate enough to delete the python installer entries 
> under the Windows Installer key (the list of installed applications in 
> the Windows "Uninstall or Change a Program" Control Panel). You know, 
> the registry keys you are *NEVER* to use as an indication if the 
> application is currently installed because MS constantly corrupts this 
> list and can leave your installation in an un-installable, 
> un-repairable, and un-removable state? 
> 
> Well it worked. The Python installer no longer sees the application as 
> installed and happily performs a full installation. I did that, a full 
> removal to get rid of any other problems, and a clean installation and 
> everything works fine now. 
> 
> This installer is seriously screwed up and desperately needs a re-write. 
> It should use its own key to indicate whether the application is 
> installed but should not depend on it in case of a partially 
> installed/removed state, should not require any installed file to fully 
> repair or remove the application, and should query the user if any 
> information required is missing from the installation or registry. In 
> other words, the normal MSI installer guidelines. 
> 
> I hope this is of help to someone out there. 

## Fixing python-win32 on python 3.4

From [stackoverflow](http://stackoverflow.com/questions/22490233/win32com-import-error-python-3-4)

We need to re-run the install script to get **import win32wnet  **to work.

```
python C:\Python34\Scripts\pywin32_postinstall.py -install
```



## Creating the default ipython profiles

Clean out any old ones

```
cd ~
rm -rf .ipython
# create new defaults
ipython profile create
```

[A useful ref](http://ipython.org/ipython-doc/dev/config/intro.html)

## 2to3

**2to3  **is a utility installed with python3 that helps convert. The documentation is [here](http://docs.python.org/2/library/2to3.html).

# Getting Python 2 and 3 to play well with Win7
There was a great discussion on [StackOverflow](http://stackoverflow.com/questions/15912063/how-do-i-run-python-2-and-3-in-windows-7) that suggested the [Python launcher for Windows](http://www.python.org/dev/peps/pep-0397/) introduced in Python 3. The documentation is on [bitbucket](https://bitbucket.org/vinay.sajip/pylauncher/src/tip/Doc/launcher.rst).

## Building Python Extensions on Win 7 x64

One must precisely match the compiler used to
build the binaries. For Python 3.3, this is
Visual Studio 2010.  I did a custom install of
Visual Studio 2010 Premium to get the x64 compilers
installed. I also installed Service Pack 1 and
the x64 redistributable package.

### Get the environment variables set

The easiest way to do this is to use the **Visual
Studio x64 Win64 Command Prompt  **command window.

### Example: compiling the 0.10 dev version of scikit-image

1. I started the **x64 Win64 Command Prompt**
2. I downloaded the source from github.
3. When I first tried **python setup.py build** it complained about missing the cython dependency.
4. I did **pip3 install cython** from the command window.
5. On my second attempt at **python setup.py build** I got an error complaining about undefined **M_PI**. This should have been picked up by **include math.h** but was not. I placed this in the two affected files

```
#ifndef M_PI
  #define M_PI 3.14159265358979323846
#endif
```

This built and installed without further error messages.


## GUI
### Eclipse
#### Install from PyDev
Install from update site **http://pydev.org/updates``
### Color themes
Install from update site **http://eclipse-color-theme.github.io/update/``

They have a nice Sublime Text 2 theme

## Directory operations

### get the current working directory
```
import os
os.getcwd()
```
### remove an entire tree
```
import shutil
shutil.rmtree(path, ignore_errors=False, onerror=None)
```

## ini files
[StackOverflow](http://stackoverflow.com/questions/8884188/how-to-read-and-write-ini-file-with-python)

```
import configparser

config = configparser.ConfigParser()
config.read('FILE.INI')
print(config['DEFAULT']['path'])     # -> "/path/name/"
config['DEFAULT']['path'] = '/var/shared/'    # update
config['DEFAULT']['default_message'] = 'Hey! help me!!'   # create

with open('FILE.INI', 'w') as configfile:    # save
    config.write(configfile)
```

Seems to work fine...

## List Comprehensions

From [Carl Groner](http://carlgroner.me/Python/2011/11/09/An-Introduction-to-List-Comprehensions-in-Python.html)

### The basics.
Let’s start with a simple list.

```
>>> my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
>>> my_list
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

Quite often, we’ll need to build a new list from the elements of an existing list. For example, let’s say we want to make a list containing all elements of **my_list``, each multiplied by 2. 

### Using Python's List Comprehension
Now let’s take a look at how to do this using Python’s list comprehension syntax.

```
>>> new_list = [x * 2 for x in my_list]
>>> new_list
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
```
### Syntax
The syntax for list comprehension is based on set builder notation. Given the form **[Y for X in LIST]**, **Y** is commonly referred to as the **output function** , **X** is the ***variable***, and **LIST** is the **input set**. This statement says to do **Y** on each **X** in **LIST**.

For an example of using a different output function, let’s say say we want a new list that contains each number in **my_list** as a string type…

```
>>> [str(x) for x in my_list]
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
```

You may be asking yourself why we wouldn't just use **map()** here:

```
>>> map(str, my_list)
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
```

In this example, **map** looks like a good alternative. However, for slightly more complicated requirements, list comprehension can be a bit more concise. For example, when we’d like to specify a predicate .

### The predicate
Consider our previous example, where we want to create a list of string types for each element in **my_list``, except this time we only want the elements which are even numbers. A typical way to do this would be:

```
>>> new_list = []
>>> for x in my_list:
...   if (x % 2) == 0:
...     new_list.append(str(x))
... 
>>> new_list
['2', '4', '6', '8', '10']
```

In order to use map() here we would need to first filter the list to exclude the odd numbers.

Using the list comprehension syntax would look like this:

```
>>> new_list = [str(x) for x in my_list if (x % 2) == 0]
>>> new_list
['2', '4', '6', '8', '10']
```

This version introduces the predicate, an expression after the list which acts as a filter on which elements get passed to the output function.

Neat, clear and concise.

### Loops of loops.
Finally, it’s worth mentioning that you can use list comprehensions to iterate on more than one list. For example:

```
>>> list_a = ['A', 'B']
>>> list_b = [1, 2]
>>> [(x, y) for x in list_a for y in list_b]
[('A', 1), ('A', 2), ('B', 1), ('B', 2)]
```

Just like you would expect in for loops, the last loop moves the fastest. Also note that this method returns a list of tuples. If you’d like nested lists, you can also nest one list comprehension within another.

```
>>> list_a = ['A', 'B']
>>> list_b = ['C', 'D']
>>> [[x+y for x in list_a] for y in list_b]
[['AC', 'BC'], ['AD', 'BD']]
```

### Summary.

List comprehension in Python can often provide a neat, clear, and concise syntax for creating lists from other lists. However, one should always be aware that, particularly for complex transformations or predicates, the concise and terse syntax can quickly become very difficult to read. In these cases, it's often beneficial to revert to traditional looping constructs.


## Alchemy...

## A DM3 image reader in python
[ImageJ Wiki](http://imagejdocu.tudor.lu/doku.php?id=plugin:utilities:python_dm3_reader:start)

## MySQL

## With Python 3

JRM...

Try
[mysql-connector-python](http://dev.mysql.com/doc/relnotes/connector-python/en/)

```
easy_install mysql-connector-python
```

documentation
[mysql.com](http://dev.mysql.com/doc/refman/5.6/en/connector-python.html)


[stackoverflow](http://stackoverflow.com/questions/15434930/python-3-mysql-and-pymysql-on-a-windows-7-box)
> I might be asking the impossible. However, I am trying to
> connect to MySQL on a windows 7 box using Python 3.3.0.
> I've using PyMySQL as a way to connect, but this appears
> not to be supported for a Windows box.

offered this answer

> Rather than use any other connector. I found that MySQL
> have a Python 3.3 MySQL connector which solves this issue.
> [see](http://dev.mysql.com/doc/refman/5.6/en/myconnpy_example_connecting.html)



Note that
[this question](http://stackoverflow.com/questions/4960048/python-3-and-mysql)
suggested that

> You should probably use pymysql - Pure Python MySQL
> client instead. It works with Python 3.x, and doesn't
> have any dependencies.
> 
> This pure Python MySQL client provides a DB-API to a
> MySQL database by talking directly to the server via
> the binary client/server protocol.
>
> Example:

```
import pymysql
conn = pymysql.connect(host='127.0.0.1', unix_socket='/tmp/mysql.sock', user='root', passwd=None, db='mysql')
cur = conn.cursor()
cur.execute("SELECT Host,User FROM user")
for r in cur:
    print(r)
cur.close()
conn.close()

```

They offered the link to
[gohkle's](http://www.lfd.uci.edu/~gohlke/pythonlibs/)
Win binaries. Currently (2013-06-01), the list doesn't
list py3.2 binaries. I do note that there are py3.2
binaries for Oursql that claims to support MySQL
databases
see [this example](http://pythonhosted.org/oursql/tutorial.html#establishing-a-connection).


[Back to Index](../README.html)
