---
title: "Windows Tips"
author: "J. R. Minter"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: united
    highlight: pygments
---

[Back to Index](../README.html)

Some useful tips for windows

## Create a shortcut to switch between windows in Win 7
Drag the shortcut from to ``%USERPROFILE%\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\Switch`` the quick launch bar.

Creat a similar shortcut of the character map ``%windir%\system32\charmap.exe``

## Use Imagemagick to convert png to pdf from the command line
```
convert sample.png sample.pdf
```
Note: for high resolution (default is 72 dpi) one can add

```
-density 300
```

From [Stackoverflow](http://unix.stackexchange.com/questions/42856/how-can-i-convert-a-png-to-a-pdf-in-high-quality-so-its-not-blurry-or-fuzzy)

## Win7 libraries

[microsoft's tutorial](http://windows.microsoft.com/en-us/windows7/include-folders-in-a-library)

Libraries are a new feature in Win7 that gather content from various folders.

### To include a folder in a library:

1. Open the location of the folder you want to include.
2. Right-click on the folder and select ``Include in library``'.
3. Choose from a Library in the list or create a new one. Note that the folder is linked into the library, but remains in its original location.

### To remove a folder from a library

1. In the task bar, click the ``Windows Explorer`` button.
2. Click the library in the navigation pane.
3. Click ``locations`` at the top of the window.
4. Click the folder you want to remove from the library and then the ``Remove`` button and then ``Ok``. The folder is unlinked from the library but remains in its original location.


## Net use
see [Technet](http://technet.microsoft.com/en-us/library/gg651155.aspx) also see [about.com](http://pcsupport.about.com/od/commandlinereference/p/net-use-command.htm)

### Syntax

```
net use [{<DeviceName> | *}] [\\<ComputerName>\<ShareName>[\<volume>]] [{<Password> | *}]] [/user:[<DomainName>\]<UserName] >[/user:[<DottedDomainName>\]<UserName>] [/user: [<UserName@DottedDomainName>] [/savecred] [/smartcard] [{/delete | /persistent:{yes | no}}]

net use [<DeviceName> [/home[{<Password> | *}] [/delete:{yes | no}]]

net use [/persistent:{yes | no}]
```

### Example

```
net use d:\\server\share /user:Accounts\User1
```


Here's a slightly more complicated example that you might see in a business setting.

In this net use example, I want to map my ``e:`` drive to the ``smithmark`` shared folder on ``usrsvr002``. I want to connect as another user account I have ``[/user]`` by the name of ``msmith2`` that's stored on the ``pdc01`` domain with a password of ``Ue345Ii``. I don't want to map this drive manually every time I start my computer ``[/p:yes]`` nor do I want to enter my username and password each time ``[/savecred]``.

```
net use e: \\usrsvr002\smithmark Ue345Ii /user:pdc01\msmith2 /savecred /p:yes
```

I suppose an appropriate final example of net use would be the removal ``[/delete]`` of a currently mapped drive, in this case ``p:``.

```
net use p: /delete
```



## A setup for Win7/WinXP compatibility

1. On WinXP, create ``C:\Users\userName`` for each user. Create a ``Documents`` folder there. Change ``My Documents`` to point there. This is the default for Win7. We will use this as the user's ``%HOME%`` directory on both systems.

2. Create ``git``, ``work``, and ``src`` directories in each users ``Documents``. Create a ``proj`` directory in ``work``. 

3. Place shared dlls/scripts in ``C:\Apps\local``

4. Install Apps like analySIS, R, texlive, etc that you would like to play well across systems call frequently from the system path into a folder in ``C:\Apps``. Avoid spaces in path names was much as possible. Short is good!!!

## Enabling cut/paste w mouse from cmd window

[MS Technet](http://technet.microsoft.com/en-us/magazine/ff758104.aspx) notes that one can enable copy/paste with the mouse by enabling ``QuickEdit Mode`` in the default command window properties. See also [howto geek](http://www.howtogeek.com/howto/windows-vista/copy-to-the-clipboard-from-the-windows-command-prompt/)

## Poster printing

To use the poster printer in the 8th floor site office

1. **Queue:** ``\\rocps003\PLT4022``
2. Works well with Adobe Reader. Go to ``page setup``
3. **Paper Choice** ``Oversize B0(JIS)``
4. **Paper Source:** Check before use. Typically ``Roll 1`` is satin, ``Roll 2`` is glossy.
5. Make sure you choose best quality - it is slow; typically takes 20 min for a typical poster.

## Re-assigning drive letters

From [superuser.com](http://superuser.com/questions/70295/force-a-usb-device-to-use-a-certain-drive-letter?rq=1)

1. Start | Control Panel | Administrative Tools | Computer Management
2. Click on "Disk Management"
3. Select the USB drive in the list
4. Right-click and "Change Drive Letters and Paths..."
5. Assign a different, unused drive letter.

## Fixing major annoyances

### Quick Launch Bar in Win7

The [howto geek](http://www.howtogeek.com/howto/windows-7/add-the-quick-launch-bar-to-the-taskbar-in-windows-7/) shows us how...

1. Unlock taskbar
2. Create a new toolbar from the menu
3. Type in the location:

```
%appdata%\Microsoft\Internet Explorer\Quick Launch
```

It will be all the way over on the right, so you’ll want to click on the dotted lines and then drag the toolbar all the way to the left (which is slightly tricky sometimes). ***Note that you’ll need to right-click and unlock the taskbar before you can move the toolbar.***

### No context menus in Win 7
This has been a pain for a while on a few systems.
Of all the tips I found on line the instructions
from [here](http://sourceforge.net/p/sevenzip/discussion/45797/thread/838d57cb/) worked

```
1. open regedit
2. open HKEY_CLASSES_ROOT
3. open *
4. open shellex
5. open right click on ContextMenuHandlers and go to permissions
6. click on Advanced
7. check "Replace all child objects permissions with inheritable permissions form this object"
8. hit OK a few times
9. try to right click on a file and see if it shows up.
```

## Environment Variables

A pair of useful lists from
[askvg.com](http://www.askvg.com/list-of-environment-variables-in-windows-xp-vista-and-7/)

### WinXP

```
Environment Variable         Path
%ALLUSERSPROFILE%           C:\Documents and Settings\All Users
%APPDATA%                   C:\Documents and Settings\{username}\Application Data
%COMMONPROGRAMFILES%        C:\Program Files\Common Files
%COMMONPROGRAMFILES(x86)%   C:\Program Files (x86)\Common Files
%COMSPEC%                   C:\Windows\System32\cmd.exe
%HOMEDRIVE%                 C:
%HOMEPATH%                  C:\Documents and Settings\{username}
%PROGRAMFILES%              C:\Program Files
%PROGRAMFILES(X86)%         C:\Program Files (x86) (only in 64-bit version)
%SystemDrive%               C:
%SystemRoot%                C:\Windows
%TEMP% and %TMP%            C:\Documents and Settings\{username}\Local Settings\Temp
%USERPROFILE%               C:\Documents and Settings\{username}
%WINDIR%                    C:\Windows
```

### Vista and Win 7

```
Environment Variable        Path
%ALLUSERSPROFILE%           C:\ProgramData
%APPDATA%                   C:\Users\{username}\AppData\Roaming
%COMMONPROGRAMFILES%        C:\Program Files\Common Files
%COMMONPROGRAMFILES(x86)%   C:\Program Files (x86)\Common Files
%COMSPEC%                   C:\Windows\System32\cmd.exe
%HOMEDRIVE%                 C:
%HOMEPATH%                  C:\Users\{username}
%LOCALAPPDATA%              C:\Users\{username}\AppData\Local
%PROGRAMDATA%               C:\ProgramData
%PROGRAMFILES%              C:\Program Files
%PROGRAMFILES(X86)%         C:\Program Files (x86) (only in 64-bit version)
%PUBLIC%                    C:\Users\Public
%SystemDrive%               C:
%SystemRoot%                C:\Windows
%TEMP% and %TMP%            C:\Users\{username}\AppData\Local\Temp
%USERPROFILE%               C:\Users\{username}
%WINDIR%	                C:\Windows
```


# Win32


## Getting short path names

This one had me ripping my hair out. The solution was
[here](http://answers.google.com/answers/threadview/id/522710.html)


There's a simple way to do it:

run ``cmd.exe`` and do the following:
```
cd "long path name"
command
```
Then ``command.com`` will come up and display the short path name.

[Back to Index](../README.html)

