---
title: "Sole Treadmill"
author: "J. R. Minter"
date: "Started: 2015-05-10, Last modified: 2022-01-25"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
---
[Back to Index](./README.html)

```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# make this an external chunk that can be included in any file
library(knitr)
options(width = 72)
opts_chunk$set(message = F, error = F, warning = F, comment = NA, fig.align = 'center', dpi = 100, tidy = F, cache.path = '.cache/', fig.path = 'figure/')

options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
knit_hooks$set(plot = knitr:::hook_plot_html)
```


# Sole F63 Treadmill

From [Sole](https://www.soletreadmills.com/treadmills/f63-sole-treadmill)

## How to use the treadmill

1. Stand on Treadmill

2. Use **either program** Up/Down

3. When it cycles to **User1** hit the button.

4. When ready press **Start**

## Specs

-   3.0 HP motor provides a range of speeds including the challenging 12 mph top speed

-   Cushion Flex Whisper Deck reduces impact to joints by 40%

-   15 levels of incline provide the right challenge for runners and walkers of all abilities

-   Flywheels create a smoother, vibration free surface

-   Heavy-duty steel construction guaranteed for life


## Overview

-   Named “Best in its Price Range” by Fit Rated, Run Reviews, Treadmill Reviews,
    and many others
-   Easy Assist Folding Deck Design makes storing your treadmill easy and
    convenient
-   High-end rollers create a static free motion leading to a long lifespan

-   Smoothest treadmill when making adjustments mid-workout

-   LCD screen provides real-time statistics to monitor progress towards goals

## Technology

-   Bluetooth Audio Speakers - listen to music from your smart devices through
    the speakers on the console.
    
-   USB Port - Charge your smart devices while working out

-   Integrated tablet holder - gives you the freedom to use your smart devices
    to watch shows or follow your workout routines
    
-   Unmatched convenience with handlebar adjustment technology

-   Integrated entertainment systems make time fly during workouts

## More

### Machine Dimensions

- Height(in.): 66"
- Item Weight(lbs.): 254 lbs.
- Length(in.): 82"
- Weight Capacity(lbs.): 325 lbs.
- Width(in.): 35"
- Running Surface: 20" X 60"
- Rollers: 2.5"
- Step Up Height: 8"
- Box Dimensions: 86"X36"X17"
- Controls & Features
- Bluetooth Speaker Compatible: Yes
- Tablet/Phone: Yes
- USB Device Charging: Yes
- Bluetooth Compatible: Yes
- Standard Programs: 6
- Custom Programs: 2
- Heart Programs: 2
- Heart Rate Monitoring: Pulse Grips & Chest Strap Compatible
- Chest Strap Included: Yes
- Cooling Fans: Yes
- Sound System: Yes
- Workout Display: 6.5" LCD
- Display Color: White Back-lit
- Motor : 3.0 HP, DC Type
- Speed : .5 - 12 mph
- Incline: 0 - 15 Levels
- Easy Assist Folding: Yes

## Warranty

- Frame: Lifetime
- Motor: Lifetime
- Deck: 3 Years
- Electronics: 3 Years
- Parts: 3 Years
- Labor: 1 Years


[Back to Index](./README.html)
