Color tips
========================================================
```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# make this an external chunk that can be included in any file
library(knitr)
options(width = 72)
opts_chunk$set(message = F, error = F, warning = F, comment = NA, fig.align = 'center', dpi = 100, tidy = F, cache.path = '.cache/', fig.path = 'figure/')

options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
knit_hooks$set(plot = knitr:::hook_plot_html)
```


[Back to Index](../README.html)


Color palettes need to be chosen carefully.

Resources

[Zach Holman](http://zachholman.com/posts/slide-design-for-developers/)

[ColorBrewer](http://colorbrewer2.org/)

[colourlovers](http://www.colourlovers.com)

[Kuler](https://kuler.adobe.com/create/color-wheel/)

[efg's handy R-Color PDF](pdf/RColorChart.pdf)


## My favorite desktop background

I like ``RGB(0,34,64)`` which is ``#002240``. Note that my favorite
light yellow background for analySIS scale bars is ``RGB(255,255,220)``
which is ``#FFFFDC`` 

```{r,fig.height=1, fig.width=1}
pal <- c("#002240", "#FFFFDC")
std.mar <- par()$mar
par(mar = rep(0, 4)) 
image(matrix(1:2), col = pal, axes = FALSE)
par(mar=std.mar)
```


## Some Palettes I like

### 8-class BrBG (Diverging) from Color Brewer

```
Brown
#8c510a
#bf812d
#dfc27d
#f6e8c3 x
#c7eae5 x
#80cdc1
#35978f
#01665e
Blue-Green
```
```{r,fig.height=1}
pal <- c("#8c510a","#bf812d", "#dfc27d", "#f6e8c3", "#c7eae5","#80cdc1","#35978f","#01665e")
names(pal) <- c("","","","","","","","")
std.mar <- par()$mar
par(mar = rep(0, 4)) 
image(matrix(1:8), col = pal, axes = FALSE)
par(mar=std.mar)
```

### 8-class  RdYlBu

```
Red
#d73027
#f46d43
#fdae61
#fee090
#e0f3f8
#abd9e9
#74add1
#4575b4
Blue
```

```{r,fig.height=1}
pal <- c("#d73027","#f46d43","#fdae61","#fee090","#e0f3f8","#abd9e9","#74add1","#4575b4")
names(pal) <- c("","","","","","","","")
std.mar <- par()$mar
par(mar = rep(0, 4)) 
image(matrix(1:8), col = pal, axes = FALSE)
par(mar=std.mar)
```


[Business Casual](https://kuler.adobe.com/Business-Casual-color-theme-5595/)

```{r,fig.height=1}
pal <- c("#133463","#365FB7", "#5A72A6", "#F4EFDC", "#BA9B65")
std.mar <- par()$mar
par(mar = rep(0, 4)) 
image(matrix(1:5), col = pal, axes = FALSE)
par(mar=std.mar)
```


[Threadless](http://www.colourlovers.com/palette/27905/threadless)

```{r,fig.height=1}
pal <- c("#1B325F","#9CC4E4", "#E9F2F9", "#3A89C9", "#F26C4F")
std.mar <- par()$mar
par(mar = rep(0, 4)) 
image(matrix(1:5), col = pal, axes = FALSE)
par(mar=std.mar)
```

[Blown Entreprneur](http://www.colourlovers.com/palette/59867/Blown_Entrepreneur)

```{r,fig.height=1}
pal <- c("#44749D","#C6D4E1", "#FFFFFF", "#EBE7E0", "#BDB8AD")
names(pal) <- c("","", "", "", "")
std.mar <- par()$mar
par(mar = rep(0, 4)) 
image(matrix(1:5), col = pal, axes = FALSE)
par(mar=std.mar)
```

[Back to Index](../README.html)
