---
title: "Secrets to Gas Control"
author: "Peter Jaret"
date: 'Started: 2021-03-25, Last Modified: 2021-04-12'
output:
  pdf_document: default
  html_document:
    df_print: paged
---
Secrets to Gas Control
By Peter Jaret
Reviewed by Brunilda Nazario, MD on September 17, 2012
FROM THE WEBMD ARCHIVES 
The average person passes gas 14 to 23 times a day. Knowing it’s healthy and normal doesn’t always keep it from being embarrassing. If you’re tired of silly jokes and occasional upset, a few simple tips may help you take charge of bloating and gassiness.

Watch What You Eat
The friendly bacteria in our guts help digest foods that our bodies have trouble breaking down. These bacteria also produce gas, usually as they digest food in the large intestines. Foods most often linked to intestinal gas include:

Beans and lentils
Asparagus, broccoli, Brussels sprouts, cabbage, and other vegetables
Fructose, a natural sugar found in artichokes, onions, pears, wheat, and some soft drinks
Lactose, the natural sugar found in milk
Fruits, oat bran, peas, and other foods high in soluble fiber, which gets digested in your large intestine
Corn, pasta, potatoes, and other foods rich in starch
Sorbitol, the artificial sweetener
Whole grains, such as brown rice, oatmeal, and whole wheat
That list covers a whole lot of healthy food, but you don’t have to severely restrict your diet. Most likely just a few give you gas. "Some people have problems digesting milk. Others don’t," says Lawrence R. Kosinski, MD, MBA, a spokesman for the American Gastroenterological Association. "And food sensitivities may change with age. Many people develop problems digesting milk products as they get older, for instance."

Two simple steps can help you discover your problem foods.

Keep a food diary. When you have bloating or gas, look back over the foods you’ve eaten within the last few hours – that’s typically when gas occurs.
Experiment, one by one, with the foods you suspect. Eat one of the foods by itself. Does it give you gas? If not, wait a day, then experiment with another of your suspect foods. Keep going through the list on different days until you find the food that gives you gas.
Adjust Your Diet
The best way to reduce gassiness is to avoid foods that cause problems. If a healthy food gives you gas – such as whole grains and vegetables -- reduce the amount you eat. Then, gradually start eating more of the food – increasing the amount bit by bit over weeks – to give your digestive system time to adjust.

Consider a Supplement
Some supplements contain digestive enzymes that break down hard-to-digest foods. You can buy the enzyme lactase over the counter if dairy products give you gas. A product called Beano helps break down gas-producing sugars in beans.

Avoid Swallowing Air
We all swallow small amounts of air. That’s normal. When we swallow too much air – called aerophagia -- it causes abdominal bloating, gas, or belching. Pay attention to things you do that may make you swallow more air than you need, such as:

Chewing gum
Drinking carbonated sodas
Eating too quickly
Smoking
Wearing loose dentures
Stress can also make you swallow too much air. "Often people aren’t even aware that they’re gulping down air," Kosinski says. "If you’re feeling anxious or [are] under a lot of stress, look for ways to relax. Or talk to your doctor about stress reduction techniques."

Get Moving
Walking, bicycling, running, and other forms of exercise can help move gas through your digestive tract, easing bloating.

Talk to Your Doctor if You’re Worried
If lifestyle changes don’t help, and you’re bloated or gassy often, talk to your doctor.

"Bloating or abnormal amounts of intestinal gas can be a symptom of celiac disease, irritable bowel syndrome, bacterial overgrowth, or problems associated with the pancreas," Kosinski says. "Certain medications can also cause intestinal gas. So it’s definitely important to mention it to your doctor if you’re worried."

Your doctor may suggest tests to rule out underlying problems. If the culprit is simply the foods you love, your doctor can also prescribe medicine -- a gastrointestinal stimulant -- that moves gas through your intestines more quickly.

WebMD Feature
Sources © 2008 WebMD, LLC. All rights reserved.
TOP PICKS
What Are Prebiotics?
Common Constipation Treatments
Gastroparesis: What to Eat and What to Avoid
Newly Diagnosed With Crohn's? Steps to Take
Restaurant Heartburn Triggers
Experimental Pill for Celiac Disease
FURTHER READING
A Visual Guide to Irritable Bowel Syndrome
Super Steps to Boost Digestive Health
Clear the Air: The Lowdown on Gas
All About Farts
Gas and Bloating Topics
TODAY ON WEBMD
man holding his stomach
Digestive Myths
Get the facts on common problems.

blueberries in a palm
Diverticulitis Diet
Best and worst foods.

TOOLS & RESOURCES
What Is Appendicitis?
How Heartburn Happens
Is My Constipation Serious?
IBS Triggers and Prevention
How to Choose a Biologic
16 Tips for Good Digestion
Click to See More
SIGN UP FOR OUR FREE DIGESTIVE HEALTH NEWSLETTER
Enter your email address
By clicking "Subscribe," I agree to the WebMD Terms and Conditions and Privacy Policy. I also agree to receive emails from WebMD and I understand that I may opt out of WebMD subscriptions at any time.
TODAY ON WEBMD
RECOMMENDED FOR YOU
diverticuliltis illustration
SLIDESHOW
What Is Diverticulitis?
couple eating at cafe
ARTICLE
Dining Out? Cut Calories, Heartburn
boy with ice cream
SLIDESHOW
Tummy Troubles in Kids
Woman blowing bubble gum
SLIDESHOW
Gum for Heartburn & Other Digestive Tips
photo of woman with upset stomach
ARTICLE
Crohn's Disease Complications
Woman with stomach pain
SLIDESHOW
What Is Celiac Disease?
diet for diverticulitis
VIDEO
Diet for Diverticulitis
what causes diarrhea
VIDEO
What Causes Diarrhea?
More from WebMD
5 Tips to Help With Relapsing MS
How to Thrive With Narcolepsy
Relief for Blocked Hair Follicles
Psoriatic Arthritis and Your Sleep
What Psoriasis Feels Like
First Psoriatic Arthritis Flare
Talking to Your Doctor About RA
Crohn's: A 'Full-Body' Disease
Avoiding Crohn’s Flares
Living With Ankylosing Spondylitis
Live Better With Psoriatic Disease
Types of B-Cell Therapy for MS
Living Better With T2 Diabetes
Why Prostate Cancer Spreads
Getting the Care You Need for MS
Where Breast Cancer Spreads
Logo for WebMD
FIND US ON:
Facebook
Twitter
Pinterest
Policies
Privacy Policy
Cookie Policy
Editorial Policy
Advertising Policy
Correction Policy
Terms of Use
About
Contact Us
About WebMD
Careers
Newsletter
Corporate
WebMD Health Services
Site Map
Accessibility
WebMD Network
Medscape
Medscape Reference
MedicineNet
eMedicineHealth
RxList
OnHealth
WebMDRx
First Aid
WebMD Magazine
WebMD Health Record
Dictionary
Physician Directory
Our Apps
WebMD Mobile
WebMD App
Pregnancy
Baby
Allergy
Medscape
For Advertisers
Advertise with Us
Advertising Policy
TRUSTeTAG Registered SealHoncode SealAdchoices
© 2005 - 2021 WebMD LLC. All rights reserved.

WebMD does not provide medical advice, diagnosis or treatment.

See additional information.

