from ij import IJ

IJ.run("Close All")
imp = IJ.openImage("http://imagej.nih.gov/ij/images/m51.zip")
imp2 = imp.duplicate()
imp2.setTitle("work")
imp2.show()
imp3 = imp.duplicate()
imp3.setTitle("bin")
IJ.setAutoThreshold(imp3, "MaxEntropy dark")
IJ.run("Make Binary")
imp3.show()
IJ.run("Convert to Mask")
imp3.show()
imp4 = imp3.duplicate()
imp4.show()
IJ.run("Make Binary")
imp4.setTitle("EDM-16")
IJ.run(imp4, "EDM 16bits", "")
imp4.show()
