---
title: "Apple-TV"
author: "John Minter"
date: "Started 2022-02-25, Last modified: 2022-02-26"
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\fontsize{18}{19.2}
\fontseries{r}
\selectfont


[Back to Index](../README.html)

# Viewing Programs on Apple TV

1. Turn on TV

2. Turn on Apple TV using the Siri Remote. The button is on the top right
   of the remote.
   
3. Put in my ear buds.

4. Go **_back_** to settings.

5. Choose **video and audio**.

6. Choose **audio output**.

7. Choose **temporary audio outputs**.

8. Add **airpods**

< (Back)    
<     
<      

9. Choose desired programs.

- HBO Max

- Prime Video

- Paramount Plus


# How to Change the Episode on HBO Max

If you’re wondering how to change an episode in HBO Max, look no further. This
article will show you how to do it across several platforms. In addition, we’ll
offer tips to enhance your experience with this relatively new streaming
platform.


## How to Change the Episode in HBO Max on an Apple TV

HBO Max is available on Apple TV, too. If you’re watching your TV show on Apple
TV, but you find one of the episodes boring or you’ve already seen it, you can
easily change to a different one.

Follow these steps to switch episodes in HBO Max on Apple TV:

1. While watching an episode, tap the menu button on your Apple TV remote.

2. Switch between seasons and select the episode you want to watch.


## Rewind or Fast Forward on Apple TV

- Continuously rewind or Fast-Forward

> **Press and hold** the **left**  or **right** on the **click-pad ring**
> **(second generation Siri Remote).**
> **Press `left` or `right` repeatedly to cycle through rewind or**
> **fast-forward speed options (2x, 3x, 4x).** 


While the new Siri Remote that’s included with the 2021 Apple TV 4K has been
redesigned, it retains some of the better elements offered by the old remote.
The glass trackpad is still there but has been replaced by a round trackpad
surrounded by aluminum. This new remote also features raised edges around th
circumference of the circle, providing some tactility to the trackpad.

So when it comes to actually control your movies and TV shows, Apple has
included a couple of different options. The first method to know about if you
want to fast forward on Apple TV is to just skip forwards or backward. This can
be done by simply clicking back or forward on the aforementioned trackpad. When
clicking left or right on the trackpad, you’ll be able to skip around in
10-second increments.

Obviously, skipping in small increments is fine most of the time, but if you
want to actually scrub through a show or movie in order to get to a certain spot,
things are a bit different. In order to fast forward on Apple TV continuously,
you’ll need to press and hold the right button on the trackpad. When you click
the button, the default speed is 2x, but this can be increased to either 3x or
4x speeds by continuing to press the button. Once you’ve reached the spot in the
movie or show that you want, just click the center of the trackpad or the
Play/Pause button in order to resume the content.

[Back to Index](../README.html)

